//! `cargo-zisk-dev gen-ops` — regenerate the precompile seams from the declarative
//! precompile manifests.
//!
//! Reads the workspace registry (`zisk-precompiles.toml`, the enabled set) and each
//! enabled precompile's `zisk-precompile.toml` (its definition), validates the ids,
//! and emits the generated seams:
//!   - `core/src/precompile_ops.gen.rs` — a `zisk_ops_with_precompiles!` wrapper macro
//!     that appends the precompiles' `define_ops!` rows to the hand-written vanilla
//!     ISA rows.
//!   - `executor/src/sm/precompiles.gen.rs` — the per-crate imports and the
//!     `register_precompiles!` invocation (the executor's precompile registry).
//! Base ISA is never touched; only the precompile rows/entries are generated.

use std::{
    collections::HashSet,
    fs,
    path::{Path, PathBuf},
};

use anyhow::{bail, Context, Result};
use serde::Deserialize;

/// Regenerate the zisk-core precompile op tables from the manifests.
#[derive(clap::Args)]
#[command(about = "Regenerate zisk-core precompile op tables from the precompile manifests")]
pub(crate) struct GenOpsCmd {
    /// Workspace precompile registry (the enabled set).
    #[arg(long = "registry", default_value = "zisk-precompiles.toml")]
    registry: PathBuf,

    /// Path to `core/src` (where the generated core `*.gen.rs` files are written).
    #[arg(long = "core-src", default_value = "core/src")]
    core_src: PathBuf,

    /// Path to `executor/src` (where the generated executor `*.gen.rs` files are written).
    #[arg(long = "executor-src", default_value = "executor/src")]
    executor_src: PathBuf,
}

/// Lowest valid precompile `op_type_id` — the reserved band; base op-types are below.
const OP_TYPE_ID_BAND: u64 = 0x1000;

#[derive(Deserialize)]
struct Registry {
    precompiles: RegistrySection,
}

#[derive(Deserialize)]
struct RegistrySection {
    enabled: Vec<String>,
}

#[derive(Deserialize)]
struct Manifest {
    precompile: Precompile,
}

#[derive(Deserialize)]
struct Precompile {
    /// Type-name stem: `<name>Manager/Instance/Collector/CounterInputGen`, register variant.
    name: String,
    op_type: String,
    op_type_id: u64,
    /// Core `*_OP_TYPE_ID` const name (used by the register invocation + op-type routing).
    op_type_id_const: String,
    /// Crate exporting the per-precompile SM types (`precomp_*`).
    sm_crate: String,
    /// `zisk_pil` AIR-ids const for this precompile.
    air_ids: String,
    /// Whether the SM owns a rank-assigned instance (`pctx.add_instance_assign`).
    #[serde(default)]
    rank_assign: bool,
    #[serde(default)]
    op: Vec<Op>,
}

#[derive(Deserialize)]
struct Op {
    name: String,
    str: String,
    opcode: u64,
    cost: String,
    input_size: u64,
    output_size: u64,
    #[serde(default)]
    stats: bool,
}

/// Resolve a registry entry to its precompile directory: a bare name maps to
/// `precompiles/<name>`, anything containing a path separator is used as-is.
fn resolve_dir(entry: &str) -> PathBuf {
    if entry.contains('/') {
        PathBuf::from(entry)
    } else {
        Path::new("precompiles").join(entry)
    }
}

/// Emit the `zisk_ops_with_precompiles!` wrapper: it re-emits the caller's base rows
/// then appends one `define_ops!` row per precompile op.
fn emit(precompiles: &[Precompile]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo-zisk-dev gen-ops` — do not edit by hand.\n\
         //\n\
         // Wraps the hand-written vanilla-ISA `define_ops!` rows and appends the enabled\n\
         // precompiles' rows. Generated from `zisk-precompiles.toml` + each precompile's\n\
         // `zisk-precompile.toml`. Opcodes are explicit, so ZiskOp order isn't ABI.\n\
         macro_rules! zisk_ops_with_precompiles {\n    \
             ($($base:tt),* $(,)?) => {\n        \
                 define_ops! {\n            \
                     $($base,)*\n",
    );
    for p in precompiles {
        for op in &p.op {
            let stats_fn =
                if op.stats { format!("ops_{}", op.str) } else { "ops_none".to_string() };
            out.push_str(&format!(
                "            ({}, \"{}\", {}, {}, {:#x}, {}, {}, opc_{}, op_{}, {}),\n",
                op.name,
                op.str,
                p.op_type,
                op.cost,
                op.opcode,
                op.input_size,
                op.output_size,
                op.str,
                op.str,
                stats_fn,
            ));
        }
    }
    out.push_str("        }\n    };\n}\n");
    out
}

/// Emit the executor's precompile registry: the per-crate type imports plus the
/// `register_precompiles!` invocation (one entry per precompile, in registry order).
fn emit_register(precompiles: &[Precompile]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo-zisk-dev gen-ops` — do not edit by hand.\n\
         //\n\
         // The executor's precompile registry: per-crate SM-type imports and the\n\
         // `register_precompiles!` invocation, in `zisk-precompiles.toml` order.\n\
         // Generated from each precompile's `zisk-precompile.toml`.\n\n",
    );
    for p in precompiles {
        out.push_str(&format!(
            "use {krate}::{{{n}Collector, {n}CounterInputGen, {n}Instance, {n}Manager}};\n",
            krate = p.sm_crate,
            n = p.name,
        ));
    }
    out.push_str("use zisk_common::ComponentBuilder;\n");
    out.push_str(&format!(
        "use zisk_core::{{{}}};\n",
        precompiles.iter().map(|p| p.op_type_id_const.as_str()).collect::<Vec<_>>().join(", ")
    ));
    out.push_str(&format!(
        "use zisk_pil::{{{}}};\n\n",
        precompiles.iter().map(|p| p.air_ids.as_str()).collect::<Vec<_>>().join(", ")
    ));

    out.push_str("crate::register_precompiles! {\n");
    for p in precompiles {
        out.push_str(&format!(
            "    {name} [\n        op: {op},\n        air: {air},\n        rank_assign: {rank},\n    ] => {name}Manager<F>,\n",
            name = p.name,
            op = p.op_type_id_const,
            air = p.air_ids,
            rank = p.rank_assign,
        ));
    }
    out.push_str("}\n");
    out
}

/// Reject duplicate/out-of-band opcodes and op-type ids.
fn validate(precompiles: &[Precompile]) -> Result<()> {
    let mut op_type_ids = HashSet::new();
    let mut opcodes = HashSet::new();
    for p in precompiles {
        if p.op_type_id < OP_TYPE_ID_BAND {
            bail!(
                "op_type '{}': op_type_id {:#x} is below the reserved precompile band {:#x}",
                p.op_type,
                p.op_type_id,
                OP_TYPE_ID_BAND
            );
        }
        if !op_type_ids.insert(p.op_type_id) {
            bail!("duplicate op_type_id {:#x} (op_type '{}')", p.op_type_id, p.op_type);
        }
        for op in &p.op {
            if !opcodes.insert(op.opcode) {
                bail!("duplicate opcode {:#x} (op '{}')", op.opcode, op.name);
            }
        }
    }
    Ok(())
}

/// Load and parse the registry plus each enabled precompile's manifest. Entry dirs
/// resolve under `base_dir` — `.` for the CLI (run from the repo root), the repo root
/// for the `generated_seams_up_to_date` test (which runs from any CWD).
fn load_precompiles(registry_path: &Path, base_dir: &Path) -> Result<Vec<Precompile>> {
    let registry: Registry = toml::from_str(
        &fs::read_to_string(registry_path)
            .with_context(|| format!("reading registry {}", registry_path.display()))?,
    )
    .with_context(|| format!("parsing registry {}", registry_path.display()))?;

    let mut precompiles = Vec::new();
    for entry in &registry.precompiles.enabled {
        let manifest_path = base_dir.join(resolve_dir(entry)).join("zisk-precompile.toml");
        let manifest: Manifest = toml::from_str(
            &fs::read_to_string(&manifest_path)
                .with_context(|| format!("reading manifest {}", manifest_path.display()))?,
        )
        .with_context(|| format!("parsing manifest {}", manifest_path.display()))?;
        precompiles.push(manifest.precompile);
    }
    Ok(precompiles)
}

impl GenOpsCmd {
    pub(crate) fn run(&self) -> Result<()> {
        let precompiles = load_precompiles(&self.registry, Path::new("."))?;
        validate(&precompiles)?;

        let ops_path = self.core_src.join("precompile_ops.gen.rs");
        fs::write(&ops_path, emit(&precompiles))
            .with_context(|| format!("writing {}", ops_path.display()))?;

        let reg_path = self.executor_src.join("sm/precompiles.gen.rs");
        fs::write(&reg_path, emit_register(&precompiles))
            .with_context(|| format!("writing {}", reg_path.display()))?;

        println!(
            "generated {} + {} ({} precompiles, {} ops)",
            ops_path.display(),
            reg_path.display(),
            precompiles.len(),
            precompiles.iter().map(|p| p.op.len()).sum::<usize>()
        );
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Best-of-both guard: the `zisk-precompile.toml` manifests stay the authoring
    /// surface, and this test gives them the compile-time safety a Rust const table
    /// would — run at `cargo test`, not only when someone runs `gen-ops`. It fails if
    /// any manifest is invalid (id band / uniqueness) or if the checked-in generated
    /// seams have drifted from what the manifests produce (a stale `.gen.rs`, or a
    /// hand-edit to a generated file). Fix by re-running `cargo-zisk-dev gen-ops`.
    #[test]
    fn generated_seams_up_to_date() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("cli crate dir has a parent (the repo root)");

        let precompiles = load_precompiles(&root.join("zisk-precompiles.toml"), root)
            .expect("load the enabled precompile manifests");
        // Bad values (below the reserved band, duplicate op_type_id / opcode) fail here.
        validate(&precompiles).expect("precompile manifests pass id validation");

        // Drift guard: regenerate in memory and compare byte-for-byte with the
        // committed files (`run()` writes `emit(..)` output verbatim, no rustfmt).
        let ops_path = root.join("core/src/precompile_ops.gen.rs");
        assert_eq!(
            fs::read_to_string(&ops_path).expect("read committed core seam"),
            emit(&precompiles),
            "{} is stale — run `cargo-zisk-dev gen-ops`",
            ops_path.display(),
        );

        let reg_path = root.join("executor/src/sm/precompiles.gen.rs");
        assert_eq!(
            fs::read_to_string(&reg_path).expect("read committed executor seam"),
            emit_register(&precompiles),
            "{} is stale — run `cargo-zisk-dev gen-ops`",
            reg_path.display(),
        );
    }
}
