use crate::get_asm_paths;
use crate::guest::ProgramId;
use crate::GuestProgram;
use crate::ProofOpts;
use crate::{
    check_paths_exist, ensure_rom, get_rom_bin_path,
    prover::{ProverBackend, ProverEngine, ZiskBackend},
    ZiskAggPhaseResult, ZiskExecuteResult, ZiskPhaseResult, ZiskProveResult,
    ZiskVerifyConstraintsResult,
};
use asm_runner::HintsShmem;
use asm_runner::{AsmRunnerOptions, AsmServices};
use executor::{initialize_executor, AsmResources};
use precompiles_hints::HintsProcessor;
use proofman::{
    AggProofs, AggProofsRegister, ProofMan, ProvePhase, ProvePhaseInputs, SnarkWrapper, WitnessInfo,
};
use proofman_common::{
    initialize_logger, ProofOptions, ProofmanOptions, RankInfo, RowInfo, VerboseMode,
};
use proofman_util::{timer_start_info, timer_stop_and_log_info};
use rom_setup::{generate_assembly, get_output_path, DEFAULT_CACHE_PATH};
use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, RwLock};
use zisk_common::io::StreamSource;
use zisk_common::io::ZiskStdin;
use zisk_common::ExecutorStatsHandle;
use zisk_common::ZiskExecutorTime;
use zisk_common::{
    ProofMode, ZiskProgramVK, ZiskProof, ZiskProofWithPublicValues, ZiskPublics, ZiskVK,
};
use zisk_core::{Riscv2zisk, ZiskRom};
use zisk_distributed_common::LoggingConfig;

use anyhow::Result;

pub struct Asm;

impl ZiskBackend for Asm {
    type Prover = AsmProver;
}

/// Builder for ASM backend setup with optional hints support.
pub struct AsmSetupBuilder<'a> {
    prover: &'a AsmProver,
    elf: &'a GuestProgram,
    with_hints: bool,
}

impl<'a> AsmSetupBuilder<'a> {
    fn new(prover: &'a AsmProver, elf: &'a GuestProgram) -> Self {
        Self { prover, elf, with_hints: false }
    }

    /// Enable hints processing for this program.
    ///
    /// When hints are enabled, the ASM backend will process hints generated by the guest program.
    pub fn with_hints(mut self) -> Self {
        self.with_hints = true;
        self
    }

    pub fn run(self) -> Result<()> {
        self.prover.setup_internal(self.elf, self.with_hints)
    }
}

pub struct AsmProver {
    pub(crate) core_prover: AsmCoreProver,
    program_cache: Arc<RwLock<HashMap<ProgramId, Arc<ZiskRom>>>>,
}

impl AsmProver {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        snark_wrapper: bool,
        preload_snark: bool,
        proving_key: PathBuf,
        proving_key_snark: PathBuf,
        shared_tables: bool,
        base_port: Option<u16>,
        unlock_mapped_memory: bool,
        asm_out_file: bool,
        no_auto_setup: bool,
        options: ProofmanOptions,
        is_distributed: bool,
        logging_config: Option<LoggingConfig>,
    ) -> Result<Self> {
        let core_prover = AsmCoreProver::new(
            snark_wrapper,
            preload_snark,
            proving_key,
            proving_key_snark,
            shared_tables,
            base_port,
            unlock_mapped_memory,
            asm_out_file,
            no_auto_setup,
            options,
            is_distributed,
            logging_config,
        )?;

        let program_cache = Arc::new(RwLock::new(HashMap::new()));
        Ok(Self { core_prover, program_cache })
    }
}

impl ProverEngine for AsmProver {
    type Builder<'a> = AsmSetupBuilder<'a>;

    fn setup<'a>(&'a self, elf: &'a GuestProgram) -> Self::Builder<'a> {
        AsmSetupBuilder::new(self, elf)
    }

    fn setup_internal(&self, elf: &GuestProgram, with_hints: bool) -> Result<()> {
        let pctx = self.core_prover.backend.get_pctx()?;
        ensure_rom(&pctx, elf)?;

        let world_rank = self.core_prover.rank_info.world_rank;
        let local_rank = self.core_prover.rank_info.local_rank;
        let n_processes = self.core_prover.rank_info.n_processes;
        let is_distributed = self.core_prover.asm_info.is_distributed;
        let unlock_mapped_memory = self.core_prover.asm_info.unlock_mapped_memory;
        let asm_out_file = self.core_prover.asm_info.asm_out_file;
        let verbose_mode = self.core_prover.asm_info.verbose;
        let base_port = Some(AsmServices::port_base_offset(
            self.core_prover.asm_info.base_port,
            n_processes,
            self.core_prover.asm_info.n_setups.load(Ordering::SeqCst),
        ));

        let rv2zk = Riscv2zisk::new(elf.elf());

        let zisk_rom = rv2zk.run().unwrap_or_else(|e| panic!("Application error: {e}"));
        let zisk_rom = Arc::new(zisk_rom);

        let default_cache_path = std::env::var("HOME")
            .map(PathBuf::from)
            .map_err(|e| anyhow::anyhow!("Failed to read HOME environment variable: {e}"))?
            .join(DEFAULT_CACHE_PATH);

        let (asm_mt_filename, asm_rh_filename) = get_asm_paths(elf, with_hints)?;

        let asm_mt_path = default_cache_path.join(asm_mt_filename);
        let asm_rh_path = default_cache_path.join(asm_rh_filename);

        if check_paths_exist(&asm_mt_path).is_err() || check_paths_exist(&asm_rh_path).is_err() {
            if self.core_prover.asm_info.no_auto_setup {
                return Err(anyhow::anyhow!(
                        "Assembly files not found for ELF {}. Force ROM setup is enabled, but assembly files are still missing. Please ensure that the assembly generation process has been completed successfully.",
                        elf.name()
                    ));
            }

            if pctx.mpi_ctx.rank == 0 {
                tracing::info!(
                    ">>> ROM SETUP (one time only) - Generating assembly files for ELF: {}",
                    elf.name()
                );
                timer_start_info!(ROM_SETUP);
                let output_path = get_output_path(&None)?;
                generate_assembly(
                    elf.elf(),
                    elf.name(),
                    &output_path,
                    with_hints,
                    self.core_prover.asm_info.verbose != VerboseMode::Info,
                )?;
                timer_stop_and_log_info!(ROM_SETUP);
                tracing::info!("<<< ROM SETUP complete - Assembly files cached for future use");
            }
            pctx.mpi_ctx.barrier();
        }

        pctx.mpi_ctx.barrier();

        timer_start_info!(STARTING_ASM_MICROSERVICES);
        let asm_services = AsmServices::new(world_rank, local_rank, base_port);

        let asm_runner_options = AsmRunnerOptions::new()
            .with_base_port(base_port)
            .with_world_rank(world_rank)
            .with_local_rank(local_rank)
            .with_verbose(verbose_mode == VerboseMode::Debug)
            .with_metrics(verbose_mode == VerboseMode::Debug)
            .with_unlock_mapped_memory(unlock_mapped_memory)
            .with_asm_out_file(asm_out_file);

        asm_services.start_asm_services(&asm_mt_path, asm_runner_options)?;
        timer_stop_and_log_info!(STARTING_ASM_MICROSERVICES);

        let mpi_broadcast_fn = (is_distributed && n_processes > 1 && with_hints).then(|| {
            let pctx = pctx.clone();
            Arc::new(move |data: &mut Vec<u8>| {
                pctx.mpi_ctx.broadcast(data);
                Ok(())
            }) as Arc<dyn Fn(&mut Vec<u8>) -> Result<()> + Send + Sync>
        });

        let init_rom = !is_distributed && world_rank == 0;

        self.core_prover.backend.set_asm_resources(AsmResources::new(
            world_rank,
            local_rank,
            base_port,
            unlock_mapped_memory,
            verbose_mode,
            with_hints,
            mpi_broadcast_fn,
            init_rom,
            asm_services,
        )?)?;

        self.core_prover.asm_info.n_setups.fetch_add(1, Ordering::SeqCst);

        self.program_cache.write().unwrap().insert(elf.program_id.clone(), zisk_rom);
        Ok(())
    }
    fn world_rank(&self) -> i32 {
        self.core_prover.rank_info.world_rank
    }

    fn local_rank(&self) -> i32 {
        self.core_prover.rank_info.local_rank
    }

    fn set_stdin(&self, stdin: ZiskStdin) -> Result<()> {
        self.core_prover.backend.set_stdin(stdin)
    }

    fn register_program(&self, program_id: &ProgramId) -> Result<()> {
        let rom = self
            .program_cache
            .read()
            .ok()
            .and_then(|cache| cache.get(program_id).cloned())
            .ok_or_else(|| {
            anyhow::anyhow!("Program '{}' not found in cache. Call setup() first.", program_id.name)
        })?;
        let pctx = self.core_prover.backend.get_pctx()?;
        let rom_bin_path = get_rom_bin_path(&pctx, program_id)?;
        self.core_prover.backend.register_program(rom, &rom_bin_path)
    }

    fn executed_steps(&self) -> u64 {
        self.core_prover
            .backend
            .execution_result()
            .map(|(exec_result, _)| exec_result.steps)
            .unwrap_or(0)
    }

    fn get_execution_info(&self) -> Result<(WitnessInfo, ZiskExecutorTime)> {
        self.core_prover.backend.get_execution_info()
    }

    fn execute(
        &self,
        program: &GuestProgram,
        stdin: ZiskStdin,
        output_path: Option<PathBuf>,
    ) -> Result<ZiskExecuteResult> {
        self.register_program(&program.program_id)?;
        self.core_prover.backend.execute(stdin, output_path)
    }

    fn stats(
        &self,
        program: &GuestProgram,
        stdin: ZiskStdin,
        debug_info: Option<Option<String>>,
        minimal_memory: bool,
        mpi_node: Option<u32>,
    ) -> Result<(i32, i32, Option<ExecutorStatsHandle>)> {
        self.register_program(&program.program_id)?;
        self.core_prover.backend.stats(stdin, debug_info, minimal_memory, mpi_node)
    }

    fn get_instance_trace(
        &self,
        instance_id: usize,
        first_row: usize,
        num_rows: usize,
        offset: Option<usize>,
    ) -> Result<Vec<RowInfo>> {
        self.core_prover.backend.get_instance_trace(instance_id, first_row, num_rows, offset)
    }

    fn get_instance_air_values(&self, instance_id: usize) -> Result<Vec<u64>> {
        self.core_prover.backend.get_instance_air_values(instance_id)
    }

    fn get_instance_fixed(
        &self,
        instance_id: usize,
        first_row: usize,
        num_rows: usize,
        offset: Option<usize>,
    ) -> Result<Vec<RowInfo>> {
        self.core_prover.backend.get_instance_fixed(instance_id, first_row, num_rows, offset)
    }

    fn verify_constraints(
        &self,
        program: &GuestProgram,
        stdin: ZiskStdin,
        debug_info: Option<Option<String>>,
    ) -> Result<ZiskVerifyConstraintsResult> {
        self.register_program(&program.program_id)?;
        self.core_prover.backend.verify_constraints(stdin, debug_info)
    }

    fn vk(&self, elf: &GuestProgram) -> Result<ZiskProgramVK> {
        self.core_prover.backend.vk(elf)
    }

    fn prove(
        &self,
        program: &GuestProgram,
        stdin: ZiskStdin,
        mode: ProofMode,
        proof_options: ProofOpts,
    ) -> Result<ZiskProveResult> {
        self.register_program(&program.program_id)?;
        self.core_prover.backend.prove(stdin, mode, proof_options)
    }

    fn plonk(
        &self,
        proof: &ZiskProof,
        publics: &ZiskPublics,
        vk: &ZiskProgramVK,
    ) -> Result<ZiskProofWithPublicValues> {
        self.core_prover.backend.plonk(proof, publics, vk)
    }

    fn minimal(
        &self,
        proof: &ZiskProof,
        publics: &ZiskPublics,
        vk: &ZiskProgramVK,
    ) -> Result<ZiskProofWithPublicValues> {
        self.core_prover.backend.minimal(proof, publics, vk)
    }

    fn prove_phase(
        &self,
        phase_inputs: ProvePhaseInputs,
        options: ProofOptions,
        phase: ProvePhase,
    ) -> Result<ZiskPhaseResult> {
        self.core_prover.backend.prove_phase(phase_inputs, options, phase)
    }

    fn set_partition(
        &self,
        total_compute_units: usize,
        allocation: Vec<u32>,
        rank_id: usize,
    ) -> Result<()> {
        self.core_prover.backend.set_partition(total_compute_units, allocation, rank_id)
    }

    fn register_aggregated_proofs(&self, agg_proofs: Vec<AggProofsRegister>) -> Result<()> {
        self.core_prover.backend.register_aggregated_proofs(agg_proofs)
    }

    fn aggregate_proofs(
        &self,
        agg_proofs: Vec<AggProofs>,
        last_proof: bool,
        final_proof: bool,
        options: &ProofOptions,
    ) -> Result<Option<ZiskAggPhaseResult>> {
        self.core_prover.backend.aggregate_proofs(agg_proofs, last_proof, final_proof, options)
    }

    fn mpi_broadcast(&self, data: &mut Vec<u8>) -> Result<()> {
        self.core_prover.backend.mpi_broadcast(data)
    }

    fn get_vadcop_vk(&self, minimal: bool) -> Result<ZiskVK> {
        self.core_prover.backend.get_vadcop_vk(minimal)
    }

    fn submit_hint(&self, bytes: &[u8]) -> Result<()> {
        self.core_prover.backend.submit_hint(bytes)
    }

    fn submit_input(&self, bytes: &[u8]) -> Result<()> {
        self.core_prover.backend.submit_input(bytes)
    }

    fn register_hints_stream(&self, stream: StreamSource) -> Result<()> {
        self.core_prover.backend.register_hints_stream(stream)
    }

    fn get_hints_processor(&self) -> Result<Option<Arc<HintsProcessor<HintsShmem>>>> {
        self.core_prover.backend.get_hints_processor()
    }

    fn set_active_services(&self, is_first_partition: bool) -> Result<()> {
        self.core_prover.backend.set_active_services(is_first_partition)
    }

    fn reset_resources(&self) -> Result<()> {
        self.core_prover.backend.reset_resources()
    }

    fn cancel(&self) {
        self.core_prover.backend.cancel();
    }
}

pub struct AsmInfo {
    pub is_distributed: bool,
    pub base_port: Option<u16>,
    pub unlock_mapped_memory: bool,
    pub asm_out_file: bool,
    pub verbose: VerboseMode,
    pub no_auto_setup: bool,
    pub n_setups: AtomicU64,
}

pub struct AsmCoreProver {
    backend: ProverBackend,
    rank_info: RankInfo,
    asm_info: AsmInfo,
}

impl AsmCoreProver {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        use_snark_wrapper: bool,
        preload_snark: bool,
        proving_key: PathBuf,
        proving_key_snark: PathBuf,
        shared_tables: bool,
        base_port: Option<u16>,
        unlock_mapped_memory: bool,
        asm_out_file: bool,
        no_auto_setup: bool,
        options: ProofmanOptions,
        is_distributed: bool,
        logging_config: Option<LoggingConfig>,
    ) -> Result<Self> {
        check_paths_exist(&proving_key)?;
        let proofman = ProofMan::new(proving_key.clone(), options.clone())
            .map_err(|e| anyhow::anyhow!(e.to_string()))?;

        let rank_info = proofman.get_rank_info();

        if logging_config.is_some() {
            zisk_distributed_common::init(logging_config.as_ref(), Some(&rank_info))?;
        } else {
            initialize_logger(options.verbose_mode, Some(&rank_info));
        }

        proofman.set_barrier();

        let mut snark_wrapper = None;
        if use_snark_wrapper {
            check_paths_exist(&proving_key_snark)?;
            let (aux_trace, d_buffers, reload_fixed_pols_gpu) = proofman.get_preallocated_buffers();
            snark_wrapper = Some(SnarkWrapper::new_with_preallocated_buffers(
                &proving_key_snark,
                options.verbose_mode,
                Some(aux_trace),
                Some(d_buffers),
                Some(reload_fixed_pols_gpu),
                preload_snark,
                options.gpu,
            )?);
        }

        let executor =
            initialize_executor(options.verbose_mode, shared_tables, true, &proofman.get_wcm())?;

        let core = ProverBackend::new(
            proofman,
            snark_wrapper,
            executor,
            proving_key,
            Some(proving_key_snark),
        );

        Ok(Self {
            backend: core,
            rank_info,
            asm_info: AsmInfo {
                is_distributed,
                base_port,
                unlock_mapped_memory,
                asm_out_file,
                verbose: options.verbose_mode,
                no_auto_setup,
                n_setups: AtomicU64::new(0),
            },
        })
    }
}
