use crate::execute_client::ExecuteClient;
use crate::{
    check_paths_exist, ensure_program_vk, get_asm_paths, get_rom_bin_path,
    guest::ProgramId,
    prover::{ProverBackend, ProverEngine, ZiskBackend, ZiskProver},
    BackendProverOpts, ExecuteOutput, GuestProgram, ProveOutput, VerifyConstraintsOutput,
    ZiskAggPhaseResult, ZiskPhaseResult,
};
use asm_runner::{AsmRunnerOptions, AsmServices, HintsShmem};
use executor::{AsmResources, AsmSharedResources, GpuBufferSource, ZiskExecutor};
use precompiles_hints::HintsProcessor;
use proofman::{
    AggProofs, AggProofsRegister, PlanningInfo, ProofMan, ProvePhase, ProvePhaseInputs,
    SnarkWrapper, WitnessInfo,
};
use proofman_common::{
    initialize_logger, DebugReport, ProofCtx, ProofOptions, ProofmanOptions, RankInfo, RowInfo,
    VerboseMode,
};
use proofman_starks_lib_c::{get_unified_buffer_gpu_c, get_unified_buffer_gpu_size_c};
use proofman_util::{timer_start_info, timer_stop_and_log_info};
use rom_setup::{generate_assembly, get_output_path};
use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::{
    atomic::{AtomicBool, AtomicU64, Ordering},
    {Arc, RwLock},
};
use zisk_cluster_common::LoggingConfig;
use zisk_common::{
    io::{StreamSource, ZiskStdin},
    AirInstanceCount, ExecutorStatsHandle, ProgramVK, ProofKind, PublicValues, SetupKey,
    StatsCostPerType, ZiskExecutorTime, ZiskPaths,
};
use zisk_core::{Riscv2zisk, ZiskRom};

use anyhow::Result;

pub struct Asm;

impl ZiskBackend for Asm {
    type Prover = AsmProver;
}

/// Builder for ASM backend setup with optional hints support.
pub struct AsmSetupBuilder<'a> {
    prover: &'a AsmProver,
    elf: &'a GuestProgram,
    with_hints: bool,
    emulator_only: bool,
}

impl<'a> AsmSetupBuilder<'a> {
    fn new(prover: &'a AsmProver, elf: &'a GuestProgram) -> Self {
        Self { prover, elf, with_hints: false, emulator_only: false }
    }

    /// Enable hints processing for this program.
    ///
    /// When hints are enabled, the ASM backend will process hints generated by the guest program.
    pub fn with_hints(mut self) -> Self {
        self.with_hints = true;
        self
    }

    pub fn emulator_only(mut self) -> Self {
        self.emulator_only = true;
        self
    }

    pub fn run(self) -> Result<ProgramVK> {
        self.prover.setup_internal(self.elf, self.with_hints, self.emulator_only)
    }
}

struct ProgramEntry {
    zisk_rom: Arc<ZiskRom>,
    program_vk: ProgramVK,
    /// Keeps ASM resources (C processes + shmem) alive for the full worker lifetime.
    resources: Option<Arc<AsmResources>>,
}

pub struct AsmProver {
    core_prover: AsmCoreProver,
    program_cache: RwLock<HashMap<SetupKey, ProgramEntry>>,
    /// Tracks whether the currently registered program was set up with hints.
    current_with_hints: AtomicBool,
    /// Tracks whether the currently registered program was set up emulator-only.
    /// When true, prove/verify_constraints/stats are rejected.
    current_emulator_only: AtomicBool,
}

impl AsmProver {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        snark_wrapper: bool,
        preload_snark: bool,
        proving_key: PathBuf,
        proving_key_snark: PathBuf,
        shared_tables: bool,
        unlock_mapped_memory: bool,
        asm_out_file: bool,
        no_auto_setup: bool,
        options: ProofmanOptions,
        is_distributed: bool,
        logging_config: Option<LoggingConfig>,
        cpu_mops: bool,
    ) -> Result<Self> {
        AsmServices::cleanup_stale_shmem();
        let core_prover = AsmCoreProver::new(
            snark_wrapper,
            preload_snark,
            proving_key,
            proving_key_snark,
            shared_tables,
            unlock_mapped_memory,
            asm_out_file,
            no_auto_setup,
            options,
            is_distributed,
            logging_config,
            cpu_mops,
        )?;
        Ok(Self {
            core_prover,
            program_cache: RwLock::new(HashMap::new()),
            current_with_hints: AtomicBool::new(false),
            current_emulator_only: AtomicBool::new(false),
        })
    }

    fn get_asm_cache_paths(
        elf: &GuestProgram,
        with_hints: bool,
    ) -> Result<(PathBuf, PathBuf), anyhow::Error> {
        let default_cache_path = &ZiskPaths::global().cache;
        let (asm_mt_filename, asm_rh_filename) = get_asm_paths(elf, with_hints)?;
        let asm_mt_path = default_cache_path.join(asm_mt_filename);
        let asm_rh_path = default_cache_path.join(asm_rh_filename);

        Ok((asm_mt_path, asm_rh_path))
    }

    fn start_asm_service(
        &self,
        elf: &GuestProgram,
        zisk_rom: Arc<ZiskRom>,
        program_vk: &ProgramVK,
        asm_mt_path: PathBuf,
        with_hints: bool,
        pctx: &Arc<ProofCtx<fields::Goldilocks>>,
    ) -> std::result::Result<(), anyhow::Error> {
        let world_rank = self.core_prover.rank_info.world_rank;
        let local_rank = self.core_prover.rank_info.local_rank;
        let n_processes = self.core_prover.rank_info.n_processes;
        let is_distributed = self.core_prover.asm_info.is_distributed;
        let unlock_mapped_memory = self.core_prover.asm_info.unlock_mapped_memory;
        let asm_out_file = self.core_prover.asm_info.asm_out_file;
        let verbose_mode = self.core_prover.asm_info.verbose;

        timer_start_info!(STARTING_ASM_MICROSERVICES);

        let asm_runner_options = AsmRunnerOptions::new()
            .with_local_rank(local_rank)
            .with_verbose(verbose_mode == VerboseMode::Debug)
            .with_metrics(verbose_mode == VerboseMode::Debug)
            .with_unlock_mapped_memory(unlock_mapped_memory)
            .with_asm_out_file(asm_out_file);

        let mpi_broadcast_fn = (is_distributed && n_processes > 1 && with_hints && world_rank == 0)
            .then(|| {
                let pctx = pctx.clone();
                Arc::new(move |data: &mut Vec<u8>| {
                    pctx.mpi_ctx.broadcast(data);
                    Ok(())
                }) as Arc<dyn Fn(&mut Vec<u8>) -> Result<()> + Send + Sync>
            });

        let init_rom = !is_distributed && world_rank == 0;

        if let Some(entry) = self.program_cache.read().unwrap().get(&SetupKey::new(
            &*elf.program_id.hash_id,
            with_hints,
            false,
        )) {
            timer_stop_and_log_info!(STARTING_ASM_MICROSERVICES);
            let resources =
                entry.resources.clone().expect("full-asm cache entry must have ASM resources");
            self.core_prover.backend.set_asm_resources(resources)?;
            return Ok(());
        }

        // The program hash is carried in the sem_prefix (so the semaphores are
        // per-program), while the shmem segments are keyed by pid+local_rank only
        // and are shared/reused across program hashes. Each program still gets its
        // own AsmSharedResources; previous programs' resources stay alive in the
        // pool via Arc.
        let asm_services = AsmServices::new(
            world_rank,
            local_rank,
            elf.program_id.hash_id.as_ref().to_string(),
            &asm_mt_path,
            with_hints,
            asm_runner_options,
        )?;

        // Borrow proofman's already-allocated unified GPU buffer.
        // Zero values when CUDA is unavailable; downstream consumers no-op on (0, 0).
        // When --cpu-mops is set, force the planner onto CPU regardless of buffer
        // availability; proofman still runs proof generation on GPU.
        let gpu_buffer_source = if self.core_prover.asm_info.cpu_mops {
            GpuBufferSource::Cpu
        } else {
            let (gpu_buf_ptr, gpu_buf_size) = pctx.get_gpu_buffer();
            GpuBufferSource::Borrowed { ptr: gpu_buf_ptr, size: gpu_buf_size as usize }
        };

        let shared = Arc::new(AsmSharedResources::new(
            local_rank,
            unlock_mapped_memory,
            verbose_mode,
            mpi_broadcast_fn,
            init_rom,
            with_hints,
            asm_services.shm_prefix(),
            gpu_buffer_source,
        )?);
        timer_stop_and_log_info!(STARTING_ASM_MICROSERVICES);

        let resources = Arc::new(AsmResources::new(shared, asm_services)?);
        self.core_prover.backend.set_asm_resources(resources.clone())?;
        self.core_prover.asm_info.n_setups.fetch_add(1, Ordering::SeqCst);
        self.program_cache.write().unwrap().insert(
            SetupKey::new(&*elf.program_id.hash_id, with_hints, false),
            ProgramEntry { zisk_rom, resources: Some(resources), program_vk: program_vk.clone() },
        );

        Ok(())
    }

    fn register_program_for_emulator(&self, program_id: &ProgramId) -> Result<()> {
        let with_hints = self.current_with_hints.load(Ordering::SeqCst);
        let rom = {
            let guard = self.program_cache.read().unwrap();
            let full_key = SetupKey::new(&*program_id.hash_id, with_hints, false);
            let emu_key = SetupKey::new(&*program_id.hash_id, with_hints, true);
            guard
                .get(&full_key)
                .or_else(|| guard.get(&emu_key))
                .map(|e| e.zisk_rom.clone())
                .ok_or_else(|| {
                    anyhow::anyhow!(
                        "Program '{}' (with_hints={}) not found in cache. Call setup() first.",
                        program_id.name,
                        with_hints
                    )
                })?
        };

        self.core_prover.backend.clear_asm_resources()?;

        let pctx = self.core_prover.backend.get_pctx()?;
        let rom_bin_path = get_rom_bin_path(&pctx, program_id)?;
        self.core_prover.backend.register_program(rom, &rom_bin_path, with_hints)
    }

    /// Execute via the Rust emulator path, regardless of how the program was set up.
    pub fn execute_emulator(
        &self,
        program: &GuestProgram,
        stdin: ZiskStdin,
    ) -> Result<ExecuteOutput> {
        self.register_program_for_emulator(&program.program_id)?;
        self.core_prover.backend.execute(stdin)
    }

    /// Generate a proof via the Rust emulator path, regardless of how the program was set up.
    /// Bypasses the `current_emulator_only` guard on the regular `prove` method.
    pub fn prove_emulator(
        &self,
        program: &GuestProgram,
        stdin: ZiskStdin,
        proof_kind: ProofKind,
        prover_options: BackendProverOpts,
    ) -> Result<ProveOutput> {
        self.register_program_for_emulator(&program.program_id)?;
        self.core_prover.backend.prove(stdin, proof_kind, prover_options)
    }

    /// Verify constraints via the Rust emulator path, regardless of how the program was set up.
    pub fn verify_constraints_emulator(
        &self,
        program: &GuestProgram,
        stdin: ZiskStdin,
        debug_info: Option<Option<String>>,
    ) -> Result<VerifyConstraintsOutput> {
        self.register_program_for_emulator(&program.program_id)?;
        self.core_prover.backend.verify_constraints(stdin, debug_info)
    }
}

impl ProverEngine for AsmProver {
    type Builder<'a> = AsmSetupBuilder<'a>;

    fn setup<'a>(&'a self, elf: &'a GuestProgram) -> Self::Builder<'a> {
        AsmSetupBuilder::new(self, elf)
    }

    fn setup_internal(
        &self,
        elf: &GuestProgram,
        with_hints: bool,
        emulator_only: bool,
    ) -> Result<ProgramVK> {
        // Early return if program is already cached for this exact mode.
        if let Some(entry) = self.program_cache.read().unwrap().get(&SetupKey::new(
            &*elf.program_id.hash_id,
            with_hints,
            emulator_only,
        )) {
            self.current_with_hints.store(with_hints, Ordering::SeqCst);
            self.current_emulator_only.store(emulator_only, Ordering::SeqCst);
            return Ok(entry.program_vk.clone());
        }

        let pctx = self.core_prover.backend.get_pctx()?;

        // Computes the verification key (VK) for an ELF: loads it from cache if present.
        let program_vk = ensure_program_vk(&pctx, elf)?;

        // Generate Zisk ROM from ELF
        let rv2zk = Riscv2zisk::new(elf.elf());
        let zisk_rom = rv2zk.run().map_err(|e| anyhow::anyhow!(e.to_string()))?;
        let zisk_rom = Arc::new(zisk_rom);

        if emulator_only {
            self.program_cache.write().unwrap().insert(
                SetupKey::new(&*elf.program_id.hash_id, with_hints, true),
                ProgramEntry { zisk_rom, resources: None, program_vk: program_vk.clone() },
            );
            self.current_with_hints.store(with_hints, Ordering::SeqCst);
            self.current_emulator_only.store(true, Ordering::SeqCst);
            return Ok(program_vk);
        }

        // Assembly file generation
        let (asm_mt_path, asm_rh_path) = Self::get_asm_cache_paths(elf, with_hints)?;

        let asm_mt_path_exists = check_paths_exist(&asm_mt_path).is_ok();
        let asm_rh_path_exists = check_paths_exist(&asm_rh_path).is_ok();

        if !asm_mt_path_exists || !asm_rh_path_exists {
            if self.core_prover.asm_info.no_auto_setup {
                return Err(anyhow::anyhow!(
                        "Assembly files not found for ELF {}. Force ROM setup is enabled, but assembly files are still missing. Please ensure that the assembly generation process has been completed successfully.",
                        elf.name()
                    ));
            }

            if pctx.mpi_ctx.rank == 0 {
                tracing::info!(
                    ">>> ROM SETUP (one time only) - Generating assembly files for ELF: {}",
                    elf.name()
                );
                timer_start_info!(ROM_SETUP);
                let output_path = get_output_path(&None)?;
                generate_assembly(
                    elf.elf(),
                    &output_path,
                    with_hints,
                    self.core_prover.asm_info.verbose != VerboseMode::Info,
                )?;
                timer_stop_and_log_info!(ROM_SETUP);
                tracing::info!("<<< ROM SETUP complete - Assembly files cached for future use");
            }
            pctx.mpi_ctx.barrier();
        }

        // Sync all ranks.
        pctx.mpi_ctx.barrier();

        // ASM Services startup + pool registration
        let setup_result =
            self.start_asm_service(elf, zisk_rom, &program_vk, asm_mt_path, with_hints, &pctx);

        // Synchronize all MPI ranks and check if all succeeded.
        let all_ok = pctx.mpi_ctx.all_finished_ok(setup_result.is_ok());

        // If this rank failed, return its own error.
        setup_result?;

        // If another rank failed, return a generic error.
        if !all_ok {
            return Err(anyhow::anyhow!("Setup failed on another MPI rank"));
        }

        self.current_with_hints.store(with_hints, Ordering::SeqCst);
        self.current_emulator_only.store(false, Ordering::SeqCst);
        Ok(program_vk)
    }

    fn world_rank(&self) -> i32 {
        self.core_prover.rank_info.world_rank
    }

    fn local_rank(&self) -> i32 {
        self.core_prover.rank_info.local_rank
    }

    fn set_stdin(&self, stdin: ZiskStdin) -> Result<()> {
        self.core_prover.backend.set_stdin(stdin)
    }

    fn register_program(&self, program_id: &ProgramId, with_hints: bool) -> Result<()> {
        // Required when multiple programs have been set up: setup() activates each program's
        // services in turn, so the last setup wins. register_program restores the right services.
        // Prefer a full-ASM entry; fall back to an emulator-only entry for the same key.
        let guard = self.program_cache.read().unwrap();
        let (resources, rom, emulator_only) = {
            let full_key = SetupKey::new(&*program_id.hash_id, with_hints, false);
            let emu_key = SetupKey::new(&*program_id.hash_id, with_hints, true);
            if let Some(entry) = guard.get(&full_key) {
                (entry.resources.clone(), entry.zisk_rom.clone(), false)
            } else if let Some(entry) = guard.get(&emu_key) {
                (entry.resources.clone(), entry.zisk_rom.clone(), true)
            } else {
                return Err(anyhow::anyhow!(
                    "Program '{}' (with_hints={}) not found in cache. Call setup() first.",
                    program_id.name,
                    with_hints
                ));
            }
        };
        drop(guard);

        match resources {
            Some(r) => self.core_prover.backend.set_asm_resources(r)?,
            None => self.core_prover.backend.clear_asm_resources()?,
        }

        self.current_with_hints.store(with_hints, Ordering::SeqCst);
        self.current_emulator_only.store(emulator_only, Ordering::SeqCst);
        let pctx = self.core_prover.backend.get_pctx()?;
        let rom_bin_path = get_rom_bin_path(&pctx, program_id)?;
        self.core_prover.backend.register_program(rom, &rom_bin_path, with_hints)
    }

    fn executed_steps(&self) -> u64 {
        self.core_prover
            .backend
            .execution_result()
            .map(|(exec_result, _)| exec_result.steps)
            .unwrap_or(0)
    }

    fn execution_cost_per_type(&self) -> StatsCostPerType {
        self.core_prover
            .backend
            .execution_result()
            .map(|(exec_result, _)| exec_result.cost_per_type)
            .unwrap_or_default()
    }

    fn execution_plan(&self) -> Vec<AirInstanceCount> {
        self.core_prover
            .backend
            .execution_result()
            .map(|(exec_result, _)| exec_result.plan)
            .unwrap_or_default()
    }

    fn get_execution_info(&self) -> Result<(WitnessInfo, ZiskExecutorTime)> {
        self.core_prover.backend.get_execution_info()
    }

    fn execute(&self, program: &GuestProgram, stdin: ZiskStdin) -> Result<ExecuteOutput> {
        let with_hints = self.current_with_hints.load(Ordering::SeqCst);
        self.register_program(&program.program_id, with_hints)?;
        self.core_prover.backend.execute(stdin)
    }

    fn stats(
        &self,
        program: &GuestProgram,
        stdin: ZiskStdin,
        debug_info: Option<Option<String>>,
        minimal_memory: bool,
        mpi_node: Option<u32>,
    ) -> Result<(i32, i32, Option<ExecutorStatsHandle>)> {
        let with_hints = self.current_with_hints.load(Ordering::SeqCst);
        self.register_program(&program.program_id, with_hints)?;
        if self.current_emulator_only.load(Ordering::SeqCst) {
            return Err(anyhow::anyhow!(
                "Program '{}' was set up emulator_only — stats not supported. Re-run setup without --emulator-only.",
                program.program_id.name
            ));
        }
        self.core_prover.backend.stats(stdin, debug_info, minimal_memory, mpi_node)
    }

    fn get_instance_trace(
        &self,
        instance_id: usize,
        first_row: usize,
        num_rows: usize,
        offset: Option<usize>,
    ) -> Result<Vec<RowInfo>> {
        self.core_prover.backend.get_instance_trace(instance_id, first_row, num_rows, offset)
    }

    fn get_instance_air_values(&self, instance_id: usize) -> Result<Vec<u64>> {
        self.core_prover.backend.get_instance_air_values(instance_id)
    }

    fn get_instance_fixed(
        &self,
        instance_id: usize,
        first_row: usize,
        num_rows: usize,
        offset: Option<usize>,
    ) -> Result<Vec<RowInfo>> {
        self.core_prover.backend.get_instance_fixed(instance_id, first_row, num_rows, offset)
    }

    fn get_planning_info(&self) -> Result<PlanningInfo> {
        self.core_prover.backend.get_planning_info()
    }

    fn verify_constraints(
        &self,
        program: &GuestProgram,
        stdin: ZiskStdin,
        debug_info: Option<Option<String>>,
    ) -> Result<VerifyConstraintsOutput> {
        let with_hints = self.current_with_hints.load(Ordering::SeqCst);
        self.register_program(&program.program_id, with_hints)?;
        if self.current_emulator_only.load(Ordering::SeqCst) {
            return Err(anyhow::anyhow!(
                "Program '{}' was set up emulator_only — verify_constraints not supported. Re-run setup without --emulator-only.",
                program.program_id.name
            ));
        }
        self.core_prover.backend.verify_constraints(stdin, debug_info)
    }

    fn get_debug_info(
        &self,
        program: &GuestProgram,
        stdin: ZiskStdin,
        debug_info: Option<Option<String>>,
    ) -> Result<DebugReport> {
        let with_hints = self.current_with_hints.load(Ordering::SeqCst);
        self.register_program(&program.program_id, with_hints)?;
        if self.current_emulator_only.load(Ordering::SeqCst) {
            return Err(anyhow::anyhow!(
                "Program '{}' was set up emulator_only — get_debug_info not supported. Re-run setup without --emulator-only.",
                program.program_id.name
            ));
        }
        self.core_prover.backend.get_debug_info(stdin, debug_info)
    }

    fn prove(
        &self,
        program: &GuestProgram,
        stdin: ZiskStdin,
        proof_kind: ProofKind,
        prover_options: BackendProverOpts,
    ) -> Result<ProveOutput> {
        let with_hints = self.current_with_hints.load(Ordering::SeqCst);
        self.register_program(&program.program_id, with_hints)?;
        if self.current_emulator_only.load(Ordering::SeqCst) {
            return Err(anyhow::anyhow!(
                "Program '{}' was set up emulator_only — prove not supported. Re-run setup without --emulator-only.",
                program.program_id.name
            ));
        }
        self.core_prover.backend.prove(stdin, proof_kind, prover_options)
    }

    fn wrap_proof(
        &self,
        proof: &[u64],
        publics: &PublicValues,
        vk: &ProgramVK,
        proof_kind: ProofKind,
    ) -> Result<ProveOutput> {
        match proof_kind {
            ProofKind::VadcopFinalMinimal => self.core_prover.backend.minimal(proof, publics, vk),
            ProofKind::Plonk => self.core_prover.backend.plonk(proof, publics, vk),
            _ => Err(anyhow::anyhow!("Unsupported proof mode for wrap: {:?}", proof_kind)),
        }
    }

    fn prove_phase(
        &self,
        phase_inputs: ProvePhaseInputs,
        options: ProofOptions,
        phase: ProvePhase,
    ) -> Result<ZiskPhaseResult> {
        self.core_prover.backend.prove_phase(phase_inputs, options, phase)
    }

    fn set_partition(
        &self,
        total_compute_units: usize,
        allocation: Vec<u32>,
        rank_id: usize,
    ) -> Result<()> {
        self.core_prover.backend.set_partition(total_compute_units, allocation, rank_id)
    }

    fn register_aggregated_proofs(&self, agg_proofs: Vec<AggProofsRegister>) -> Result<()> {
        self.core_prover.backend.register_aggregated_proofs(agg_proofs)
    }

    fn aggregate_proofs(
        &self,
        agg_proofs: Vec<AggProofs>,
        last_proof: bool,
        final_proof: bool,
        options: &ProofOptions,
    ) -> Result<Option<ZiskAggPhaseResult>> {
        self.core_prover.backend.aggregate_proofs(agg_proofs, last_proof, final_proof, options)
    }

    fn mpi_broadcast(&self, data: &mut Vec<u8>) -> Result<()> {
        self.core_prover.backend.mpi_broadcast(data)
    }

    fn notify_cluster_cancellation(&self) {
        self.core_prover.backend.notify_cluster_cancellation();
    }

    fn cluster_barrier(&self) {
        self.core_prover.backend.cluster_barrier();
    }

    fn get_vadcop_vk(&self, minimal: bool) -> Result<Vec<u64>> {
        self.core_prover.backend.get_vadcop_vk(minimal)
    }

    fn submit_hint(&self, bytes: &[u8]) -> Result<()> {
        self.core_prover.backend.submit_hint(bytes)
    }

    fn submit_input(&self, bytes: &[u8]) -> Result<()> {
        self.core_prover.backend.submit_input(bytes)
    }

    fn append_raw_input(&self, bytes: &[u8]) -> Result<()> {
        self.core_prover.backend.append_raw_input(bytes)
    }

    fn register_hints_stream(&self, stream: StreamSource) -> Result<()> {
        self.core_prover.backend.register_hints_stream(stream)
    }

    fn register_inputs_stream(&self, stream: StreamSource) -> Result<()> {
        self.core_prover.backend.register_inputs_stream(stream)
    }

    fn get_hints_processor(&self) -> Result<Arc<HintsProcessor<HintsShmem>>> {
        if self.current_with_hints.load(Ordering::SeqCst) {
            self.core_prover.backend.get_hints_processor()
        } else {
            Err(anyhow::anyhow!("Current program was not set up with hints"))
        }
    }

    fn set_active_services(&self, is_first_process: bool) -> Result<()> {
        self.core_prover.backend.set_active_services(is_first_process)
    }

    fn reset(&self) -> Result<()> {
        self.core_prover.backend.reset()
    }

    fn cancel(&self) -> Result<()> {
        // Order matters: set proofman's cancel flag first so when the executor
        // unwinds (after the ASM children wake), proofman already knows to bail.
        self.core_prover.backend.cancel();
        self.core_prover.backend.signal_cancellation()
    }

    fn wait_until_proofman_ready(&self) {
        self.core_prover.backend.wait_until_proofman_ready();
    }
}

pub struct AsmInfo {
    pub is_distributed: bool,
    pub unlock_mapped_memory: bool,
    pub asm_out_file: bool,
    pub verbose: VerboseMode,
    pub no_auto_setup: bool,
    pub n_setups: AtomicU64,
    pub cpu_mops: bool,
}

pub struct AsmCoreProver {
    backend: ProverBackend,
    rank_info: RankInfo,
    asm_info: AsmInfo,
}

impl AsmCoreProver {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        use_snark_wrapper: bool,
        preload_snark: bool,
        proving_key: PathBuf,
        proving_key_snark: PathBuf,
        shared_tables: bool,
        unlock_mapped_memory: bool,
        asm_out_file: bool,
        no_auto_setup: bool,
        options: ProofmanOptions,
        is_distributed: bool,
        logging_config: Option<LoggingConfig>,
        cpu_mops: bool,
    ) -> Result<Self> {
        check_paths_exist(&proving_key)?;
        let proofman = ProofMan::new(proving_key.clone(), options.clone())
            .map_err(|e| anyhow::anyhow!(e.to_string()))?;

        let rank_info = proofman.get_rank_info();

        if logging_config.is_some() {
            zisk_cluster_common::init(logging_config.as_ref(), Some(&rank_info))?;
        } else {
            initialize_logger(options.verbose_mode, Some(&rank_info));
        }

        proofman.set_barrier();

        let mut snark_wrapper = None;
        if use_snark_wrapper {
            check_paths_exist(&proving_key_snark)?;
            let (aux_trace, d_buffers, reload_fixed_pols_gpu) = proofman.get_preallocated_buffers();
            snark_wrapper = Some(SnarkWrapper::new_with_preallocated_buffers(
                &proving_key_snark,
                options.verbose_mode,
                Some(aux_trace),
                Some(d_buffers),
                Some(reload_fixed_pols_gpu),
                preload_snark,
                options.gpu,
            )?);
        }

        let executor = ZiskExecutor::new(
            &proofman.get_wcm(),
            options.verbose_mode,
            shared_tables,
            true,
            options.packed,
        )?;

        let core = ProverBackend::new(
            proofman,
            snark_wrapper,
            executor,
            proving_key,
            Some(proving_key_snark),
        );

        Ok(Self {
            backend: core,
            rank_info,
            asm_info: AsmInfo {
                is_distributed,
                unlock_mapped_memory,
                asm_out_file,
                verbose: options.verbose_mode,
                no_auto_setup,
                n_setups: AtomicU64::new(0),
                cpu_mops,
            },
        })
    }
}

impl ExecuteClient for ZiskProver<Asm> {
    fn setup(&self, program: &GuestProgram, with_hints: bool) -> Result<()> {
        let builder = ZiskProver::<Asm>::setup(self, program);
        let builder = if with_hints { builder.with_hints() } else { builder };
        builder.run().map(|_| ())
    }

    fn execute(
        &self,
        program: &GuestProgram,
        stdin: ZiskStdin,
        hints: Option<StreamSource>,
    ) -> Result<ExecuteOutput> {
        if let Some(stream) = hints {
            ZiskProver::<Asm>::register_hints_stream(self, stream)?;
        }
        ZiskProver::<Asm>::execute(self, program, stdin)
    }
}
