use crate::{
    check_paths_exist, ensure_program_vk, get_asm_paths, get_rom_bin_path,
    guest::ProgramId,
    prover::{ProverBackend, ProverEngine, ZiskBackend},
    BackendProverOpts, ExecuteOutput, GuestProgram, ProveOutput, VerifyConstraintsOutput,
    ZiskAggPhaseResult, ZiskPhaseResult,
};
use asm_runner::{AsmRunnerOptions, AsmServices, HintsShmem};
use executor::{initialize_executor, AsmResources, AsmSharedResources};
use precompiles_hints::HintsProcessor;
use proofman::{
    AggProofs, AggProofsRegister, ProofMan, ProvePhase, ProvePhaseInputs, SnarkWrapper, WitnessInfo,
};
use proofman_common::{
    initialize_logger, ProofCtx, ProofOptions, ProofmanOptions, RankInfo, RowInfo, VerboseMode,
};
use proofman_starks_lib_c::{get_unified_buffer_gpu_c, get_unified_buffer_gpu_size_c};
use proofman_util::{timer_start_info, timer_stop_and_log_info};
use rom_setup::{generate_assembly, get_output_path, DEFAULT_CACHE_PATH};
use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::{
    atomic::{AtomicBool, AtomicU64, Ordering},
    {Arc, RwLock},
};
use zisk_cluster_common::LoggingConfig;
use zisk_common::{
    io::{StreamSource, ZiskStdin},
    ExecutorStatsHandle, ProgramVK, ProofKind, PublicValues, SetupKey, ZiskExecutorTime, ZiskVK,
};
use zisk_core::{Riscv2zisk, ZiskRom};

use anyhow::Result;

pub struct Asm;

impl ZiskBackend for Asm {
    type Prover = AsmProver;
}

/// Builder for ASM backend setup with optional hints support.
pub struct AsmSetupBuilder<'a> {
    prover: &'a AsmProver,
    elf: &'a GuestProgram,
    with_hints: bool,
}

impl<'a> AsmSetupBuilder<'a> {
    fn new(prover: &'a AsmProver, elf: &'a GuestProgram) -> Self {
        Self { prover, elf, with_hints: false }
    }

    /// Enable hints processing for this program.
    ///
    /// When hints are enabled, the ASM backend will process hints generated by the guest program.
    pub fn with_hints(mut self) -> Self {
        self.with_hints = true;
        self
    }

    pub fn run(self) -> Result<ProgramVK> {
        self.prover.setup_internal(self.elf, self.with_hints)
    }
}

struct ProgramEntry {
    zisk_rom: Arc<ZiskRom>,
    program_vk: ProgramVK,
    /// Keeps ASM resources (C processes + shmem) alive for the full worker lifetime.
    resources: Arc<AsmResources>,
}

pub struct AsmProver {
    core_prover: AsmCoreProver,
    program_cache: RwLock<HashMap<SetupKey, ProgramEntry>>,
    /// Tracks whether the currently registered program was set up with hints.
    current_with_hints: AtomicBool,
}

impl AsmProver {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        snark_wrapper: bool,
        preload_snark: bool,
        proving_key: PathBuf,
        proving_key_snark: PathBuf,
        shared_tables: bool,
        unlock_mapped_memory: bool,
        asm_out_file: bool,
        no_auto_setup: bool,
        options: ProofmanOptions,
        is_distributed: bool,
        logging_config: Option<LoggingConfig>,
    ) -> Result<Self> {
        AsmServices::cleanup_stale_shmem();
        let core_prover = AsmCoreProver::new(
            snark_wrapper,
            preload_snark,
            proving_key,
            proving_key_snark,
            shared_tables,
            unlock_mapped_memory,
            asm_out_file,
            no_auto_setup,
            options,
            is_distributed,
            logging_config,
        )?;
        Ok(Self {
            core_prover,
            program_cache: RwLock::new(HashMap::new()),
            current_with_hints: AtomicBool::new(false),
        })
    }

    fn get_asm_cache_paths(
        elf: &GuestProgram,
        with_hints: bool,
    ) -> Result<(PathBuf, PathBuf), anyhow::Error> {
        let default_cache_path = std::env::var("HOME")
            .map(PathBuf::from)
            .map_err(|e| anyhow::anyhow!("Failed to read HOME environment variable: {e}"))?
            .join(DEFAULT_CACHE_PATH);
        let (asm_mt_filename, asm_rh_filename) = get_asm_paths(elf, with_hints)?;
        let asm_mt_path = default_cache_path.join(asm_mt_filename);
        let asm_rh_path = default_cache_path.join(asm_rh_filename);

        Ok((asm_mt_path, asm_rh_path))
    }

    fn start_asm_service(
        &self,
        elf: &GuestProgram,
        zisk_rom: Arc<ZiskRom>,
        program_vk: &ProgramVK,
        asm_mt_path: PathBuf,
        with_hints: bool,
        pctx: &Arc<ProofCtx<fields::Goldilocks>>,
    ) -> std::result::Result<(), anyhow::Error> {
        let world_rank = self.core_prover.rank_info.world_rank;
        let local_rank = self.core_prover.rank_info.local_rank;
        let n_processes = self.core_prover.rank_info.n_processes;
        let is_distributed = self.core_prover.asm_info.is_distributed;
        let unlock_mapped_memory = self.core_prover.asm_info.unlock_mapped_memory;
        let asm_out_file = self.core_prover.asm_info.asm_out_file;
        let verbose_mode = self.core_prover.asm_info.verbose;

        timer_start_info!(STARTING_ASM_MICROSERVICES);

        let asm_runner_options = AsmRunnerOptions::new()
            .with_local_rank(local_rank)
            .with_verbose(verbose_mode == VerboseMode::Debug)
            .with_metrics(verbose_mode == VerboseMode::Debug)
            .with_unlock_mapped_memory(unlock_mapped_memory)
            .with_asm_out_file(asm_out_file);

        let mpi_broadcast_fn = (is_distributed && n_processes > 1 && with_hints).then(|| {
            let pctx = pctx.clone();
            Arc::new(move |data: &mut Vec<u8>| {
                pctx.mpi_ctx.broadcast(data);
                Ok(())
            }) as Arc<dyn Fn(&mut Vec<u8>) -> Result<()> + Send + Sync>
        });

        let init_rom = !is_distributed && world_rank == 0;

        if let Some(entry) = self
            .program_cache
            .read()
            .unwrap()
            .get(&SetupKey::new(&*elf.program_id.hash_id, with_hints))
        {
            timer_stop_and_log_info!(STARTING_ASM_MICROSERVICES);
            self.core_prover.backend.set_asm_resources(entry.resources.clone())?;
            return Ok(());
        }

        // Each program has its own shm_prefix (includes program hash), so each needs
        // its own shmem creation + AsmSharedResources. Previous programs' resources
        // stay alive in the pool via Arc.
        let asm_services = AsmServices::new(
            world_rank,
            local_rank,
            elf.program_id.hash_id.as_ref().to_string(),
            &asm_mt_path,
            with_hints,
            asm_runner_options,
        )?;

        // Borrow proofman's already-allocated unified GPU buffer. 
        // Zero values when CUDA is unavailable; downstream consumers no-op on (0, 0).
        let device_buffers_ptr = pctx.get_device_buffers_ptr();
        let gpu_buf_ptr = get_unified_buffer_gpu_c(device_buffers_ptr) as usize;
        let gpu_buf_size = get_unified_buffer_gpu_size_c(device_buffers_ptr);

        let shared = Arc::new(AsmSharedResources::new(
            world_rank,
            local_rank,
            unlock_mapped_memory,
            verbose_mode,
            mpi_broadcast_fn,
            init_rom,
            with_hints,
            asm_services.shm_prefix(),
            gpu_buf_ptr,
            gpu_buf_size,
        )?);
        timer_stop_and_log_info!(STARTING_ASM_MICROSERVICES);

        let resources = Arc::new(AsmResources::new(shared, asm_services)?);
        self.core_prover.backend.set_asm_resources(resources.clone())?;
        self.core_prover.asm_info.n_setups.fetch_add(1, Ordering::SeqCst);
        self.program_cache.write().unwrap().insert(
            SetupKey::new(&*elf.program_id.hash_id, with_hints),
            ProgramEntry { zisk_rom, resources, program_vk: program_vk.clone() },
        );

        Ok(())
    }
}

impl ProverEngine for AsmProver {
    type Builder<'a> = AsmSetupBuilder<'a>;

    fn setup<'a>(&'a self, elf: &'a GuestProgram) -> Self::Builder<'a> {
        AsmSetupBuilder::new(self, elf)
    }

    fn setup_internal(&self, elf: &GuestProgram, with_hints: bool) -> Result<ProgramVK> {
        // Early return if program is already cached.
        if let Some(entry) = self
            .program_cache
            .read()
            .unwrap()
            .get(&SetupKey::new(&*elf.program_id.hash_id, with_hints))
        {
            self.current_with_hints.store(with_hints, Ordering::SeqCst);
            return Ok(entry.program_vk.clone());
        }

        let pctx = self.core_prover.backend.get_pctx()?;

        // Computes the verification key (VK) for an ELF: loads it from cache if present.
        let program_vk = ensure_program_vk(&pctx, elf)?;

        // Generate Zisk ROM from ELF
        let rv2zk = Riscv2zisk::new(elf.elf());
        let zisk_rom = rv2zk.run().map_err(|e| anyhow::anyhow!(e.to_string()))?;
        let zisk_rom = Arc::new(zisk_rom);

        // Assembly file generation
        let (asm_mt_path, asm_rh_path) = Self::get_asm_cache_paths(elf, with_hints)?;

        let asm_mt_path_exists = check_paths_exist(&asm_mt_path).is_ok();
        let asm_rh_path_exists = check_paths_exist(&asm_rh_path).is_ok();

        if !asm_mt_path_exists || !asm_rh_path_exists {
            if self.core_prover.asm_info.no_auto_setup {
                return Err(anyhow::anyhow!(
                        "Assembly files not found for ELF {}. Force ROM setup is enabled, but assembly files are still missing. Please ensure that the assembly generation process has been completed successfully.",
                        elf.name()
                    ));
            }

            if pctx.mpi_ctx.rank == 0 {
                tracing::info!(
                    ">>> ROM SETUP (one time only) - Generating assembly files for ELF: {}",
                    elf.name()
                );
                timer_start_info!(ROM_SETUP);
                let output_path = get_output_path(&None)?;
                generate_assembly(
                    elf.elf(),
                    elf.name(),
                    &output_path,
                    with_hints,
                    self.core_prover.asm_info.verbose != VerboseMode::Info,
                )?;
                timer_stop_and_log_info!(ROM_SETUP);
                tracing::info!("<<< ROM SETUP complete - Assembly files cached for future use");
            }
            pctx.mpi_ctx.barrier();
        }

        // Sync all ranks.
        pctx.mpi_ctx.barrier();

        // ASM Services startup + pool registration
        let setup_result =
            self.start_asm_service(elf, zisk_rom, &program_vk, asm_mt_path, with_hints, &pctx);

        // Synchronize all MPI ranks and check if all succeeded.
        let all_ok = pctx.mpi_ctx.all_finished_ok(setup_result.is_ok());

        // If this rank failed, return its own error.
        setup_result?;

        // If another rank failed, return a generic error.
        if !all_ok {
            return Err(anyhow::anyhow!("Setup failed on another MPI rank"));
        }

        self.current_with_hints.store(with_hints, Ordering::SeqCst);
        Ok(program_vk)
    }

    fn world_rank(&self) -> i32 {
        self.core_prover.rank_info.world_rank
    }

    fn local_rank(&self) -> i32 {
        self.core_prover.rank_info.local_rank
    }

    fn set_stdin(&self, stdin: ZiskStdin) -> Result<()> {
        self.core_prover.backend.set_stdin(stdin)
    }

    fn register_program(&self, program_id: &ProgramId, with_hints: bool) -> Result<()> {
        // Required when multiple programs have been set up: setup() activates each program's
        // services in turn, so the last setup wins. register_program restores the right services.
        let guard = self.program_cache.read().unwrap();
        let entry =
            guard.get(&SetupKey::new(&*program_id.hash_id, with_hints)).ok_or_else(|| {
                anyhow::anyhow!(
                    "Program '{}' (with_hints={}) not found in cache. Call setup() first.",
                    program_id.name,
                    with_hints
                )
            })?;
        self.core_prover.backend.set_asm_resources(entry.resources.clone())?;
        let rom = entry.zisk_rom.clone();
        drop(guard);

        self.current_with_hints.store(with_hints, Ordering::SeqCst);
        let pctx = self.core_prover.backend.get_pctx()?;
        let rom_bin_path = get_rom_bin_path(&pctx, program_id)?;
        self.core_prover.backend.register_program(rom, &rom_bin_path, with_hints)
    }

    fn executed_steps(&self) -> u64 {
        self.core_prover
            .backend
            .execution_result()
            .map(|(exec_result, _)| exec_result.steps)
            .unwrap_or(0)
    }

    fn get_execution_info(&self) -> Result<(WitnessInfo, ZiskExecutorTime)> {
        self.core_prover.backend.get_execution_info()
    }

    fn execute(&self, program: &GuestProgram, stdin: ZiskStdin) -> Result<ExecuteOutput> {
        let with_hints = self.current_with_hints.load(Ordering::SeqCst);
        self.register_program(&program.program_id, with_hints)?;
        self.core_prover.backend.execute(stdin)
    }

    fn stats(
        &self,
        program: &GuestProgram,
        stdin: ZiskStdin,
        debug_info: Option<Option<String>>,
        minimal_memory: bool,
        mpi_node: Option<u32>,
    ) -> Result<(i32, i32, Option<ExecutorStatsHandle>)> {
        let with_hints = self.current_with_hints.load(Ordering::SeqCst);
        self.register_program(&program.program_id, with_hints)?;
        self.core_prover.backend.stats(stdin, debug_info, minimal_memory, mpi_node)
    }

    fn get_instance_trace(
        &self,
        instance_id: usize,
        first_row: usize,
        num_rows: usize,
        offset: Option<usize>,
    ) -> Result<Vec<RowInfo>> {
        self.core_prover.backend.get_instance_trace(instance_id, first_row, num_rows, offset)
    }

    fn get_instance_air_values(&self, instance_id: usize) -> Result<Vec<u64>> {
        self.core_prover.backend.get_instance_air_values(instance_id)
    }

    fn get_instance_fixed(
        &self,
        instance_id: usize,
        first_row: usize,
        num_rows: usize,
        offset: Option<usize>,
    ) -> Result<Vec<RowInfo>> {
        self.core_prover.backend.get_instance_fixed(instance_id, first_row, num_rows, offset)
    }

    fn verify_constraints(
        &self,
        program: &GuestProgram,
        stdin: ZiskStdin,
        debug_info: Option<Option<String>>,
    ) -> Result<VerifyConstraintsOutput> {
        let with_hints = self.current_with_hints.load(Ordering::SeqCst);
        self.register_program(&program.program_id, with_hints)?;
        self.core_prover.backend.verify_constraints(stdin, debug_info)
    }

    fn prove(
        &self,
        program: &GuestProgram,
        stdin: ZiskStdin,
        proof_kind: ProofKind,
        prover_options: BackendProverOpts,
    ) -> Result<ProveOutput> {
        let with_hints = self.current_with_hints.load(Ordering::SeqCst);
        self.register_program(&program.program_id, with_hints)?;
        self.core_prover.backend.prove(stdin, proof_kind, prover_options)
    }

    fn wrap_proof(
        &self,
        proof_bytes: &[u8],
        publics: &PublicValues,
        vk: &ProgramVK,
        proof_kind: ProofKind,
    ) -> Result<ProveOutput> {
        match proof_kind {
            ProofKind::VadcopFinalMinimal => {
                self.core_prover.backend.minimal(proof_bytes, publics, vk)
            }
            ProofKind::Plonk => self.core_prover.backend.plonk(proof_bytes, publics, vk),
            _ => Err(anyhow::anyhow!("Unsupported proof mode for wrap: {:?}", proof_kind)),
        }
    }

    fn prove_phase(
        &self,
        phase_inputs: ProvePhaseInputs,
        options: ProofOptions,
        phase: ProvePhase,
    ) -> Result<ZiskPhaseResult> {
        self.core_prover.backend.prove_phase(phase_inputs, options, phase)
    }

    fn set_partition(
        &self,
        total_compute_units: usize,
        allocation: Vec<u32>,
        rank_id: usize,
    ) -> Result<()> {
        self.core_prover.backend.set_partition(total_compute_units, allocation, rank_id)
    }

    fn register_aggregated_proofs(&self, agg_proofs: Vec<AggProofsRegister>) -> Result<()> {
        self.core_prover.backend.register_aggregated_proofs(agg_proofs)
    }

    fn aggregate_proofs(
        &self,
        agg_proofs: Vec<AggProofs>,
        last_proof: bool,
        final_proof: bool,
        options: &ProofOptions,
    ) -> Result<Option<ZiskAggPhaseResult>> {
        self.core_prover.backend.aggregate_proofs(agg_proofs, last_proof, final_proof, options)
    }

    fn mpi_broadcast(&self, data: &mut Vec<u8>) -> Result<()> {
        self.core_prover.backend.mpi_broadcast(data)
    }

    fn get_vadcop_vk(&self, minimal: bool) -> Result<ZiskVK> {
        self.core_prover.backend.get_vadcop_vk(minimal)
    }

    fn submit_hint(&self, bytes: &[u8]) -> Result<()> {
        self.core_prover.backend.submit_hint(bytes)
    }

    fn submit_input(&self, bytes: &[u8]) -> Result<()> {
        self.core_prover.backend.submit_input(bytes)
    }

    fn append_raw_input(&self, bytes: &[u8]) -> Result<()> {
        self.core_prover.backend.append_raw_input(bytes)
    }

    fn register_hints_stream(&self, stream: StreamSource) -> Result<()> {
        self.core_prover.backend.register_hints_stream(stream)
    }

    fn register_inputs_stream(&self, stream: StreamSource) -> Result<()> {
        self.core_prover.backend.register_inputs_stream(stream)
    }

    fn get_hints_processor(&self) -> Result<Arc<HintsProcessor<HintsShmem>>> {
        if self.current_with_hints.load(Ordering::SeqCst) {
            self.core_prover.backend.get_hints_processor()
        } else {
            Err(anyhow::anyhow!("Current program was not set up with hints"))
        }
    }

    fn set_active_services(&self, is_first_partition: bool) -> Result<()> {
        self.core_prover.backend.set_active_services(is_first_partition)
    }

    fn reset_resources(&self) -> Result<()> {
        self.core_prover.backend.reset_resources()
    }

    fn restart_asm_resources(&self, elf: &GuestProgram, with_hints: bool) -> Result<()> {
        let key = SetupKey::new(&*elf.program_id.hash_id, with_hints);
        let world_rank = self.core_prover.rank_info.world_rank;

        tracing::warn!(
            ">>> [{world_rank}] Soft-resetting ASM children for program {} (with_hints={with_hints})",
            elf.name(),
        );

        let resources = {
            let cache = self.program_cache.read().unwrap();
            cache
                .get(&key)
                .ok_or_else(|| {
                    anyhow::anyhow!(
                        "restart_asm_resources: program '{}' (with_hints={with_hints}) not in cache",
                        elf.name()
                    )
                })?
                .resources
                .clone()
        };

        self.core_prover.backend.cancel();
        resources.signal_children_reset()?;

        tracing::info!(">>> [{world_rank}] Soft-reset signal sent for program {}", elf.name());
        Ok(())
    }

    fn cancel(&self) {
        self.core_prover.backend.cancel();
    }
}

pub struct AsmInfo {
    pub is_distributed: bool,
    pub unlock_mapped_memory: bool,
    pub asm_out_file: bool,
    pub verbose: VerboseMode,
    pub no_auto_setup: bool,
    pub n_setups: AtomicU64,
}

pub struct AsmCoreProver {
    backend: ProverBackend,
    rank_info: RankInfo,
    asm_info: AsmInfo,
}

impl AsmCoreProver {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        use_snark_wrapper: bool,
        preload_snark: bool,
        proving_key: PathBuf,
        proving_key_snark: PathBuf,
        shared_tables: bool,
        unlock_mapped_memory: bool,
        asm_out_file: bool,
        no_auto_setup: bool,
        options: ProofmanOptions,
        is_distributed: bool,
        logging_config: Option<LoggingConfig>,
    ) -> Result<Self> {
        check_paths_exist(&proving_key)?;
        let proofman = ProofMan::new(proving_key.clone(), options.clone())
            .map_err(|e| anyhow::anyhow!(e.to_string()))?;

        let rank_info = proofman.get_rank_info();

        if logging_config.is_some() {
            zisk_cluster_common::init(logging_config.as_ref(), Some(&rank_info))?;
        } else {
            initialize_logger(options.verbose_mode, Some(&rank_info));
        }

        proofman.set_barrier();

        let mut snark_wrapper = None;
        if use_snark_wrapper {
            check_paths_exist(&proving_key_snark)?;
            let (aux_trace, d_buffers, reload_fixed_pols_gpu) = proofman.get_preallocated_buffers();
            snark_wrapper = Some(SnarkWrapper::new_with_preallocated_buffers(
                &proving_key_snark,
                options.verbose_mode,
                Some(aux_trace),
                Some(d_buffers),
                Some(reload_fixed_pols_gpu),
                preload_snark,
                options.gpu,
            )?);
        }

        let executor =
            initialize_executor(options.verbose_mode, shared_tables, true, &proofman.get_wcm())?;

        executor.set_packed(options.packed);

        let core = ProverBackend::new(
            proofman,
            snark_wrapper,
            executor,
            proving_key,
            Some(proving_key_snark),
        );

        Ok(Self {
            backend: core,
            rank_info,
            asm_info: AsmInfo {
                is_distributed,
                unlock_mapped_memory,
                asm_out_file,
                verbose: options.verbose_mode,
                no_auto_setup,
                n_setups: AtomicU64::new(0),
            },
        })
    }
}
