[package]
name = "mem-planner-cpp"
version.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
repository.workspace = true
categories.workspace = true

build = "build.rs"

[dependencies]
zisk-common = { path = "../../common" }
mem-common = { path = "../mem-common" }
zisk-pil = { path = "../../pil" }
proofman-common = { workspace = true }
proofman-util = { workspace = true }
tracing = { workspace = true }

[features]
default = []
save_mem_bus_data = []
