//! [`Ir`] -> Lean 4 definitions.
//!
//! The output is deliberately independent of Mathlib, because the Lean the
//! Sail model generates is too: `sail/build/lean/out` has no dependencies at
//! all. What the constraints need is the arithmetic of a field and nothing
//! else, so the emitted prelude declares exactly that as a class and every
//! definition stays polymorphic in it.

use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;

use crate::ir::{Ir, Kind, Operand, Slot};
use crate::print::{self, Leaves, Plan, MAX_INLINE};

/// The field interface the generated constraints are stated over. Static: it
/// says nothing about any particular pilout.
pub const PRELUDE: &str = r#"/-
  The field PIL constraints generated by `pilout-constraints` are stated over.

  A pil2 constraint is a polynomial identity, so the structure it needs is that
  of a commutative ring: addition, subtraction, multiplication, negation and
  numerals, with the usual laws. Lean's core provides exactly that as
  `Lean.Grind.CommRing`, and `grind` knows how to reason with it — so the
  generated AIRs need no Mathlib, and neither does a proof about them.

  The ring is left abstract on purpose. A pil2 constraint is evaluated over the
  cubic extension, where the stage-2 columns and the challenges live, while
  stage-1 columns and constants are base field elements embedded in it. Stated
  over any commutative ring, one definition covers both.

  Two consequences worth knowing before proving anything:

  - Facts that hold only in a field — that a nonzero element is invertible, or
    that 2 is not zero — are not available here. A proof needing one
    instantiates `F` at the concrete field, whose characteristic each generated
    AIR records as `basePrime`.
  - The booleanity of a `bits(1)` column is not a constraint at all. It comes
    from a range-check lookup, which lives in the pilout's hints rather than in
    the AIR, and is not extracted.
-/

/-- The ring a PIL constraint is evaluated in. -/
abbrev PilField (F : Type) := Lean.Grind.CommRing F
"#;

/// Renders one AIR. `module` is the import path of the prelude, e.g. `Pil`.
pub fn render(ir: &Ir, module: &str) -> String {
    let plan = Plan::build(ir, MAX_INLINE);
    let names = Names::build(ir, &plan);
    let leaves =
        LeanLeaves { names: &names, base_field: ir.pilout.base_field.parse::<u128>().ok() };

    let mut out = String::new();
    header(&mut out, ir, module);
    structures(&mut out, &names);
    definitions(&mut out, ir, &plan, &names, &leaves);
    constraints(&mut out, ir, &plan, &names, &leaves);
    aggregate(&mut out, ir, &names);
    let _ = writeln!(out, "end {}", namespace(ir));
    out
}

fn namespace(ir: &Ir) -> String {
    format!("Pil.{}.{}", ident(&ir.air.airgroup), ident(&ir.air.air))
}

fn header(out: &mut String, ir: &Ir, module: &str) {
    let air = &ir.air;
    let counts = kind_counts(ir);
    let _ = write!(
        out,
        r#"/-
  {airgroup}/{air} — {n} constraints, generated from a pilout.

  DO NOT EDIT. Regenerate with:
    pilout-constraints lean --pilout <file>.pilout --air {air}

  pilout      {file}
  blake3      {hash}
  base field  {field}
  rows        {rows}
  stages      {widths:?} (committed width per stage, stage 1 first)
  constraints {counts}

  Row offsets wrap around the trace, so a row index here is an integer and the
  trace is asserted to be periodic (`cyclic`) rather than indexed by `Fin`.
  That keeps `t (i - 1)` a subtraction instead of a proof obligation.
-/
import {module}.Prelude

-- A generated definition ignores the row argument when a constraint only
-- relates air values, and both the terms and the structures are wide: Keccakf
-- commits 453 columns and Main carries 756 air values, and a structure that
-- size exceeds the default heartbeat limit while elaborating. Sail's own Lean
-- output raises the same three options.
set_option linter.unusedVariables false
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

namespace {ns}

"#,
        airgroup = air.airgroup,
        air = air.air,
        n = ir.constraints.len(),
        file = ir.pilout.file,
        hash = ir.pilout.blake3,
        field = ir.pilout.base_field,
        rows = air.num_rows,
        widths = air.stage_widths,
        counts = counts,
        module = module,
        ns = namespace(ir),
    );

    let _ = write!(
        out,
        "/-- Base field characteristic of the pilout this came from. -/\ndef basePrime : Nat := {}\n\n\
         /-- Row count of this AIR, from the pilout. -/\ndef numRows : Nat := {}\n\n",
        ir.pilout.base_field, ir.air.num_rows
    );
}

fn kind_counts(ir: &Ir) -> String {
    let mut every = 0;
    let mut first = 0;
    let mut last = 0;
    let mut frame = 0;
    for c in &ir.constraints {
        match c.kind {
            Kind::EveryRow => every += 1,
            Kind::FirstRow => first += 1,
            Kind::LastRow => last += 1,
            Kind::EveryFrame { .. } => frame += 1,
        }
    }
    let mut parts = Vec::new();
    for (n, label) in
        [(every, "every row"), (first, "first row"), (last, "last row"), (frame, "every frame")]
    {
        if n > 0 {
            parts.push(format!("{n} {label}"));
        }
    }
    parts.join(", ")
}

/// `Row` holds everything that varies per row, `Ctx` everything that does not.
fn structures(out: &mut String, names: &Names) {
    let _ = writeln!(
        out,
        "/-- Every column of one row: the committed columns of each stage, plus the\n\
         fixed and periodic columns the AIR reads. One field per PIL symbol, so a\n\
         PIL array is a function of its indices — `a[2][0]` is `(t i).a 2 0`. -/\n\
         structure Row (F : Type) where"
    );
    for (declaration, comment) in &names.row_fields {
        let _ = writeln!(out, "  {declaration}{comment}");
    }
    let _ = writeln!(out);

    let _ = writeln!(
        out,
        "/-- What the AIR holds constant down the trace: air values, challenges,\n\
         publics, proof values and airgroup values. -/\nstructure Ctx (F : Type) where"
    );
    if names.ctx_fields.is_empty() {
        let _ = writeln!(out, "  -- this AIR references none");
    }
    for (declaration, comment) in &names.ctx_fields {
        let _ = writeln!(out, "  {declaration}{comment}");
    }

    let _ = write!(
        out,
        "\n/-- A trace: one row per index. -/\nabbrev Trace (F : Type) := Int → Row F\n\n\
         variable {{F : Type}} [PilField F]\n\n\
         /-- The trace repeats with the AIR's row count, which is what makes a row\n\
         offset past either end well defined. -/\n\
         def cyclic (t : Trace F) : Prop := ∀ i : Int, t (i + (numRows : Int)) = t i\n\n"
    );
}

fn definitions(out: &mut String, ir: &Ir, plan: &Plan, names: &Names, leaves: &LeanLeaves) {
    let shared: Vec<u32> = plan.definitions().collect();
    if shared.is_empty() {
        return;
    }
    let _ = writeln!(
        out,
        "/-! ### Shared subexpressions\n\n\
         One definition per expression the pilout shares between constraints, plus\n\
         the intermediates the PIL itself named. Everything used once is inlined. -/\n"
    );
    for idx in shared {
        if let Some(pil) = plan.named.get(&idx) {
            let _ = writeln!(out, "/-- `{pil}` — named intermediate, pilout expression {idx}. -/");
        } else {
            let _ = writeln!(out, "/-- Pilout expression {idx}. -/");
        }
        let body = print::render(ir, plan, leaves, idx);
        let _ = writeln!(
            out,
            "def {} (x : Ctx F) (t : Trace F) (i : Int) : F :=\n  {}\n",
            names.expr[&idx], body
        );
    }
}

fn constraints(out: &mut String, ir: &Ir, plan: &Plan, names: &Names, leaves: &LeanLeaves) {
    let _ = writeln!(
        out,
        "/-! ### Constraints\n\n\
         One definition per constraint of the AIR, in pilout order, each stating\n\
         that the constraint's expression vanishes. -/\n"
    );
    for c in &ir.constraints {
        let location = c.source.as_ref().and_then(|s| s.location());
        let text = c.source.as_ref().map(|s| s.text.as_str());
        match (location, text) {
            (Some(loc), Some(text)) => {
                let _ =
                    writeln!(out, "/-- `{loc}` — `{text}` -/", loc = loc, text = escape_doc(text));
            }
            (None, Some(text)) => {
                let _ = writeln!(out, "/-- `{}` -/", escape_doc(text));
            }
            _ => {
                let _ = writeln!(out, "/-- Constraint {} of the AIR. -/", c.idx);
            }
        }
        if let Kind::EveryFrame { offset_min, offset_max } = c.kind {
            let _ = writeln!(
                out,
                "-- every frame, offsets [{offset_min}, {offset_max}]: the frame bounds are the\n\
                 -- pilout's; the row offsets inside the expression are relative to `i`."
            );
        }
        // A root shared by two constraints has its own definition; calling it
        // keeps the two constraints visibly the same expression.
        let body = if plan.is_defined(c.expr) {
            leaves.reference(c.expr)
        } else {
            print::render(ir, plan, leaves, c.expr)
        };
        let _ = writeln!(
            out,
            "def {} (x : Ctx F) (t : Trace F) (i : Int) : Prop :=\n  {} = 0\n",
            names.constraint[&c.idx], body
        );
    }
}

/// `everyRow`, `firstRow`, `lastRow`, and the `holds` that ties them together.
fn aggregate(out: &mut String, ir: &Ir, names: &Names) {
    let of_kind = |pred: fn(&Kind) -> bool| -> Vec<u32> {
        ir.constraints.iter().filter(|c| pred(&c.kind)).map(|c| c.idx).collect()
    };
    let every = of_kind(|k| matches!(k, Kind::EveryRow | Kind::EveryFrame { .. }));
    let first = of_kind(|k| matches!(k, Kind::FirstRow));
    let last = of_kind(|k| matches!(k, Kind::LastRow));

    let conjunction = |idxs: &[u32], row: &str| -> String {
        if idxs.is_empty() {
            return "True".to_string();
        }
        idxs.iter()
            .map(|i| format!("{} x t {row}", names.constraint[i]))
            .collect::<Vec<_>>()
            .join("\n  ∧ ")
    };

    let _ = writeln!(out, "/-! ### The AIR -/\n");
    let _ = writeln!(
        out,
        "/-- Every constraint asserted at every row, at row `i`. -/\n\
         def everyRow (x : Ctx F) (t : Trace F) (i : Int) : Prop :=\n  {}\n",
        conjunction(&every, "i")
    );
    let _ = writeln!(
        out,
        "/-- Constraints asserted only on the first row. -/\n\
         def firstRow (x : Ctx F) (t : Trace F) : Prop :=\n  {}\n",
        conjunction(&first, "0")
    );
    let _ = writeln!(
        out,
        "/-- Constraints asserted only on the last row. -/\n\
         def lastRow (x : Ctx F) (t : Trace F) : Prop :=\n  {}\n",
        conjunction(&last, "((numRows : Int) - 1)")
    );
    let _ = writeln!(
        out,
        "/-- The whole AIR: a periodic trace satisfying every constraint. -/\n\
         def holds (x : Ctx F) (t : Trace F) : Prop :=\n  \
         cyclic t\n  ∧ (∀ i : Int, everyRow x t i)\n  ∧ firstRow x t\n  ∧ lastRow x t\n"
    );
}

/// How to reach one scalar: a structure field, plus the indices to apply to it
/// when that field came from a PIL array.
struct Access {
    field: String,
    index: Vec<u32>,
}

impl Access {
    /// `a 0 1`, or just `flag` when the symbol is a scalar.
    fn render(&self) -> String {
        let mut out = self.field.clone();
        for i in &self.index {
            out.push_str(&format!(" {i}"));
        }
        out
    }
}

/// One structure field: a whole PIL symbol, array and all.
struct Field {
    /// The Lean identifier.
    name: String,
    /// The PIL name, for the comment.
    pil: String,
    /// Per-dimension extent; empty for a scalar.
    shape: Vec<u32>,
    /// Every scalar the symbol covers, as `(IR name, index)`.
    slots: Vec<(String, Vec<u32>)>,
    /// What kind of symbol it is, and which stage it sits in.
    what: String,
}

impl Field {
    fn new(slot: &Slot, what: &str, taken: &mut HashSet<String>) -> Field {
        let stage = if slot.stage == 0 { String::new() } else { format!(", stage {}", slot.stage) };
        let mut field = Field {
            name: unique(&ident(&slot.base), taken),
            pil: slot.base.clone(),
            shape: Vec::new(),
            slots: Vec::new(),
            what: format!("{what}{stage}"),
        };
        field.push(slot);
        field
    }

    fn push(&mut self, slot: &Slot) {
        for (dim, i) in slot.index.iter().enumerate() {
            match self.shape.get_mut(dim) {
                Some(extent) => *extent = (*extent).max(i + 1),
                None => self.shape.push(i + 1),
            }
        }
        self.slots.push((slot.name.clone(), slot.index.clone()));
    }

    /// `a : Nat → Nat → F` with `-- a[4][2] (witness, stage 1)` beside it.
    fn declare(&self) -> (String, String) {
        let arrows = "Nat → ".repeat(self.shape.len());
        let extents: String = self.shape.iter().map(|n| format!("[{n}]")).collect();
        (
            format!("{} : {arrows}F", self.name),
            format!("  -- {}{extents} ({})", self.pil, self.what),
        )
    }

    fn accesses(&self) -> Vec<(String, Access)> {
        self.slots
            .iter()
            .map(|(name, index)| {
                (name.clone(), Access { field: self.name.clone(), index: index.clone() })
            })
            .collect()
    }
}

/// Lean identifiers for every name the IR mentions, kept unique.
struct Names {
    /// `(declaration, trailing comment)`, in structure order.
    row_fields: Vec<(String, String)>,
    ctx_fields: Vec<(String, String)>,
    /// IR column name -> the field and indices that reach it.
    row: HashMap<String, Access>,
    /// IR global name -> the field and indices that reach it.
    ctx: HashMap<String, Access>,
    /// Expression index -> definition name.
    expr: HashMap<u32, String>,
    /// Constraint index -> definition name.
    constraint: HashMap<u32, String>,
}

impl Names {
    fn build(ir: &Ir, plan: &Plan) -> Names {
        let mut taken = HashSet::new();
        let mut this = Names {
            row_fields: Vec::new(),
            ctx_fields: Vec::new(),
            row: HashMap::new(),
            ctx: HashMap::new(),
            expr: HashMap::new(),
            constraint: HashMap::new(),
        };

        // One field per PIL symbol rather than per scalar, so a PIL array
        // becomes a field of function type. This is not cosmetic: Lean's
        // structure elaboration is superlinear in the number of fields, and
        // flattening every array put 599 fields in Keccakf's `Row` and `Ctx`,
        // which took over ten minutes to elaborate before a single constraint
        // was reached. Grouped, the same AIR declares a few dozen.
        //
        // The index type is `Nat`, not `Fin n`: only in-range indices are ever
        // generated, and `Nat` keeps them plain numerals instead of coercions.
        let group = |slots: &[Slot], what: &str, taken: &mut HashSet<String>| -> Vec<Field> {
            let mut fields: Vec<Field> = Vec::new();
            let mut by_base: HashMap<String, usize> = HashMap::new();
            for slot in slots {
                match by_base.get(&slot.base) {
                    Some(&at) => fields[at].push(slot),
                    None => {
                        by_base.insert(slot.base.clone(), fields.len());
                        fields.push(Field::new(slot, what, taken));
                    }
                }
            }
            fields
        };

        let columns = [
            (&ir.columns.witness, "witness"),
            (&ir.columns.fixed, "fixed"),
            (&ir.columns.periodic, "periodic"),
            (&ir.columns.custom, "custom commit"),
        ];
        for (slots, what) in columns {
            for field in group(slots, what, &mut taken) {
                this.row.extend(field.accesses());
                this.row_fields.push(field.declare());
            }
        }

        let globals = [
            (&ir.globals.air_values, "air value"),
            (&ir.globals.airgroup_values, "airgroup value"),
            (&ir.globals.publics, "public"),
            (&ir.globals.proof_values, "proof value"),
            (&ir.globals.challenges, "challenge"),
        ];
        for (slots, what) in globals {
            for field in group(slots, what, &mut taken) {
                this.ctx.extend(field.accesses());
                this.ctx_fields.push(field.declare());
            }
        }

        // A column an expression references but no symbol names. The pilout is
        // within its rights: the std library commits columns the PIL never
        // names. They still need a field, or the output would not compile.
        for (name, row) in referenced(ir) {
            let map = if row { &mut this.row } else { &mut this.ctx };
            if map.contains_key(&name) {
                continue;
            }
            let id = unique(&ident(&name), &mut taken);
            map.insert(name.clone(), Access { field: id.clone(), index: Vec::new() });
            let declaration = format!("{id} : F");
            let comment = format!("  -- {name} (no symbol in the pilout)");
            if row {
                this.row_fields.push((declaration, comment));
            } else {
                this.ctx_fields.push((declaration, comment));
            }
        }

        for c in &ir.constraints {
            let id = unique(&format!("c{}", c.idx), &mut taken);
            this.constraint.insert(c.idx, id);
        }

        // Named intermediates keep their PIL name; a name the compiler used
        // twice gets its expression index appended so both survive.
        let mut duplicated: HashMap<String, u32> = HashMap::new();
        for name in plan.named.values() {
            *duplicated.entry(name.clone()).or_default() += 1;
        }
        for idx in plan.definitions() {
            let name = match plan.named.get(&idx) {
                Some(pil) if duplicated.get(pil).copied().unwrap_or(0) > 1 => {
                    format!("{}_e{idx}", ident(pil))
                }
                Some(pil) => ident(pil),
                None => format!("e{idx}"),
            };
            let id = unique(&name, &mut taken);
            this.expr.insert(idx, id);
        }

        this
    }
}

/// Every leaf name the constraints reach, with whether it is row-dependent.
fn referenced(ir: &Ir) -> Vec<(String, bool)> {
    let mut seen = HashSet::new();
    let mut out = Vec::new();
    for idx in ir.reachable() {
        for operand in ir.expressions[idx as usize].operands() {
            let entry = match operand {
                Operand::Witness { name, .. }
                | Operand::Fixed { name, .. }
                | Operand::Periodic { name, .. }
                | Operand::Custom { name, .. } => Some((name.clone(), true)),
                Operand::AirValue { name, .. }
                | Operand::AirGroupValue { name, .. }
                | Operand::Public { name, .. }
                | Operand::ProofValue { name, .. }
                | Operand::Challenge { name, .. } => Some((name.clone(), false)),
                _ => None,
            };
            if let Some(entry) = entry {
                if seen.insert(entry.clone()) {
                    out.push(entry);
                }
            }
        }
    }
    out
}

struct LeanLeaves<'a> {
    names: &'a Names,
    /// Used to print `p - k` as `-k`, which is the same element and much easier
    /// to read. `None` if the characteristic did not fit a u128.
    base_field: Option<u128>,
}

impl Leaves for LeanLeaves<'_> {
    fn constant(&self, value: &str) -> String {
        // The compiler folds subtraction into `p - k`. Printing that back as
        // `-k` costs nothing (they are the same field element) and turns
        // `+ 18446744069414584320 * x` into `+ -x`.
        if let (Some(p), Ok(v)) = (self.base_field, value.parse::<u128>()) {
            if v > p / 2 && v < p {
                return format!("(-{})", p - v);
            }
        }
        value.to_string()
    }

    fn column(&self, name: &str, offset: i32) -> String {
        let access = match self.names.row.get(name) {
            Some(access) => access.render(),
            None => ident(name),
        };
        let row = match offset {
            0 => "t i".to_string(),
            o if o > 0 => format!("t (i + {o})"),
            o => format!("t (i - {})", -(o as i64)),
        };
        format!("({row}).{access}")
    }

    fn global(&self, name: &str) -> String {
        match self.names.ctx.get(name) {
            Some(access) => format!("x.{}", access.render()),
            None => format!("x.{}", ident(name)),
        }
    }

    fn reference(&self, idx: u32) -> String {
        format!("{} x t i", self.names.expr.get(&idx).cloned().unwrap_or_else(|| format!("e{idx}")))
    }
}

/// Lean 4 keywords that would break an identifier. Not exhaustive for the
/// language, only for what a PIL name can collide with.
const KEYWORDS: &[&str] = &[
    "at",
    "by",
    "calc",
    "do",
    "else",
    "end",
    "example",
    "exists",
    "from",
    "fun",
    "have",
    "if",
    "in",
    "instance",
    "let",
    "match",
    "mutual",
    "namespace",
    "open",
    "section",
    "set",
    "show",
    "structure",
    "then",
    "theorem",
    "this",
    "universe",
    "variable",
    "where",
    "with",
    "def",
    "deriving",
    "forall",
];

/// A PIL name as a Lean identifier: `Main.last_reg_value[3][1]` becomes
/// `Main_last_reg_value_3_1`. Apostrophes survive — `next_pc'` is already a
/// legal Lean identifier, and it is the PIL's own notation for the next row.
fn ident(name: &str) -> String {
    let mut out = String::new();
    // A run of characters Lean will not take becomes one `_`, and only once
    // something keepable follows it: `a[0]` is `a_0`, not `a_0_`. Underscores
    // in the original are kept as they are, so `__L1__` survives intact.
    let mut pending_separator = false;
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' || ch == '\'' {
            if pending_separator && !out.is_empty() {
                out.push('_');
            }
            pending_separator = false;
            out.push(ch);
        } else {
            pending_separator = true;
        }
    }
    let mut out = if out.is_empty() { "_anon".to_string() } else { out };
    if out.starts_with(|c: char| !c.is_ascii_alphabetic() && c != '_') {
        out.insert(0, '_');
    }
    if KEYWORDS.contains(&out.as_str()) {
        out.push('_');
    }
    out
}

fn unique(name: &str, taken: &mut HashSet<String>) -> String {
    if taken.insert(name.to_string()) {
        return name.to_string();
    }
    for n in 2.. {
        let candidate = format!("{name}_{n}");
        if taken.insert(candidate.clone()) {
            return candidate;
        }
    }
    unreachable!()
}

/// `/-` and `-/` inside a doc comment would end it early.
fn escape_doc(text: &str) -> String {
    text.replace("/-", "/ -").replace("-/", "- /")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn idents_are_legal_and_keep_the_pil_shape() {
        assert_eq!(ident("a[0]"), "a_0");
        assert_eq!(ident("Main.last_reg_value[3][1]"), "Main_last_reg_value_3_1");
        assert_eq!(ident("Main.next_pc'"), "Main_next_pc'");
        assert_eq!(ident("__L1__"), "__L1__");
        assert_eq!(ident("a[0]."), "a_0");
        assert_eq!(ident("at"), "at_");
        assert_eq!(ident("3col"), "_3col");
    }

    #[test]
    fn an_array_symbol_becomes_one_field_of_function_type() {
        let slot = |name: &str, index: Vec<u32>, id: u32| Slot {
            name: name.to_string(),
            base: "a".to_string(),
            index,
            stage: 1,
            id,
            commit: None,
        };
        let mut taken = HashSet::new();
        let mut field = Field::new(&slot("a[0][0]", vec![0, 0], 0), "witness", &mut taken);
        for (name, index, id) in [
            ("a[0][1]", vec![0, 1], 1),
            ("a[1][0]", vec![1, 0], 2),
            ("a[1][1]", vec![1, 1], 3),
            ("a[2][0]", vec![2, 0], 4),
            ("a[2][1]", vec![2, 1], 5),
        ] {
            field.push(&slot(name, index, id));
        }

        // The shape is recovered from the indices, so one field covers all six.
        let (declaration, comment) = field.declare();
        assert_eq!(declaration, "a : Nat → Nat → F");
        assert_eq!(comment, "  -- a[3][2] (witness, stage 1)");

        let accesses = field.accesses();
        assert_eq!(accesses.len(), 6);
        let rendered: Vec<String> = accesses.iter().map(|(_, a)| a.render()).collect();
        assert_eq!(rendered[0], "a 0 0");
        assert_eq!(rendered[5], "a 2 1");
    }

    #[test]
    fn a_scalar_symbol_stays_a_plain_field() {
        let mut taken = HashSet::new();
        let field = Field::new(
            &Slot {
                name: "flag".to_string(),
                base: "flag".to_string(),
                index: vec![],
                stage: 1,
                id: 6,
                commit: None,
            },
            "witness",
            &mut taken,
        );
        assert_eq!(field.declare().0, "flag : F");
        assert_eq!(field.accesses()[0].1.render(), "flag");
    }

    #[test]
    fn uniqueness_suffixes_only_on_collision() {
        let mut taken = HashSet::new();
        assert_eq!(unique("x", &mut taken), "x");
        assert_eq!(unique("x", &mut taken), "x_2");
        assert_eq!(unique("x", &mut taken), "x_3");
        assert_eq!(unique("y", &mut taken), "y");
    }
}
