[package]
name = "sm-freq-ops"
version = "0.1.0"
edition = "2021"

[dependencies]
zisk-core = { path = "../../core" }
sm-common = { path = "../common" }

# common = { git = "https://github.com/0xPolygonHermez/pil2-proofman.git", branch ="develop" }
# proofman = { git = "https://github.com/0xPolygonHermez/pil2-proofman.git", branch ="develop" }
# wchelpers = { git = "https://github.com/0xPolygonHermez/pil2-proofman.git", branch ="develop" }
#Local development
common = { workspace = true }
proofman = { workspace = true }
wchelpers = { workspace = true }

log = { version = "0.4", default-features = false }
p3-goldilocks = { git = "https://github.com/Plonky3/Plonky3.git", rev = "c3d754ef77b9fce585b46b972af751fe6e7a9803" }
p3-field = { git = "https://github.com/Plonky3/Plonky3.git", rev = "c3d754ef77b9fce585b46b972af751fe6e7a9803" }
rayon = "1.10.0"