[package]
name = "zkvm-interface"
description = "C interface bindings for the ZisK zkVM"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[build-dependencies]
bindgen = "0.72"
