[package]
name = "zisk-precomp-dma"
description = "Direct-memory-access precompile for the ZisK zkVM"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
categories = { workspace = true }

[dependencies]
zisk-core = { workspace = true }
zisk-common = { workspace = true }
zisk-pil = { workspace = true }
zisk-precomp-common = { workspace = true }
zisk-precomp-helpers = { workspace = true }

proofman-common = { workspace = true }
proofman-util = { workspace = true }
pil2-std-lib = { workspace = true }
proofman-fields = { workspace = true }
tracing = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
zisk-test-artifacts = { workspace = true }

[features]
default = []
dma_memcmp = []
debug_dma = []
save_dma_collectors = []
save_dma_inputs = []
save_dma_plans = []
debug_dma_gen_mem_inputs = []
