[package]
name = "sm-quick-ops"
version = "0.1.0"
edition = "2021"

[dependencies]
zisk-core = { path = "../../core" }
sm-common = { path = "../common" }

proofman-common = { workspace = true }
proofman-setup = { workspace = true }
proofman = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }