#ifndef __MEM_CONFIG_HPP__
#define __MEM_CONFIG_HPP__

#define ROM_ADDR 0x80000000
#define INPUT_ADDR 0x40000000
#define RAM_ADDR 0xA0000000

#define ROM_SIZE_MB 128
#define INPUT_SIZE_MB 1024
#define RAM_SIZE_MB 512

#define CHUNK_SIZE_BITS 18
#define CHUNK_SIZE (1 << CHUNK_SIZE_BITS)
#define MAX_LOCATORS 2048
#define MAX_MEM_PLANNERS 8
#define USE_ADDR_COUNT_TABLE
#define MAX_SEGMENTS 512
// #define MEM_PLANNER_STATS
// #define MEM_SAVE_CPP_OFFSETS

#define MEM_CHECK_POINT_MAP
// #define SEGMENT_STATS
// #define CHUNK_STATS
// #define COUNT_CHUNK_STATS
#define SEGMENT_LARGE_CHUNKS 512

#define MEM_TYPES 3
#define ROM_ID 0
#define INPUT_ID 1
#define RAM_ID 2



#define MAX_CHUNKS (1 << 18)     // 2^36 / 2^18 = 2^18

// THREAD_BITS >= 1
#define THREAD_BITS 2
#define ADDR_LOW_BITS (THREAD_BITS + 3)
#define MAX_THREADS (1 << THREAD_BITS)
#define ADDR_MASK ((MAX_THREADS - 1) * 8)

#define MAX_PAGES 26
#define ADDR_PAGE_BITS (23 - THREAD_BITS)
#define ADDR_PAGE_SIZE (1 << ADDR_PAGE_BITS)
#define RELATIVE_OFFSET_MASK (ADDR_PAGE_SIZE - 1)
#define ADDR_TABLE_SIZE (ADDR_PAGE_SIZE * MAX_PAGES)
#define OFFSET_BITS (25 + 4 - THREAD_BITS) // 4 bits (3 bits for 6 pages, 1 bit security)
#define OFFSET_PAGE_SHIFT_BITS (OFFSET_BITS - 3)

#define MAX_SLOT_GB 6
#define ADDR_SLOT_BITS 5
#define ADDR_SLOT_BYTES 4
#define ADDR_SLOT_SIZE (1 << ADDR_SLOT_BITS)
#define ADDR_SLOT_MASK (0xFFFFFFFF << ADDR_SLOT_BITS)
#define ADDR_TOTAL_SLOTS ((((size_t)MAX_SLOT_GB) << 30) / (ADDR_SLOT_SIZE * ADDR_SLOT_BYTES))
#define ADDR_SLOTS (ADDR_TOTAL_SLOTS / MAX_THREADS)

#define ADDR_SLOTS_SIZE (ADDR_SLOT_SIZE * ADDR_SLOTS)
#define TIME_US_BY_CHUNK 173

#define NO_CHUNK_ID 0xFFFFFFFF
#define EMPTY_PAGE 0xFFFFFFFF

#define OFFSET_PAGE_SIZE 1024
#define MAX_OFFSETS (1 << 22)

#define MAX_OFFSET_PAGES_INCREMENT 8192
#define MAX_OFFSET_INCREMENT (1024 * OFFSET_PAGE_SIZE)
#define MEM_OFFSETS_PAGES 4096
#define MEM_OFFSETS MAX_OFFSET_INCREMENT

#define MAX_IMMUTABLE_ADDR_DISTANCE (1 << 24)

// SINGLE WRITE FLAGS
//                bits
// bytes(4)        0-3   (values 1,2,4,8)
// write_flag (1)    4
// clear_flag (1)    5

#include "mops_format.hpp"

#endif
