[package]
name = "zisk-prover-backend"
description = "Proving backend for the ZisK zkVM"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
categories = { workspace = true }

[dependencies]
# Proofman dependencies
proofman = { workspace = true }
proofman-common = { workspace = true }
proofman-util = { workspace = true }
proofman-verifier = { workspace = true, features = ["parallel", "verify"] }

# Zisk internal crates
zisk-program-macros = { workspace = true }
zisk-common = { workspace = true }
zisk-core = { workspace = true }
zisk-pil = { workspace = true }
zisk-cluster-common = { workspace = true }
zisk-transpiler-riscv = { workspace = true }
zisk-executor = { workspace = true }
zisk-rom-setup = { workspace = true }
zisk-asm-runner = { workspace = true }
zisk-precomp-hints = { workspace = true }
proofman-fields = { workspace = true }
borsh = { workspace = true }

# Optional dependencies
ziskemu = { workspace = true }

# External dependencies
anyhow = { workspace = true }
colored = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
blake3 = { workspace = true }
alloy-sol-types = { workspace = true }

[features]
default = []
cpu-only = ["proofman-common/cpu-only", "zisk-executor/cpu-only"]
stats = []
diagnostic = ["proofman-common/diagnostic"]
