[package]
name = "zisksim"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv2zisk = {path="../riscv/riscv2zisk"}

[lib]
name = "zisksim"
path = "src/lib.rs"

[[bin]]
name = "zisksim"
path = "src/bin/zisksim.rs"