[package]
name = "zisk-riscv"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[dependencies]
zisk-definitions = { workspace = true }
zisk-core = { workspace = true }

[build-dependencies]
lib-float = { workspace = true, optional = true }

[features]
default = []
float = ["dep:lib-float", "lib-float/float"]
bit_manipulation_extensions = []