reorder_imports = true
use_small_heuristics = "Max"
use_field_init_shorthand = true

## Nightly options:
# imports_granularity = "Crate"
# comment_width = 100
# wrap_comments = true
# binop_separator = "Front"
# trailing_comma = "Vertical"
# trailing_semicolon = false
# format_code_in_doc_comments = true
# doc_comment_code_block_width = 100