// code generated
//
// equation: s*s-x1-x2-x3-p*q1+p*offset
//
// p: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F
// offset: 0x4
// (p*offset): 0x3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFF0BC
//
// chunks:16
// chunk_bits:16
// terms_by_clock: 2

pub struct Secp256k1X3 {}

impl Secp256k1X3 {
    #[allow(clippy::too_many_arguments)]
    pub fn calculate(
        icol: u8,
        x1: &[i64; 16],
        x2: &[i64; 16],
        x3: &[i64; 16],
        s: &[i64; 16],
        q1: &[i64; 16],
    ) -> i64 {
        match icol {
            0 => s[0] * s[0] - x1[0] - x2[0] - x3[0] - 0xFC2F * q1[0] + 0xF0BC,
            1 => {
                s[1] * s[0] + s[0] * s[1] - x1[1] - x2[1] - x3[1] - 0xFFFF * q1[0] - 0xFC2F * q1[1]
                    + 0xFFFF
            }
            2 => {
                s[2] * s[0] + s[1] * s[1] + s[0] * s[2]
                    - x1[2]
                    - x2[2]
                    - x3[2]
                    - 0xFFFE * q1[0]
                    - 0xFFFF * q1[1]
                    - 0xFC2F * q1[2]
                    + 0xFFFB
            }
            3 => {
                s[3] * s[0] + s[2] * s[1] + s[1] * s[2] + s[0] * s[3]
                    - x1[3]
                    - x2[3]
                    - x3[3]
                    - 0xFFFF * q1[0]
                    - 0xFFFE * q1[1]
                    - 0xFFFF * q1[2]
                    - 0xFC2F * q1[3]
                    + 0xFFFF
            }
            4 => {
                s[4] * s[0] + s[3] * s[1] + s[2] * s[2] + s[1] * s[3] + s[0] * s[4]
                    - x1[4]
                    - x2[4]
                    - x3[4]
                    - 0xFFFF * q1[0]
                    - 0xFFFF * q1[1]
                    - 0xFFFE * q1[2]
                    - 0xFFFF * q1[3]
                    - 0xFC2F * q1[4]
                    + 0xFFFF
            }
            5 => {
                s[5] * s[0] + s[4] * s[1] + s[3] * s[2] + s[2] * s[3] + s[1] * s[4] + s[0] * s[5]
                    - x1[5]
                    - x2[5]
                    - x3[5]
                    - 0xFFFF * q1[0]
                    - 0xFFFF * q1[1]
                    - 0xFFFF * q1[2]
                    - 0xFFFE * q1[3]
                    - 0xFFFF * q1[4]
                    - 0xFC2F * q1[5]
                    + 0xFFFF
            }
            6 => {
                s[6] * s[0]
                    + s[5] * s[1]
                    + s[4] * s[2]
                    + s[3] * s[3]
                    + s[2] * s[4]
                    + s[1] * s[5]
                    + s[0] * s[6]
                    - x1[6]
                    - x2[6]
                    - x3[6]
                    - 0xFFFF * q1[0]
                    - 0xFFFF * q1[1]
                    - 0xFFFF * q1[2]
                    - 0xFFFF * q1[3]
                    - 0xFFFE * q1[4]
                    - 0xFFFF * q1[5]
                    - 0xFC2F * q1[6]
                    + 0xFFFF
            }
            7 => {
                s[7] * s[0]
                    + s[6] * s[1]
                    + s[5] * s[2]
                    + s[4] * s[3]
                    + s[3] * s[4]
                    + s[2] * s[5]
                    + s[1] * s[6]
                    + s[0] * s[7]
                    - x1[7]
                    - x2[7]
                    - x3[7]
                    - 0xFFFF * q1[0]
                    - 0xFFFF * q1[1]
                    - 0xFFFF * q1[2]
                    - 0xFFFF * q1[3]
                    - 0xFFFF * q1[4]
                    - 0xFFFE * q1[5]
                    - 0xFFFF * q1[6]
                    - 0xFC2F * q1[7]
                    + 0xFFFF
            }
            8 => {
                s[8] * s[0]
                    + s[7] * s[1]
                    + s[6] * s[2]
                    + s[5] * s[3]
                    + s[4] * s[4]
                    + s[3] * s[5]
                    + s[2] * s[6]
                    + s[1] * s[7]
                    + s[0] * s[8]
                    - x1[8]
                    - x2[8]
                    - x3[8]
                    - 0xFFFF * q1[0]
                    - 0xFFFF * q1[1]
                    - 0xFFFF * q1[2]
                    - 0xFFFF * q1[3]
                    - 0xFFFF * q1[4]
                    - 0xFFFF * q1[5]
                    - 0xFFFE * q1[6]
                    - 0xFFFF * q1[7]
                    - 0xFC2F * q1[8]
                    + 0xFFFF
            }
            9 => {
                s[9] * s[0]
                    + s[8] * s[1]
                    + s[7] * s[2]
                    + s[6] * s[3]
                    + s[5] * s[4]
                    + s[4] * s[5]
                    + s[3] * s[6]
                    + s[2] * s[7]
                    + s[1] * s[8]
                    + s[0] * s[9]
                    - x1[9]
                    - x2[9]
                    - x3[9]
                    - 0xFFFF * q1[0]
                    - 0xFFFF * q1[1]
                    - 0xFFFF * q1[2]
                    - 0xFFFF * q1[3]
                    - 0xFFFF * q1[4]
                    - 0xFFFF * q1[5]
                    - 0xFFFF * q1[6]
                    - 0xFFFE * q1[7]
                    - 0xFFFF * q1[8]
                    - 0xFC2F * q1[9]
                    + 0xFFFF
            }
            10 => {
                s[10] * s[0]
                    + s[9] * s[1]
                    + s[8] * s[2]
                    + s[7] * s[3]
                    + s[6] * s[4]
                    + s[5] * s[5]
                    + s[4] * s[6]
                    + s[3] * s[7]
                    + s[2] * s[8]
                    + s[1] * s[9]
                    + s[0] * s[10]
                    - x1[10]
                    - x2[10]
                    - x3[10]
                    - 0xFFFF * q1[0]
                    - 0xFFFF * q1[1]
                    - 0xFFFF * q1[2]
                    - 0xFFFF * q1[3]
                    - 0xFFFF * q1[4]
                    - 0xFFFF * q1[5]
                    - 0xFFFF * q1[6]
                    - 0xFFFF * q1[7]
                    - 0xFFFE * q1[8]
                    - 0xFFFF * q1[9]
                    - 0xFC2F * q1[10]
                    + 0xFFFF
            }
            11 => {
                s[11] * s[0]
                    + s[10] * s[1]
                    + s[9] * s[2]
                    + s[8] * s[3]
                    + s[7] * s[4]
                    + s[6] * s[5]
                    + s[5] * s[6]
                    + s[4] * s[7]
                    + s[3] * s[8]
                    + s[2] * s[9]
                    + s[1] * s[10]
                    + s[0] * s[11]
                    - x1[11]
                    - x2[11]
                    - x3[11]
                    - 0xFFFF * q1[0]
                    - 0xFFFF * q1[1]
                    - 0xFFFF * q1[2]
                    - 0xFFFF * q1[3]
                    - 0xFFFF * q1[4]
                    - 0xFFFF * q1[5]
                    - 0xFFFF * q1[6]
                    - 0xFFFF * q1[7]
                    - 0xFFFF * q1[8]
                    - 0xFFFE * q1[9]
                    - 0xFFFF * q1[10]
                    - 0xFC2F * q1[11]
                    + 0xFFFF
            }
            12 => {
                s[12] * s[0]
                    + s[11] * s[1]
                    + s[10] * s[2]
                    + s[9] * s[3]
                    + s[8] * s[4]
                    + s[7] * s[5]
                    + s[6] * s[6]
                    + s[5] * s[7]
                    + s[4] * s[8]
                    + s[3] * s[9]
                    + s[2] * s[10]
                    + s[1] * s[11]
                    + s[0] * s[12]
                    - x1[12]
                    - x2[12]
                    - x3[12]
                    - 0xFFFF * q1[0]
                    - 0xFFFF * q1[1]
                    - 0xFFFF * q1[2]
                    - 0xFFFF * q1[3]
                    - 0xFFFF * q1[4]
                    - 0xFFFF * q1[5]
                    - 0xFFFF * q1[6]
                    - 0xFFFF * q1[7]
                    - 0xFFFF * q1[8]
                    - 0xFFFF * q1[9]
                    - 0xFFFE * q1[10]
                    - 0xFFFF * q1[11]
                    - 0xFC2F * q1[12]
                    + 0xFFFF
            }
            13 => {
                s[13] * s[0]
                    + s[12] * s[1]
                    + s[11] * s[2]
                    + s[10] * s[3]
                    + s[9] * s[4]
                    + s[8] * s[5]
                    + s[7] * s[6]
                    + s[6] * s[7]
                    + s[5] * s[8]
                    + s[4] * s[9]
                    + s[3] * s[10]
                    + s[2] * s[11]
                    + s[1] * s[12]
                    + s[0] * s[13]
                    - x1[13]
                    - x2[13]
                    - x3[13]
                    - 0xFFFF * q1[0]
                    - 0xFFFF * q1[1]
                    - 0xFFFF * q1[2]
                    - 0xFFFF * q1[3]
                    - 0xFFFF * q1[4]
                    - 0xFFFF * q1[5]
                    - 0xFFFF * q1[6]
                    - 0xFFFF * q1[7]
                    - 0xFFFF * q1[8]
                    - 0xFFFF * q1[9]
                    - 0xFFFF * q1[10]
                    - 0xFFFE * q1[11]
                    - 0xFFFF * q1[12]
                    - 0xFC2F * q1[13]
                    + 0xFFFF
            }
            14 => {
                s[14] * s[0]
                    + s[13] * s[1]
                    + s[12] * s[2]
                    + s[11] * s[3]
                    + s[10] * s[4]
                    + s[9] * s[5]
                    + s[8] * s[6]
                    + s[7] * s[7]
                    + s[6] * s[8]
                    + s[5] * s[9]
                    + s[4] * s[10]
                    + s[3] * s[11]
                    + s[2] * s[12]
                    + s[1] * s[13]
                    + s[0] * s[14]
                    - x1[14]
                    - x2[14]
                    - x3[14]
                    - 0xFFFF * q1[0]
                    - 0xFFFF * q1[1]
                    - 0xFFFF * q1[2]
                    - 0xFFFF * q1[3]
                    - 0xFFFF * q1[4]
                    - 0xFFFF * q1[5]
                    - 0xFFFF * q1[6]
                    - 0xFFFF * q1[7]
                    - 0xFFFF * q1[8]
                    - 0xFFFF * q1[9]
                    - 0xFFFF * q1[10]
                    - 0xFFFF * q1[11]
                    - 0xFFFE * q1[12]
                    - 0xFFFF * q1[13]
                    - 0xFC2F * q1[14]
                    + 0xFFFF
            }
            15 => {
                s[15] * s[0]
                    + s[14] * s[1]
                    + s[13] * s[2]
                    + s[12] * s[3]
                    + s[11] * s[4]
                    + s[10] * s[5]
                    + s[9] * s[6]
                    + s[8] * s[7]
                    + s[7] * s[8]
                    + s[6] * s[9]
                    + s[5] * s[10]
                    + s[4] * s[11]
                    + s[3] * s[12]
                    + s[2] * s[13]
                    + s[1] * s[14]
                    + s[0] * s[15]
                    - x1[15]
                    - x2[15]
                    - x3[15]
                    - 0xFFFF * q1[0]
                    - 0xFFFF * q1[1]
                    - 0xFFFF * q1[2]
                    - 0xFFFF * q1[3]
                    - 0xFFFF * q1[4]
                    - 0xFFFF * q1[5]
                    - 0xFFFF * q1[6]
                    - 0xFFFF * q1[7]
                    - 0xFFFF * q1[8]
                    - 0xFFFF * q1[9]
                    - 0xFFFF * q1[10]
                    - 0xFFFF * q1[11]
                    - 0xFFFF * q1[12]
                    - 0xFFFE * q1[13]
                    - 0xFFFF * q1[14]
                    - 0xFC2F * q1[15]
                    + 0xFFFF
            }
            16 => {
                s[15] * s[1]
                    + s[14] * s[2]
                    + s[13] * s[3]
                    + s[12] * s[4]
                    + s[11] * s[5]
                    + s[10] * s[6]
                    + s[9] * s[7]
                    + s[8] * s[8]
                    + s[7] * s[9]
                    + s[6] * s[10]
                    + s[5] * s[11]
                    + s[4] * s[12]
                    + s[3] * s[13]
                    + s[2] * s[14]
                    + s[1] * s[15]
                    - 0xFFFF * q1[1]
                    - 0xFFFF * q1[2]
                    - 0xFFFF * q1[3]
                    - 0xFFFF * q1[4]
                    - 0xFFFF * q1[5]
                    - 0xFFFF * q1[6]
                    - 0xFFFF * q1[7]
                    - 0xFFFF * q1[8]
                    - 0xFFFF * q1[9]
                    - 0xFFFF * q1[10]
                    - 0xFFFF * q1[11]
                    - 0xFFFF * q1[12]
                    - 0xFFFF * q1[13]
                    - 0xFFFE * q1[14]
                    - 0xFFFF * q1[15]
                    + 0x3
            }
            17 => {
                s[15] * s[2]
                    + s[14] * s[3]
                    + s[13] * s[4]
                    + s[12] * s[5]
                    + s[11] * s[6]
                    + s[10] * s[7]
                    + s[9] * s[8]
                    + s[8] * s[9]
                    + s[7] * s[10]
                    + s[6] * s[11]
                    + s[5] * s[12]
                    + s[4] * s[13]
                    + s[3] * s[14]
                    + s[2] * s[15]
                    - 0xFFFF * q1[2]
                    - 0xFFFF * q1[3]
                    - 0xFFFF * q1[4]
                    - 0xFFFF * q1[5]
                    - 0xFFFF * q1[6]
                    - 0xFFFF * q1[7]
                    - 0xFFFF * q1[8]
                    - 0xFFFF * q1[9]
                    - 0xFFFF * q1[10]
                    - 0xFFFF * q1[11]
                    - 0xFFFF * q1[12]
                    - 0xFFFF * q1[13]
                    - 0xFFFF * q1[14]
                    - 0xFFFE * q1[15]
            }
            18 => {
                s[15] * s[3]
                    + s[14] * s[4]
                    + s[13] * s[5]
                    + s[12] * s[6]
                    + s[11] * s[7]
                    + s[10] * s[8]
                    + s[9] * s[9]
                    + s[8] * s[10]
                    + s[7] * s[11]
                    + s[6] * s[12]
                    + s[5] * s[13]
                    + s[4] * s[14]
                    + s[3] * s[15]
                    - 0xFFFF * q1[3]
                    - 0xFFFF * q1[4]
                    - 0xFFFF * q1[5]
                    - 0xFFFF * q1[6]
                    - 0xFFFF * q1[7]
                    - 0xFFFF * q1[8]
                    - 0xFFFF * q1[9]
                    - 0xFFFF * q1[10]
                    - 0xFFFF * q1[11]
                    - 0xFFFF * q1[12]
                    - 0xFFFF * q1[13]
                    - 0xFFFF * q1[14]
                    - 0xFFFF * q1[15]
            }
            19 => {
                s[15] * s[4]
                    + s[14] * s[5]
                    + s[13] * s[6]
                    + s[12] * s[7]
                    + s[11] * s[8]
                    + s[10] * s[9]
                    + s[9] * s[10]
                    + s[8] * s[11]
                    + s[7] * s[12]
                    + s[6] * s[13]
                    + s[5] * s[14]
                    + s[4] * s[15]
                    - 0xFFFF * q1[4]
                    - 0xFFFF * q1[5]
                    - 0xFFFF * q1[6]
                    - 0xFFFF * q1[7]
                    - 0xFFFF * q1[8]
                    - 0xFFFF * q1[9]
                    - 0xFFFF * q1[10]
                    - 0xFFFF * q1[11]
                    - 0xFFFF * q1[12]
                    - 0xFFFF * q1[13]
                    - 0xFFFF * q1[14]
                    - 0xFFFF * q1[15]
            }
            20 => {
                s[15] * s[5]
                    + s[14] * s[6]
                    + s[13] * s[7]
                    + s[12] * s[8]
                    + s[11] * s[9]
                    + s[10] * s[10]
                    + s[9] * s[11]
                    + s[8] * s[12]
                    + s[7] * s[13]
                    + s[6] * s[14]
                    + s[5] * s[15]
                    - 0xFFFF * q1[5]
                    - 0xFFFF * q1[6]
                    - 0xFFFF * q1[7]
                    - 0xFFFF * q1[8]
                    - 0xFFFF * q1[9]
                    - 0xFFFF * q1[10]
                    - 0xFFFF * q1[11]
                    - 0xFFFF * q1[12]
                    - 0xFFFF * q1[13]
                    - 0xFFFF * q1[14]
                    - 0xFFFF * q1[15]
            }
            21 => {
                s[15] * s[6]
                    + s[14] * s[7]
                    + s[13] * s[8]
                    + s[12] * s[9]
                    + s[11] * s[10]
                    + s[10] * s[11]
                    + s[9] * s[12]
                    + s[8] * s[13]
                    + s[7] * s[14]
                    + s[6] * s[15]
                    - 0xFFFF * q1[6]
                    - 0xFFFF * q1[7]
                    - 0xFFFF * q1[8]
                    - 0xFFFF * q1[9]
                    - 0xFFFF * q1[10]
                    - 0xFFFF * q1[11]
                    - 0xFFFF * q1[12]
                    - 0xFFFF * q1[13]
                    - 0xFFFF * q1[14]
                    - 0xFFFF * q1[15]
            }
            22 => {
                s[15] * s[7]
                    + s[14] * s[8]
                    + s[13] * s[9]
                    + s[12] * s[10]
                    + s[11] * s[11]
                    + s[10] * s[12]
                    + s[9] * s[13]
                    + s[8] * s[14]
                    + s[7] * s[15]
                    - 0xFFFF * q1[7]
                    - 0xFFFF * q1[8]
                    - 0xFFFF * q1[9]
                    - 0xFFFF * q1[10]
                    - 0xFFFF * q1[11]
                    - 0xFFFF * q1[12]
                    - 0xFFFF * q1[13]
                    - 0xFFFF * q1[14]
                    - 0xFFFF * q1[15]
            }
            23 => {
                s[15] * s[8]
                    + s[14] * s[9]
                    + s[13] * s[10]
                    + s[12] * s[11]
                    + s[11] * s[12]
                    + s[10] * s[13]
                    + s[9] * s[14]
                    + s[8] * s[15]
                    - 0xFFFF * q1[8]
                    - 0xFFFF * q1[9]
                    - 0xFFFF * q1[10]
                    - 0xFFFF * q1[11]
                    - 0xFFFF * q1[12]
                    - 0xFFFF * q1[13]
                    - 0xFFFF * q1[14]
                    - 0xFFFF * q1[15]
            }
            24 => {
                s[15] * s[9]
                    + s[14] * s[10]
                    + s[13] * s[11]
                    + s[12] * s[12]
                    + s[11] * s[13]
                    + s[10] * s[14]
                    + s[9] * s[15]
                    - 0xFFFF * q1[9]
                    - 0xFFFF * q1[10]
                    - 0xFFFF * q1[11]
                    - 0xFFFF * q1[12]
                    - 0xFFFF * q1[13]
                    - 0xFFFF * q1[14]
                    - 0xFFFF * q1[15]
            }
            25 => {
                s[15] * s[10]
                    + s[14] * s[11]
                    + s[13] * s[12]
                    + s[12] * s[13]
                    + s[11] * s[14]
                    + s[10] * s[15]
                    - 0xFFFF * q1[10]
                    - 0xFFFF * q1[11]
                    - 0xFFFF * q1[12]
                    - 0xFFFF * q1[13]
                    - 0xFFFF * q1[14]
                    - 0xFFFF * q1[15]
            }
            26 => {
                s[15] * s[11] + s[14] * s[12] + s[13] * s[13] + s[12] * s[14] + s[11] * s[15]
                    - 0xFFFF * q1[11]
                    - 0xFFFF * q1[12]
                    - 0xFFFF * q1[13]
                    - 0xFFFF * q1[14]
                    - 0xFFFF * q1[15]
            }
            27 => {
                s[15] * s[12] + s[14] * s[13] + s[13] * s[14] + s[12] * s[15]
                    - 0xFFFF * q1[12]
                    - 0xFFFF * q1[13]
                    - 0xFFFF * q1[14]
                    - 0xFFFF * q1[15]
            }
            28 => {
                s[15] * s[13] + s[14] * s[14] + s[13] * s[15]
                    - 0xFFFF * q1[13]
                    - 0xFFFF * q1[14]
                    - 0xFFFF * q1[15]
            }
            29 => s[15] * s[14] + s[14] * s[15] - 0xFFFF * q1[14] - 0xFFFF * q1[15],
            30 => s[15] * s[15] - 0xFFFF * q1[15],
            _ => 0,
        }
    }
}
