// WARNING: This file has been autogenerated from the PILOUT file.
// Manual modifications are not recommended and may be overwritten.
pub use proofman_macros::trace;
use proofman_common as common;

trace!(Connection10Row, Connection10Trace<F> {
 a: F,  b: F,  c: F,
});

trace!(ConnectionNew1Row, ConnectionNew1Trace<F> {
 a: [F; 5],  b: [F; 5],  c: [F; 5],  d: [F; 5],
});
