use crate::cluster::ClusterRegistry;
use crate::config::NodeConfig;
use crate::coordinator_client::ZiskCoordinatorClient;
use crate::grpc::logging::GrpcLoggingLayer;
use crate::grpc::user::zisk_user_api_server::ZiskUserApiServer;
use crate::grpc::user_api::UserApiService;
use crate::grpc::MAX_MESSAGE_SIZE;
use crate::server::shutdown::wait_for_shutdown;
use crate::service::ZiskNodeService;
use anyhow::Result;
use std::net::SocketAddr;
use std::sync::Arc;
use std::time::Duration;
use tonic_health::server::health_reporter;
use tonic_reflection::server::Builder as ReflectionBuilder;
use tracing::info;

/// Encoded proto descriptor set generated by build.rs — used by gRPC reflection.
pub const FILE_DESCRIPTOR_SET: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/zisk_descriptor.bin"));

pub struct ZiskNodeServer {
    config: NodeConfig,
    cluster_registry: Option<Arc<ClusterRegistry>>,
}

impl ZiskNodeServer {
    pub fn new(config: NodeConfig, cluster_registry: Option<Arc<ClusterRegistry>>) -> Self {
        Self { config, cluster_registry }
    }

    pub async fn run(self) -> Result<()> {
        let addr: SocketAddr =
            format!("{}:{}", self.config.server.host, self.config.server.port).parse()?;

        let coordinator_client = self.cluster_registry.as_ref().and_then(|reg| {
            info!("Loaded cluster '{}'", reg.cluster_name());
            match reg.coordinator_url() {
                Ok(url) => {
                    info!("Coordinator at {url}");
                    match ZiskCoordinatorClient::connect(url) {
                        Ok(client) => Some(client),
                        Err(e) => {
                            tracing::warn!(
                                "Invalid coordinator URL: {e}. Running without coordinator."
                            );
                            None
                        }
                    }
                }
                Err(e) => {
                    tracing::warn!(
                        "Could not resolve coordinator URL: {e}. Running without coordinator."
                    );
                    None
                }
            }
        });

        // ── Health ────────────────────────────────────────────────────────────
        let (health_reporter, health_service) = health_reporter();
        health_reporter.set_serving::<ZiskUserApiServer<UserApiService>>().await;

        // ── Reflection ────────────────────────────────────────────────────────
        let reflection_service = ReflectionBuilder::configure()
            .register_encoded_file_descriptor_set(FILE_DESCRIPTOR_SET)
            .build_v1()?;

        // ── Services ──────────────────────────────────────────────────────────
        let node_service =
            Arc::new(ZiskNodeService::new(self.cluster_registry, coordinator_client));

        let user_svc = ZiskUserApiServer::new(UserApiService::new(node_service))
            .max_decoding_message_size(MAX_MESSAGE_SIZE)
            .max_encoding_message_size(MAX_MESSAGE_SIZE);

        info!("zisklet listening on {addr}");

        // ── Graceful shutdown ─────────────────────────────────────────────────
        // Mark both services NOT_SERVING before the server stops accepting
        // connections so load balancers and Kubernetes drain traffic cleanly.
        let shutdown = async move {
            wait_for_shutdown().await;
            info!("Shutdown signal received — draining traffic");
            health_reporter.set_not_serving::<ZiskUserApiServer<UserApiService>>().await;
        };

        let serve = tonic::transport::Server::builder()
            .layer(GrpcLoggingLayer)
            .add_service(health_service)
            .add_service(reflection_service)
            .add_service(user_svc)
            .serve_with_shutdown(addr, shutdown);

        let timeout = Duration::from_secs(self.config.server.shutdown_timeout_seconds);
        match tokio::time::timeout(timeout, serve).await {
            Ok(result) => result?,
            Err(_) => {
                tracing::warn!(
                    timeout_secs = self.config.server.shutdown_timeout_seconds,
                    "Shutdown timed out — forcing exit"
                );
            }
        }

        info!("zisklet shut down cleanly");
        Ok(())
    }
}
