[package]
name = "sm-common"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[dependencies]
zisk-core = { path = "../../core" }
zisk-common = { path = "../../common" }
data-bus = { path = "../../data-bus" }
asm-runner = { path = "../../emulator-asm/asm-runner" }

proofman-common = { workspace = true }
proofman-util = { workspace = true }
p3-field = { workspace = true }

rayon = { workspace = true }

[features]
default = ["distributed"]
distributed = ["proofman-common/distributed"]