[package]
name = "sm-common"
version = "0.4.3"
edition = "2021"

[dependencies]
zisk-core = { path = "../../core" }
data-bus = { path = "../../data-bus" }

proofman-common = { workspace = true }
proofman-util = { workspace = true }
p3-field = { workspace = true }

rayon = { workspace = true }

[features]
default = []
gpu = ["proofman-common/gpu"]