[package]
name = "sm-common"
version = "0.1.0"
edition = "2021"

[dependencies]
zisk-core = { path = "../../core" }
zisk-common = { path = "../../common" }

proofman-common = { workspace = true }
proofman-util = { workspace = true }
p3-field = { workspace = true }

rayon = "1.10.0"