[package]
name = "sm-common"
version = "0.2.0"
edition = "2021"

[dependencies]
zisk-core = { path = "../../core" }
data-bus = { path = "../../data-bus" }

proofman-common = { workspace = true }
proofman-util = { workspace = true }
p3-field = { workspace = true }

rayon = { workspace = true }