//! RISC-V registers

/// Human-readable names of the 32 well-known RISC-V registers, to be used in traces
#[repr(usize)]
pub enum RiscVRegisters {
    Zero = 0,
    Ra = 1,
    Sp = 2,
    Gp = 3,
    Tp = 4,
    T0 = 5,
    T1 = 6,
    T2 = 7,
    S0 = 8,
    S1 = 9,
    A0 = 10,
    A1 = 11,
    A2 = 12,
    A3 = 13,
    A4 = 14,
    A5 = 15,
    A6 = 16,
    A7 = 17,
    S2 = 18,
    S3 = 19,
    S4 = 20,
    S5 = 21,
    S6 = 22,
    S7 = 23,
    S8 = 24,
    S9 = 25,
    S10 = 26,
    S11 = 27,
    T3 = 28,
    T4 = 29,
    T5 = 30,
    T6 = 31,
}

impl RiscVRegisters {
    pub fn name(&self) -> &'static str {
        match self {
            RiscVRegisters::Zero => "zero",
            RiscVRegisters::Ra => "ra",
            RiscVRegisters::Sp => "sp",
            RiscVRegisters::Gp => "gp",
            RiscVRegisters::Tp => "tp",
            RiscVRegisters::T0 => "t0",
            RiscVRegisters::T1 => "t1",
            RiscVRegisters::T2 => "t2",
            RiscVRegisters::S0 => "s0",
            RiscVRegisters::S1 => "s1",
            RiscVRegisters::A0 => "a0",
            RiscVRegisters::A1 => "a1",
            RiscVRegisters::A2 => "a2",
            RiscVRegisters::A3 => "a3",
            RiscVRegisters::A4 => "a4",
            RiscVRegisters::A5 => "a5",
            RiscVRegisters::A6 => "a6",
            RiscVRegisters::A7 => "a7",
            RiscVRegisters::S2 => "s2",
            RiscVRegisters::S3 => "s3",
            RiscVRegisters::S4 => "s4",
            RiscVRegisters::S5 => "s5",
            RiscVRegisters::S6 => "s6",
            RiscVRegisters::S7 => "s7",
            RiscVRegisters::S8 => "s8",
            RiscVRegisters::S9 => "s9",
            RiscVRegisters::S10 => "s10",
            RiscVRegisters::S11 => "s11",
            RiscVRegisters::T3 => "t3",
            RiscVRegisters::T4 => "t4",
            RiscVRegisters::T5 => "t5",
            RiscVRegisters::T6 => "t6",
        }
    }

    pub fn name_from_usize(value: usize) -> Option<&'static str> {
        match value {
            0 => Some("zero"),
            1 => Some("ra"),
            2 => Some("sp"),
            3 => Some("gp"),
            4 => Some("tp"),
            5 => Some("t0"),
            6 => Some("t1"),
            7 => Some("t2"),
            8 => Some("s0"),
            9 => Some("s1"),
            10 => Some("a0"),
            11 => Some("a1"),
            12 => Some("a2"),
            13 => Some("a3"),
            14 => Some("a4"),
            15 => Some("a5"),
            16 => Some("a6"),
            17 => Some("a7"),
            18 => Some("s2"),
            19 => Some("s3"),
            20 => Some("s4"),
            21 => Some("s5"),
            22 => Some("s6"),
            23 => Some("s7"),
            24 => Some("s8"),
            25 => Some("s9"),
            26 => Some("s10"),
            27 => Some("s11"),
            28 => Some("t3"),
            29 => Some("t4"),
            30 => Some("t5"),
            31 => Some("t6"),
            _ => None,
        }
    }
}
