[package]
name = "zisk-precompiles"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[dependencies]
precompiles-common = { path = "../common" }
precomp-keccakf = { path = "../keccakf" }
precomp-arith-eq = { path = "../arith_eq" }