[package]
name = "precomp-evm"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[[bin]]
name = "jump_dest_bitmap_table_gen"
path = "src/jump_dest_bitmap_table_gen.rs"

[dependencies]
fields = { workspace = true, features = ["proofman-starks-lib-c"] }
proofman-common = { workspace = true }
clap = { workspace = true }
precompiles-helpers = { workspace = true }
zisk-pil = { workspace = true }
pil-std-lib = { workspace = true }
zisk-common = { workspace = true }
zisk-core = { workspace = true }
precompiles-common = { workspace = true }
