[package]
name = "sm-binary-64"
version = "0.1.0"
edition = "2021"

[dependencies]
zisk-core = { path = "../../core" }
sm-common = { path = "../common" }

proofman-common = { workspace = true }
proofman = { workspace = true }
witness-helpers = { workspace = true }
p3-field = { workspace = true }

log = { version = "0.4", default-features = false }
rayon = "1.10.0"
