//! Standard zkVM accelerator functions implementing the C interface from zkvm_accelerators.h.
//!
//! These functions implement the standard interface defined in:
//! https://github.com/eth-act/zkvm-standards/tree/main/standards/c-interface-accelerators
//!
//! The types used in the function signatures are generated by bindgen from
//! zkvm_accelerators.h, ensuring ABI and API compatibility with the C header.
#![allow(clippy::missing_safety_doc)]
use super::{bls12_381, bn254};
use zkvm_interface::{
    zkvm_blake2f_message, zkvm_blake2f_offset, zkvm_blake2f_state, zkvm_bls12_381_fp,
    zkvm_bls12_381_fp2, zkvm_bls12_381_g1_msm_pair, zkvm_bls12_381_g1_point,
    zkvm_bls12_381_g2_msm_pair, zkvm_bls12_381_g2_point, zkvm_bls12_381_pairing_pair,
    zkvm_bn254_g1_point, zkvm_bn254_pairing_pair, zkvm_bn254_scalar, zkvm_keccak256_hash,
    zkvm_kzg_commitment, zkvm_kzg_field_element, zkvm_kzg_proof, zkvm_ripemd160_hash,
    zkvm_secp256k1_hash, zkvm_secp256k1_pubkey, zkvm_secp256k1_signature, zkvm_secp256r1_hash,
    zkvm_secp256r1_pubkey, zkvm_secp256r1_signature, zkvm_sha256_hash, zkvm_status,
    zkvm_status_ZKVM_EFAIL as ZKVM_EFAIL, zkvm_status_ZKVM_EOK as ZKVM_EOK,
};

#[cfg_attr(not(feature = "hints"), no_mangle)]
#[cfg_attr(feature = "hints", export_name = "hints_zkvm_keccak256")]
pub unsafe extern "C" fn zkvm_keccak256(
    data: *const u8,
    len: usize,
    output: *mut zkvm_keccak256_hash,
    #[cfg(feature = "hints")] hints: &mut Vec<u64>,
) -> zkvm_status {
    super::keccak256_c(
        data,
        len,
        (*output).data.as_mut_ptr(),
        #[cfg(feature = "hints")]
        hints,
    );
    ZKVM_EOK
}

#[cfg_attr(not(feature = "hints"), no_mangle)]
#[cfg_attr(feature = "hints", export_name = "hints_zkvm_sha256")]
pub unsafe extern "C" fn zkvm_sha256(
    data: *const u8,
    len: usize,
    output: *mut zkvm_sha256_hash,
    #[cfg(feature = "hints")] hints: &mut Vec<u64>,
) -> zkvm_status {
    super::sha256_c(
        data,
        len,
        (*output).data.as_mut_ptr(),
        #[cfg(feature = "hints")]
        hints,
    );
    ZKVM_EOK
}

#[cfg_attr(not(feature = "hints"), no_mangle)]
#[cfg_attr(feature = "hints", export_name = "hints_zkvm_ripemd160")]
pub unsafe extern "C" fn zkvm_ripemd160(
    data: *const u8,
    len: usize,
    output: *mut zkvm_ripemd160_hash,
    #[cfg(feature = "hints")] hints: &mut Vec<u64>,
) -> zkvm_status {
    super::ripemd160_c(
        data,
        len,
        (*output).data.as_mut_ptr(),
        #[cfg(feature = "hints")]
        hints,
    );
    ZKVM_EOK
}

#[cfg_attr(not(feature = "hints"), no_mangle)]
#[cfg_attr(feature = "hints", export_name = "hints_zkvm_modexp")]
pub unsafe extern "C" fn zkvm_modexp(
    base: *const u8,
    base_len: usize,
    exp: *const u8,
    exp_len: usize,
    modulus: *const u8,
    mod_len: usize,
    output: *mut u8,
    #[cfg(feature = "hints")] hints: &mut Vec<u64>,
) -> zkvm_status {
    super::modexp_bytes_c(
        base,
        base_len,
        exp,
        exp_len,
        modulus,
        mod_len,
        output,
        #[cfg(feature = "hints")]
        hints,
    );
    ZKVM_EOK
}

#[cfg_attr(not(feature = "hints"), no_mangle)]
#[cfg_attr(feature = "hints", export_name = "hints_zkvm_bn254_g1_add")]
pub unsafe extern "C" fn zkvm_bn254_g1_add(
    p1: *const zkvm_bn254_g1_point,
    p2: *const zkvm_bn254_g1_point,
    result: *mut zkvm_bn254_g1_point,
    #[cfg(feature = "hints")] hints: &mut Vec<u64>,
) -> zkvm_status {
    let ret = super::bn254_g1_add_c(
        (*p1).data.as_ptr(),
        (*p2).data.as_ptr(),
        (*result).data.as_mut_ptr(),
        #[cfg(feature = "hints")]
        hints,
    );
    if matches!(ret, bn254::G1_ADD_SUCCESS | bn254::G1_ADD_SUCCESS_INFINITY) {
        ZKVM_EOK
    } else {
        ZKVM_EFAIL
    }
}

#[cfg_attr(not(feature = "hints"), no_mangle)]
#[cfg_attr(feature = "hints", export_name = "hints_zkvm_bn254_g1_mul")]
pub unsafe extern "C" fn zkvm_bn254_g1_mul(
    point: *const zkvm_bn254_g1_point,
    scalar: *const zkvm_bn254_scalar,
    result: *mut zkvm_bn254_g1_point,
    #[cfg(feature = "hints")] hints: &mut Vec<u64>,
) -> zkvm_status {
    let ret = super::bn254_g1_mul_c(
        (*point).data.as_ptr(),
        (*scalar).data.as_ptr(),
        (*result).data.as_mut_ptr(),
        #[cfg(feature = "hints")]
        hints,
    );
    if matches!(ret, bn254::G1_MUL_SUCCESS | bn254::G1_MUL_SUCCESS_INFINITY) {
        ZKVM_EOK
    } else {
        ZKVM_EFAIL
    }
}

#[cfg_attr(not(feature = "hints"), no_mangle)]
#[cfg_attr(feature = "hints", export_name = "hints_zkvm_bn254_pairing")]
pub unsafe extern "C" fn zkvm_bn254_pairing(
    pairs: *const zkvm_bn254_pairing_pair,
    num_pairs: usize,
    verified: *mut bool,
    #[cfg(feature = "hints")] hints: &mut Vec<u64>,
) -> zkvm_status {
    let ret = super::bn254_pairing_check_c(
        pairs as *const u8,
        num_pairs,
        #[cfg(feature = "hints")]
        hints,
    );
    match ret {
        bn254::PAIRING_CHECK_SUCCESS => {
            *verified = true;
            ZKVM_EOK
        }
        bn254::PAIRING_CHECK_FAILED => {
            *verified = false;
            ZKVM_EOK
        }
        _ => ZKVM_EFAIL,
    }
}

#[cfg_attr(not(feature = "hints"), no_mangle)]
#[cfg_attr(feature = "hints", export_name = "hints_zkvm_blake2f")]
pub unsafe extern "C" fn zkvm_blake2f(
    rounds: u32,
    h: *mut zkvm_blake2f_state,
    m: *const zkvm_blake2f_message,
    t: *const zkvm_blake2f_offset,
    f: u8,
    #[cfg(feature = "hints")] hints: &mut Vec<u64>,
) -> zkvm_status {
    super::blake2b_compress_c(
        rounds,
        (*h).data.as_mut_ptr() as *mut u64,
        (*m).data.as_ptr() as *const u64,
        (*t).data.as_ptr() as *const u64,
        f,
        #[cfg(feature = "hints")]
        hints,
    );
    ZKVM_EOK
}

#[cfg_attr(not(feature = "hints"), no_mangle)]
#[cfg_attr(feature = "hints", export_name = "hints_zkvm_kzg_point_eval")]
pub unsafe extern "C" fn zkvm_kzg_point_eval(
    commitment: *const zkvm_kzg_commitment,
    z: *const zkvm_kzg_field_element,
    y: *const zkvm_kzg_field_element,
    proof: *const zkvm_kzg_proof,
    verified: *mut bool,
    #[cfg(feature = "hints")] hints: &mut Vec<u64>,
) -> zkvm_status {
    // verify_kzg_proof_c takes (z, y, commitment, proof)
    *verified = super::verify_kzg_proof_c(
        (*z).data.as_ptr(),
        (*y).data.as_ptr(),
        (*commitment).data.as_ptr(),
        (*proof).data.as_ptr(),
        #[cfg(feature = "hints")]
        hints,
    );
    ZKVM_EOK
}

#[cfg_attr(not(feature = "hints"), no_mangle)]
#[cfg_attr(feature = "hints", export_name = "hints_zkvm_bls12_g1_add")]
pub unsafe extern "C" fn zkvm_bls12_g1_add(
    p1: *const zkvm_bls12_381_g1_point,
    p2: *const zkvm_bls12_381_g1_point,
    result: *mut zkvm_bls12_381_g1_point,
    #[cfg(feature = "hints")] hints: &mut Vec<u64>,
) -> zkvm_status {
    let ret = super::bls12_381_g1_add_c(
        (*result).data.as_mut_ptr(),
        (*p1).data.as_ptr(),
        (*p2).data.as_ptr(),
        #[cfg(feature = "hints")]
        hints,
    );
    if matches!(ret, bls12_381::G1_ADD_SUCCESS | bls12_381::G1_ADD_SUCCESS_INFINITY) {
        ZKVM_EOK
    } else {
        ZKVM_EFAIL
    }
}

#[cfg_attr(not(feature = "hints"), no_mangle)]
#[cfg_attr(feature = "hints", export_name = "hints_zkvm_bls12_g1_msm")]
pub unsafe extern "C" fn zkvm_bls12_g1_msm(
    pairs: *const zkvm_bls12_381_g1_msm_pair,
    num_pairs: usize,
    result: *mut zkvm_bls12_381_g1_point,
    #[cfg(feature = "hints")] hints: &mut Vec<u64>,
) -> zkvm_status {
    let ret = super::bls12_381_g1_msm_c(
        (*result).data.as_mut_ptr(),
        pairs as *const u8,
        num_pairs,
        #[cfg(feature = "hints")]
        hints,
    );
    if matches!(ret, bls12_381::G1_MSM_SUCCESS | bls12_381::G1_MSM_SUCCESS_INFINITY) {
        ZKVM_EOK
    } else {
        ZKVM_EFAIL
    }
}

#[cfg_attr(not(feature = "hints"), no_mangle)]
#[cfg_attr(feature = "hints", export_name = "hints_zkvm_bls12_g2_add")]
pub unsafe extern "C" fn zkvm_bls12_g2_add(
    p1: *const zkvm_bls12_381_g2_point,
    p2: *const zkvm_bls12_381_g2_point,
    result: *mut zkvm_bls12_381_g2_point,
    #[cfg(feature = "hints")] hints: &mut Vec<u64>,
) -> zkvm_status {
    let ret = super::bls12_381_g2_add_c(
        (*result).data.as_mut_ptr(),
        (*p1).data.as_ptr(),
        (*p2).data.as_ptr(),
        #[cfg(feature = "hints")]
        hints,
    );
    if matches!(ret, bls12_381::G2_ADD_SUCCESS | bls12_381::G2_ADD_SUCCESS_INFINITY) {
        ZKVM_EOK
    } else {
        ZKVM_EFAIL
    }
}

#[cfg_attr(not(feature = "hints"), no_mangle)]
#[cfg_attr(feature = "hints", export_name = "hints_zkvm_bls12_g2_msm")]
pub unsafe extern "C" fn zkvm_bls12_g2_msm(
    pairs: *const zkvm_bls12_381_g2_msm_pair,
    num_pairs: usize,
    result: *mut zkvm_bls12_381_g2_point,
    #[cfg(feature = "hints")] hints: &mut Vec<u64>,
) -> zkvm_status {
    let ret = super::bls12_381_g2_msm_c(
        (*result).data.as_mut_ptr(),
        pairs as *const u8,
        num_pairs,
        #[cfg(feature = "hints")]
        hints,
    );
    if matches!(ret, bls12_381::G2_MSM_SUCCESS | bls12_381::G2_MSM_SUCCESS_INFINITY) {
        ZKVM_EOK
    } else {
        ZKVM_EFAIL
    }
}

#[cfg_attr(not(feature = "hints"), no_mangle)]
#[cfg_attr(feature = "hints", export_name = "hints_zkvm_bls12_pairing")]
pub unsafe extern "C" fn zkvm_bls12_pairing(
    pairs: *const zkvm_bls12_381_pairing_pair,
    num_pairs: usize,
    verified: *mut bool,
    #[cfg(feature = "hints")] hints: &mut Vec<u64>,
) -> zkvm_status {
    let ret = super::bls12_381_pairing_check_c(
        pairs as *const u8,
        num_pairs,
        #[cfg(feature = "hints")]
        hints,
    );
    match ret {
        bls12_381::PAIRING_CHECK_SUCCESS => {
            *verified = true;
            ZKVM_EOK
        }
        bls12_381::PAIRING_CHECK_FAILED => {
            *verified = false;
            ZKVM_EOK
        }
        _ => ZKVM_EFAIL,
    }
}

#[cfg_attr(not(feature = "hints"), no_mangle)]
#[cfg_attr(feature = "hints", export_name = "hints_zkvm_bls12_map_fp_to_g1")]
pub unsafe extern "C" fn zkvm_bls12_map_fp_to_g1(
    field_element: *const zkvm_bls12_381_fp,
    result: *mut zkvm_bls12_381_g1_point,
    #[cfg(feature = "hints")] hints: &mut Vec<u64>,
) -> zkvm_status {
    let ret = super::bls12_381_fp_to_g1_c(
        (*result).data.as_mut_ptr(),
        (*field_element).data.as_ptr(),
        #[cfg(feature = "hints")]
        hints,
    );
    if ret == bls12_381::FP_TO_G1_SUCCESS {
        ZKVM_EOK
    } else {
        ZKVM_EFAIL
    }
}

#[cfg_attr(not(feature = "hints"), no_mangle)]
#[cfg_attr(feature = "hints", export_name = "hints_zkvm_bls12_map_fp2_to_g2")]
pub unsafe extern "C" fn zkvm_bls12_map_fp2_to_g2(
    field_element: *const zkvm_bls12_381_fp2,
    result: *mut zkvm_bls12_381_g2_point,
    #[cfg(feature = "hints")] hints: &mut Vec<u64>,
) -> zkvm_status {
    let ret = super::bls12_381_fp2_to_g2_c(
        (*result).data.as_mut_ptr(),
        (*field_element).data.as_ptr(),
        #[cfg(feature = "hints")]
        hints,
    );
    if ret == bls12_381::FP2_TO_G2_SUCCESS {
        ZKVM_EOK
    } else {
        ZKVM_EFAIL
    }
}

#[cfg_attr(not(feature = "hints"), no_mangle)]
#[cfg_attr(feature = "hints", export_name = "hints_zkvm_secp256r1_verify")]
pub unsafe extern "C" fn zkvm_secp256r1_verify(
    msg: *const zkvm_secp256r1_hash,
    sig: *const zkvm_secp256r1_signature,
    pubkey: *const zkvm_secp256r1_pubkey,
    verified: *mut bool,
    #[cfg(feature = "hints")] hints: &mut Vec<u64>,
) -> zkvm_status {
    *verified = super::secp256r1_ecdsa_verify_c(
        (*msg).data.as_ptr(),
        (*sig).data.as_ptr(),
        (*pubkey).data.as_ptr(),
        #[cfg(feature = "hints")]
        hints,
    );
    ZKVM_EOK
}

#[cfg_attr(not(feature = "hints"), no_mangle)]
#[cfg_attr(feature = "hints", export_name = "hints_zkvm_secp256k1_verify")]
pub unsafe extern "C" fn zkvm_secp256k1_verify(
    msg: *const zkvm_secp256k1_hash,
    sig: *const zkvm_secp256k1_signature,
    pubkey: *const zkvm_secp256k1_pubkey,
    verified: *mut bool,
    #[cfg(feature = "hints")] hints: &mut Vec<u64>,
) -> zkvm_status {
    *verified = super::secp256k1_ecdsa_verify_c(
        sig as *const u8,
        msg as *const u8,
        pubkey as *const u8,
        #[cfg(feature = "hints")]
        hints,
    );

    ZKVM_EOK
}

#[cfg_attr(not(feature = "hints"), no_mangle)]
#[cfg_attr(feature = "hints", export_name = "hints_zkvm_secp256k1_ecrecover")]
pub unsafe extern "C" fn zkvm_secp256k1_ecrecover(
    msg: *const zkvm_secp256k1_hash,
    sig: *const zkvm_secp256k1_signature,
    recid: u8,
    output: *mut zkvm_secp256k1_pubkey,
    #[cfg(feature = "hints")] hints: &mut Vec<u64>,
) -> zkvm_status {
    let ret = super::secp256k1_ecdsa_recover_c(
        sig as *const u8,
        recid,
        msg as *const u8,
        output as *mut u8,
        #[cfg(feature = "hints")]
        hints,
    );

    if ret == super::ECDSA_RECOVER_SUCCESS {
        ZKVM_EOK
    } else {
        ZKVM_EFAIL
    }
}

// ---------------------------------------------------------------------------
// Compile-time interface checks: verify our implementations match the C header.
//
// Each `let _ = [bindings::zkvm_foo, super::zkvm_foo]` puts the bindgen-generated
// declaration and our implementation into an array. Rust infers the element type
// from the generated declaration and then checks that our implementation coerces
// to the same type. This catches both name mismatches (if `bindings::zkvm_foo`
// doesn't exist) and signature mismatches (if the parameter or return types differ).
// No types are written manually here — they are all derived from the generated source.
//
// Only applicable in the non-hints build (hints adds an extra parameter).
// ---------------------------------------------------------------------------
#[cfg(not(feature = "hints"))]
#[allow(dead_code)]
mod _interface_type_checks {
    use super::*;
    use zkvm_interface as bindings;
    fn _check() {
        let _ = [bindings::zkvm_keccak256, super::zkvm_keccak256];
        let _ = [bindings::zkvm_sha256, super::zkvm_sha256];
        let _ = [bindings::zkvm_ripemd160, super::zkvm_ripemd160];
        let _ = [bindings::zkvm_modexp, super::zkvm_modexp];
        let _ = [bindings::zkvm_bn254_g1_add, super::zkvm_bn254_g1_add];
        let _ = [bindings::zkvm_bn254_g1_mul, super::zkvm_bn254_g1_mul];
        let _ = [bindings::zkvm_bn254_pairing, super::zkvm_bn254_pairing];
        let _ = [bindings::zkvm_blake2f, super::zkvm_blake2f];
        let _ = [bindings::zkvm_kzg_point_eval, super::zkvm_kzg_point_eval];
        let _ = [bindings::zkvm_bls12_g1_add, super::zkvm_bls12_g1_add];
        let _ = [bindings::zkvm_bls12_g1_msm, super::zkvm_bls12_g1_msm];
        let _ = [bindings::zkvm_bls12_g2_add, super::zkvm_bls12_g2_add];
        let _ = [bindings::zkvm_bls12_g2_msm, super::zkvm_bls12_g2_msm];
        let _ = [bindings::zkvm_bls12_pairing, super::zkvm_bls12_pairing];
        let _ = [bindings::zkvm_bls12_map_fp_to_g1, super::zkvm_bls12_map_fp_to_g1];
        let _ = [bindings::zkvm_bls12_map_fp2_to_g2, super::zkvm_bls12_map_fp2_to_g2];
        let _ = [bindings::zkvm_secp256r1_verify, super::zkvm_secp256r1_verify];
        let _ = [bindings::zkvm_secp256k1_verify, super::zkvm_secp256k1_verify];
        let _ = [bindings::zkvm_secp256k1_ecrecover, super::zkvm_secp256k1_ecrecover];
    }
}
