[package]
name = "proofman-common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
serde_derive.workspace = true
log.workspace = true
transcript = { path = "../transcript" }
p3-field.workspace = true
p3-goldilocks.workspace = true
proofman-macros.workspace = true
env_logger.workspace = true
proofman-util = { path = "../util" }
proofman-starks-lib-c = { path = "../provers/starks-lib-c" }
mpi = { version = "0.8.0", optional = true }
rayon.workspace = true

[features]
default = []
no_lib_link = ["proofman-starks-lib-c/no_lib_link"]
distributed = ["dep:mpi"]
