//! Strongly-typed RISC-V instruction format (`InstType`) and mnemonic (`InstName`) enums.
//!
//! These replace the previous stringly-typed `(type, name)` pairs returned by the decoder,
//! so dispatch on instruction format / mnemonic is checked by the compiler.
//! `as_str()` / `Display` reproduce the canonical mnemonic strings for logging and text output.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum InstType {
    A,
    B,
    C,
    Ca,
    Cb,
    Ci,
    Cinvalid,
    Ciw,
    Cj,
    Cl,
    Cr,
    Cs,
    Css,
    F,
    I,
    Invalid,
    J,
    R,
    R4,
    S,
    U,
}

impl InstType {
    /// Returns the canonical RISC-V mnemonic string for this variant.
    pub fn as_str(&self) -> &'static str {
        match self {
            InstType::A => "A",
            InstType::B => "B",
            InstType::C => "C",
            InstType::Ca => "CA",
            InstType::Cb => "CB",
            InstType::Ci => "CI",
            InstType::Cinvalid => "CINVALID",
            InstType::Ciw => "CIW",
            InstType::Cj => "CJ",
            InstType::Cl => "CL",
            InstType::Cr => "CR",
            InstType::Cs => "CS",
            InstType::Css => "CSS",
            InstType::F => "F",
            InstType::I => "I",
            InstType::Invalid => "INVALID",
            InstType::J => "J",
            InstType::R => "R",
            InstType::R4 => "R4",
            InstType::S => "S",
            InstType::U => "U",
        }
    }
}

impl Default for InstType {
    fn default() -> Self { InstType::Invalid }
}

impl core::fmt::Display for InstType {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum InstName {
    Add,
    AddUw,
    Addi,
    Addiw,
    Addw,
    AmoaddD,
    AmoaddW,
    AmoandD,
    AmoandW,
    AmomaxD,
    AmomaxW,
    AmomaxuD,
    AmomaxuW,
    AmominD,
    AmominW,
    AmominuD,
    AmominuW,
    AmoorD,
    AmoorW,
    AmoswapD,
    AmoswapW,
    AmoxorD,
    AmoxorW,
    And,
    Andi,
    Andn,
    Auipc,
    Bclr,
    Bclri,
    Beq,
    Bext,
    Bexti,
    Bge,
    Bgeu,
    Binv,
    Binvi,
    Blt,
    Bltu,
    Bne,
    Brev8,
    Bset,
    Bseti,
    CAdd,
    CAddi,
    CAddi16sp,
    CAddi4spn,
    CAddiw,
    CAddw,
    CAnd,
    CAndi,
    CBeqz,
    CBnez,
    CEbreak,
    CFld,
    CFldsp,
    CFsd,
    CFsdsp,
    CHalt,
    CJ,
    CJalr,
    CJr,
    CLd,
    CLdsp,
    CLi,
    CLui,
    CLw,
    CLwsp,
    CMv,
    CNop,
    COr,
    CReserved,
    CSd,
    CSdsp,
    CSlli,
    CSrai,
    CSrli,
    CSub,
    CSubw,
    CSw,
    CSwsp,
    CXor,
    Clmul,
    Clmulh,
    Clmulr,
    Clz,
    Clzw,
    Cpop,
    Cpopw,
    Csrrc,
    Csrrci,
    Csrrs,
    Csrrsi,
    Csrrw,
    Csrrwi,
    Ctz,
    Ctzw,
    Div,
    Divu,
    Divuw,
    Divw,
    Ebreak,
    Ecall,
    FaddD,
    FaddS,
    FclassD,
    FclassS,
    FcvtDL,
    FcvtDLu,
    FcvtDS,
    FcvtDW,
    FcvtDWu,
    FcvtLD,
    FcvtLS,
    FcvtLuD,
    FcvtLuS,
    FcvtSD,
    FcvtSL,
    FcvtSLu,
    FcvtSW,
    FcvtSWu,
    FcvtWD,
    FcvtWS,
    FcvtWuD,
    FcvtWuS,
    FdivD,
    FdivS,
    Fence,
    FenceI,
    FeqD,
    FeqS,
    Fld,
    FleD,
    FleS,
    FltD,
    FltS,
    Flw,
    FmaddD,
    FmaddS,
    FmaxD,
    FmaxS,
    FminD,
    FminS,
    FmsubD,
    FmsubS,
    FmulD,
    FmulS,
    FmvDX,
    FmvWX,
    FmvXD,
    FmvXW,
    FnmaddD,
    FnmaddS,
    FnmsubD,
    FnmsubS,
    Fsd,
    FsgnjD,
    FsgnjS,
    FsgnjnD,
    FsgnjnS,
    FsgnjxD,
    FsgnjxS,
    FsqrtD,
    FsqrtS,
    FsubD,
    FsubS,
    Fsw,
    Jal,
    Jalr,
    Lb,
    Lbu,
    Ld,
    Lh,
    Lhu,
    LrD,
    LrW,
    Lui,
    Lw,
    Lwu,
    Max,
    Maxu,
    Min,
    Minu,
    Mul,
    Mulh,
    Mulhsu,
    Mulhu,
    Mulw,
    Or,
    OrcB,
    Ori,
    Orn,
    Pack,
    Packh,
    Packw,
    Rem,
    Remu,
    Remuw,
    Remw,
    Reserved,
    Rev8,
    Rol,
    Rolw,
    Ror,
    Rori,
    Roriw,
    Rorw,
    Sb,
    ScD,
    ScW,
    Sd,
    SextB,
    SextH,
    Sh,
    Sh1add,
    Sh1addUw,
    Sh2add,
    Sh2addUw,
    Sh3add,
    Sh3addUw,
    Sll,
    Slli,
    SlliUw,
    Slliw,
    Sllw,
    Slt,
    Slti,
    Sltiu,
    Sltu,
    Sra,
    Srai,
    Sraiw,
    Sraw,
    Srl,
    Srli,
    Srliw,
    Srlw,
    Sub,
    Subw,
    Sw,
    Xnor,
    Xor,
    Xori,
    Xperm4,
    Xperm8,
    ZextH,
}

impl InstName {
    /// Returns the canonical RISC-V mnemonic string for this variant.
    pub fn as_str(&self) -> &'static str {
        match self {
            InstName::Add => "add",
            InstName::AddUw => "add.uw",
            InstName::Addi => "addi",
            InstName::Addiw => "addiw",
            InstName::Addw => "addw",
            InstName::AmoaddD => "amoadd.d",
            InstName::AmoaddW => "amoadd.w",
            InstName::AmoandD => "amoand.d",
            InstName::AmoandW => "amoand.w",
            InstName::AmomaxD => "amomax.d",
            InstName::AmomaxW => "amomax.w",
            InstName::AmomaxuD => "amomaxu.d",
            InstName::AmomaxuW => "amomaxu.w",
            InstName::AmominD => "amomin.d",
            InstName::AmominW => "amomin.w",
            InstName::AmominuD => "amominu.d",
            InstName::AmominuW => "amominu.w",
            InstName::AmoorD => "amoor.d",
            InstName::AmoorW => "amoor.w",
            InstName::AmoswapD => "amoswap.d",
            InstName::AmoswapW => "amoswap.w",
            InstName::AmoxorD => "amoxor.d",
            InstName::AmoxorW => "amoxor.w",
            InstName::And => "and",
            InstName::Andi => "andi",
            InstName::Andn => "andn",
            InstName::Auipc => "auipc",
            InstName::Bclr => "bclr",
            InstName::Bclri => "bclri",
            InstName::Beq => "beq",
            InstName::Bext => "bext",
            InstName::Bexti => "bexti",
            InstName::Bge => "bge",
            InstName::Bgeu => "bgeu",
            InstName::Binv => "binv",
            InstName::Binvi => "binvi",
            InstName::Blt => "blt",
            InstName::Bltu => "bltu",
            InstName::Bne => "bne",
            InstName::Brev8 => "brev8",
            InstName::Bset => "bset",
            InstName::Bseti => "bseti",
            InstName::CAdd => "c.add",
            InstName::CAddi => "c.addi",
            InstName::CAddi16sp => "c.addi16sp",
            InstName::CAddi4spn => "c.addi4spn",
            InstName::CAddiw => "c.addiw",
            InstName::CAddw => "c.addw",
            InstName::CAnd => "c.and",
            InstName::CAndi => "c.andi",
            InstName::CBeqz => "c.beqz",
            InstName::CBnez => "c.bnez",
            InstName::CEbreak => "c.ebreak",
            InstName::CFld => "c.fld",
            InstName::CFldsp => "c.fldsp",
            InstName::CFsd => "c.fsd",
            InstName::CFsdsp => "c.fsdsp",
            InstName::CHalt => "c.halt",
            InstName::CJ => "c.j",
            InstName::CJalr => "c.jalr",
            InstName::CJr => "c.jr",
            InstName::CLd => "c.ld",
            InstName::CLdsp => "c.ldsp",
            InstName::CLi => "c.li",
            InstName::CLui => "c.lui",
            InstName::CLw => "c.lw",
            InstName::CLwsp => "c.lwsp",
            InstName::CMv => "c.mv",
            InstName::CNop => "c.nop",
            InstName::COr => "c.or",
            InstName::CReserved => "c.reserved",
            InstName::CSd => "c.sd",
            InstName::CSdsp => "c.sdsp",
            InstName::CSlli => "c.slli",
            InstName::CSrai => "c.srai",
            InstName::CSrli => "c.srli",
            InstName::CSub => "c.sub",
            InstName::CSubw => "c.subw",
            InstName::CSw => "c.sw",
            InstName::CSwsp => "c.swsp",
            InstName::CXor => "c.xor",
            InstName::Clmul => "clmul",
            InstName::Clmulh => "clmulh",
            InstName::Clmulr => "clmulr",
            InstName::Clz => "clz",
            InstName::Clzw => "clzw",
            InstName::Cpop => "cpop",
            InstName::Cpopw => "cpopw",
            InstName::Csrrc => "csrrc",
            InstName::Csrrci => "csrrci",
            InstName::Csrrs => "csrrs",
            InstName::Csrrsi => "csrrsi",
            InstName::Csrrw => "csrrw",
            InstName::Csrrwi => "csrrwi",
            InstName::Ctz => "ctz",
            InstName::Ctzw => "ctzw",
            InstName::Div => "div",
            InstName::Divu => "divu",
            InstName::Divuw => "divuw",
            InstName::Divw => "divw",
            InstName::Ebreak => "ebreak",
            InstName::Ecall => "ecall",
            InstName::FaddD => "fadd.d",
            InstName::FaddS => "fadd.s",
            InstName::FclassD => "fclass.d",
            InstName::FclassS => "fclass.s",
            InstName::FcvtDL => "fcvt.d.l",
            InstName::FcvtDLu => "fcvt.d.lu",
            InstName::FcvtDS => "fcvt.d.s",
            InstName::FcvtDW => "fcvt.d.w",
            InstName::FcvtDWu => "fcvt.d.wu",
            InstName::FcvtLD => "fcvt.l.d",
            InstName::FcvtLS => "fcvt.l.s",
            InstName::FcvtLuD => "fcvt.lu.d",
            InstName::FcvtLuS => "fcvt.lu.s",
            InstName::FcvtSD => "fcvt.s.d",
            InstName::FcvtSL => "fcvt.s.l",
            InstName::FcvtSLu => "fcvt.s.lu",
            InstName::FcvtSW => "fcvt.s.w",
            InstName::FcvtSWu => "fcvt.s.wu",
            InstName::FcvtWD => "fcvt.w.d",
            InstName::FcvtWS => "fcvt.w.s",
            InstName::FcvtWuD => "fcvt.wu.d",
            InstName::FcvtWuS => "fcvt.wu.s",
            InstName::FdivD => "fdiv.d",
            InstName::FdivS => "fdiv.s",
            InstName::Fence => "fence",
            InstName::FenceI => "fence.i",
            InstName::FeqD => "feq.d",
            InstName::FeqS => "feq.s",
            InstName::Fld => "fld",
            InstName::FleD => "fle.d",
            InstName::FleS => "fle.s",
            InstName::FltD => "flt.d",
            InstName::FltS => "flt.s",
            InstName::Flw => "flw",
            InstName::FmaddD => "fmadd.d",
            InstName::FmaddS => "fmadd.s",
            InstName::FmaxD => "fmax.d",
            InstName::FmaxS => "fmax.s",
            InstName::FminD => "fmin.d",
            InstName::FminS => "fmin.s",
            InstName::FmsubD => "fmsub.d",
            InstName::FmsubS => "fmsub.s",
            InstName::FmulD => "fmul.d",
            InstName::FmulS => "fmul.s",
            InstName::FmvDX => "fmv.d.x",
            InstName::FmvWX => "fmv.w.x",
            InstName::FmvXD => "fmv.x.d",
            InstName::FmvXW => "fmv.x.w",
            InstName::FnmaddD => "fnmadd.d",
            InstName::FnmaddS => "fnmadd.s",
            InstName::FnmsubD => "fnmsub.d",
            InstName::FnmsubS => "fnmsub.s",
            InstName::Fsd => "fsd",
            InstName::FsgnjD => "fsgnj.d",
            InstName::FsgnjS => "fsgnj.s",
            InstName::FsgnjnD => "fsgnjn.d",
            InstName::FsgnjnS => "fsgnjn.s",
            InstName::FsgnjxD => "fsgnjx.d",
            InstName::FsgnjxS => "fsgnjx.s",
            InstName::FsqrtD => "fsqrt.d",
            InstName::FsqrtS => "fsqrt.s",
            InstName::FsubD => "fsub.d",
            InstName::FsubS => "fsub.s",
            InstName::Fsw => "fsw",
            InstName::Jal => "jal",
            InstName::Jalr => "jalr",
            InstName::Lb => "lb",
            InstName::Lbu => "lbu",
            InstName::Ld => "ld",
            InstName::Lh => "lh",
            InstName::Lhu => "lhu",
            InstName::LrD => "lr.d",
            InstName::LrW => "lr.w",
            InstName::Lui => "lui",
            InstName::Lw => "lw",
            InstName::Lwu => "lwu",
            InstName::Max => "max",
            InstName::Maxu => "maxu",
            InstName::Min => "min",
            InstName::Minu => "minu",
            InstName::Mul => "mul",
            InstName::Mulh => "mulh",
            InstName::Mulhsu => "mulhsu",
            InstName::Mulhu => "mulhu",
            InstName::Mulw => "mulw",
            InstName::Or => "or",
            InstName::OrcB => "orc.b",
            InstName::Ori => "ori",
            InstName::Orn => "orn",
            InstName::Pack => "pack",
            InstName::Packh => "packh",
            InstName::Packw => "packw",
            InstName::Rem => "rem",
            InstName::Remu => "remu",
            InstName::Remuw => "remuw",
            InstName::Remw => "remw",
            InstName::Reserved => "reserved",
            InstName::Rev8 => "rev8",
            InstName::Rol => "rol",
            InstName::Rolw => "rolw",
            InstName::Ror => "ror",
            InstName::Rori => "rori",
            InstName::Roriw => "roriw",
            InstName::Rorw => "rorw",
            InstName::Sb => "sb",
            InstName::ScD => "sc.d",
            InstName::ScW => "sc.w",
            InstName::Sd => "sd",
            InstName::SextB => "sext.b",
            InstName::SextH => "sext.h",
            InstName::Sh => "sh",
            InstName::Sh1add => "sh1add",
            InstName::Sh1addUw => "sh1add.uw",
            InstName::Sh2add => "sh2add",
            InstName::Sh2addUw => "sh2add.uw",
            InstName::Sh3add => "sh3add",
            InstName::Sh3addUw => "sh3add.uw",
            InstName::Sll => "sll",
            InstName::Slli => "slli",
            InstName::SlliUw => "slli.uw",
            InstName::Slliw => "slliw",
            InstName::Sllw => "sllw",
            InstName::Slt => "slt",
            InstName::Slti => "slti",
            InstName::Sltiu => "sltiu",
            InstName::Sltu => "sltu",
            InstName::Sra => "sra",
            InstName::Srai => "srai",
            InstName::Sraiw => "sraiw",
            InstName::Sraw => "sraw",
            InstName::Srl => "srl",
            InstName::Srli => "srli",
            InstName::Srliw => "srliw",
            InstName::Srlw => "srlw",
            InstName::Sub => "sub",
            InstName::Subw => "subw",
            InstName::Sw => "sw",
            InstName::Xnor => "xnor",
            InstName::Xor => "xor",
            InstName::Xori => "xori",
            InstName::Xperm4 => "xperm4",
            InstName::Xperm8 => "xperm8",
            InstName::ZextH => "zext.h",
        }
    }
}

impl Default for InstName {
    fn default() -> Self { InstName::Reserved }
}

impl core::fmt::Display for InstName {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}
