//! Strongly-typed RISC-V instruction mnemonic (`RiscvInstName`) enum.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum RiscvInstName {
    Add,
    AddUw,
    Addi,
    Addiw,
    Addw,
    AmoaddD,
    AmoaddW,
    AmoandD,
    AmoandW,
    AmomaxD,
    AmomaxW,
    AmomaxuD,
    AmomaxuW,
    AmominD,
    AmominW,
    AmominuD,
    AmominuW,
    AmoorD,
    AmoorW,
    AmoswapD,
    AmoswapW,
    AmoxorD,
    AmoxorW,
    And,
    Andi,
    Andn,
    Auipc,
    Bclr,
    Bclri,
    Beq,
    Bext,
    Bexti,
    Bge,
    Bgeu,
    Binv,
    Binvi,
    Blt,
    Bltu,
    Bne,
    Brev8,
    Bset,
    Bseti,
    CAdd,
    CAddi,
    CAddi16sp,
    CAddi4spn,
    CAddiw,
    CAddw,
    CAnd,
    CAndi,
    CBeqz,
    CBnez,
    CEbreak,
    CFld,
    CFldsp,
    CFsd,
    CFsdsp,
    CHalt,
    CJ,
    CJalr,
    CJr,
    CLd,
    CLdsp,
    CLi,
    CLui,
    CLw,
    CLwsp,
    CMv,
    CNop,
    COr,
    CReserved,
    CSd,
    CSdsp,
    CSlli,
    CSrai,
    CSrli,
    CSub,
    CSubw,
    CSw,
    CSwsp,
    CXor,
    Clmul,
    Clmulh,
    Clmulr,
    Clz,
    Clzw,
    Cpop,
    Cpopw,
    Csrrc,
    Csrrci,
    Csrrs,
    Csrrsi,
    Csrrw,
    Csrrwi,
    Ctz,
    Ctzw,
    Div,
    Divu,
    Divuw,
    Divw,
    Ebreak,
    Ecall,
    FaddD,
    FaddS,
    FclassD,
    FclassS,
    FcvtDL,
    FcvtDLu,
    FcvtDS,
    FcvtDW,
    FcvtDWu,
    FcvtLD,
    FcvtLS,
    FcvtLuD,
    FcvtLuS,
    FcvtSD,
    FcvtSL,
    FcvtSLu,
    FcvtSW,
    FcvtSWu,
    FcvtWD,
    FcvtWS,
    FcvtWuD,
    FcvtWuS,
    FdivD,
    FdivS,
    Fence,
    FenceI,
    FeqD,
    FeqS,
    Fld,
    FleD,
    FleS,
    FltD,
    FltS,
    Flw,
    FmaddD,
    FmaddS,
    FmaxD,
    FmaxS,
    FminD,
    FminS,
    FmsubD,
    FmsubS,
    FmulD,
    FmulS,
    FmvDX,
    FmvWX,
    FmvXD,
    FmvXW,
    FnmaddD,
    FnmaddS,
    FnmsubD,
    FnmsubS,
    Fsd,
    FsgnjD,
    FsgnjS,
    FsgnjnD,
    FsgnjnS,
    FsgnjxD,
    FsgnjxS,
    FsqrtD,
    FsqrtS,
    FsubD,
    FsubS,
    Fsw,
    Jal,
    Jalr,
    Lb,
    Lbu,
    Ld,
    Lh,
    Lhu,
    LrD,
    LrW,
    Lui,
    Lw,
    Lwu,
    Max,
    Maxu,
    Min,
    Minu,
    Mul,
    Mulh,
    Mulhsu,
    Mulhu,
    Mulw,
    Or,
    OrcB,
    Ori,
    Orn,
    Pack,
    Packh,
    Packw,
    Rem,
    Remu,
    Remuw,
    Remw,
    #[default]
    Reserved,
    Rev8,
    Rol,
    Rolw,
    Ror,
    Rori,
    Roriw,
    Rorw,
    Sb,
    ScD,
    ScW,
    Sd,
    SextB,
    SextH,
    Sh,
    Sh1add,
    Sh1addUw,
    Sh2add,
    Sh2addUw,
    Sh3add,
    Sh3addUw,
    Sll,
    Slli,
    SlliUw,
    Slliw,
    Sllw,
    Slt,
    Slti,
    Sltiu,
    Sltu,
    Sra,
    Srai,
    Sraiw,
    Sraw,
    Srl,
    Srli,
    Srliw,
    Srlw,
    Sub,
    Subw,
    Sw,
    Xnor,
    Xor,
    Xori,
    Xperm4,
    Xperm8,
    ZextH,
}

impl RiscvInstName {
    /// Returns the canonical RISC-V mnemonic string for this variant.
    pub fn as_str(&self) -> &'static str {
        match self {
            RiscvInstName::Add => "add",
            RiscvInstName::AddUw => "add.uw",
            RiscvInstName::Addi => "addi",
            RiscvInstName::Addiw => "addiw",
            RiscvInstName::Addw => "addw",
            RiscvInstName::AmoaddD => "amoadd.d",
            RiscvInstName::AmoaddW => "amoadd.w",
            RiscvInstName::AmoandD => "amoand.d",
            RiscvInstName::AmoandW => "amoand.w",
            RiscvInstName::AmomaxD => "amomax.d",
            RiscvInstName::AmomaxW => "amomax.w",
            RiscvInstName::AmomaxuD => "amomaxu.d",
            RiscvInstName::AmomaxuW => "amomaxu.w",
            RiscvInstName::AmominD => "amomin.d",
            RiscvInstName::AmominW => "amomin.w",
            RiscvInstName::AmominuD => "amominu.d",
            RiscvInstName::AmominuW => "amominu.w",
            RiscvInstName::AmoorD => "amoor.d",
            RiscvInstName::AmoorW => "amoor.w",
            RiscvInstName::AmoswapD => "amoswap.d",
            RiscvInstName::AmoswapW => "amoswap.w",
            RiscvInstName::AmoxorD => "amoxor.d",
            RiscvInstName::AmoxorW => "amoxor.w",
            RiscvInstName::And => "and",
            RiscvInstName::Andi => "andi",
            RiscvInstName::Andn => "andn",
            RiscvInstName::Auipc => "auipc",
            RiscvInstName::Bclr => "bclr",
            RiscvInstName::Bclri => "bclri",
            RiscvInstName::Beq => "beq",
            RiscvInstName::Bext => "bext",
            RiscvInstName::Bexti => "bexti",
            RiscvInstName::Bge => "bge",
            RiscvInstName::Bgeu => "bgeu",
            RiscvInstName::Binv => "binv",
            RiscvInstName::Binvi => "binvi",
            RiscvInstName::Blt => "blt",
            RiscvInstName::Bltu => "bltu",
            RiscvInstName::Bne => "bne",
            RiscvInstName::Brev8 => "brev8",
            RiscvInstName::Bset => "bset",
            RiscvInstName::Bseti => "bseti",
            RiscvInstName::CAdd => "c.add",
            RiscvInstName::CAddi => "c.addi",
            RiscvInstName::CAddi16sp => "c.addi16sp",
            RiscvInstName::CAddi4spn => "c.addi4spn",
            RiscvInstName::CAddiw => "c.addiw",
            RiscvInstName::CAddw => "c.addw",
            RiscvInstName::CAnd => "c.and",
            RiscvInstName::CAndi => "c.andi",
            RiscvInstName::CBeqz => "c.beqz",
            RiscvInstName::CBnez => "c.bnez",
            RiscvInstName::CEbreak => "c.ebreak",
            RiscvInstName::CFld => "c.fld",
            RiscvInstName::CFldsp => "c.fldsp",
            RiscvInstName::CFsd => "c.fsd",
            RiscvInstName::CFsdsp => "c.fsdsp",
            RiscvInstName::CHalt => "c.halt",
            RiscvInstName::CJ => "c.j",
            RiscvInstName::CJalr => "c.jalr",
            RiscvInstName::CJr => "c.jr",
            RiscvInstName::CLd => "c.ld",
            RiscvInstName::CLdsp => "c.ldsp",
            RiscvInstName::CLi => "c.li",
            RiscvInstName::CLui => "c.lui",
            RiscvInstName::CLw => "c.lw",
            RiscvInstName::CLwsp => "c.lwsp",
            RiscvInstName::CMv => "c.mv",
            RiscvInstName::CNop => "c.nop",
            RiscvInstName::COr => "c.or",
            RiscvInstName::CReserved => "c.reserved",
            RiscvInstName::CSd => "c.sd",
            RiscvInstName::CSdsp => "c.sdsp",
            RiscvInstName::CSlli => "c.slli",
            RiscvInstName::CSrai => "c.srai",
            RiscvInstName::CSrli => "c.srli",
            RiscvInstName::CSub => "c.sub",
            RiscvInstName::CSubw => "c.subw",
            RiscvInstName::CSw => "c.sw",
            RiscvInstName::CSwsp => "c.swsp",
            RiscvInstName::CXor => "c.xor",
            RiscvInstName::Clmul => "clmul",
            RiscvInstName::Clmulh => "clmulh",
            RiscvInstName::Clmulr => "clmulr",
            RiscvInstName::Clz => "clz",
            RiscvInstName::Clzw => "clzw",
            RiscvInstName::Cpop => "cpop",
            RiscvInstName::Cpopw => "cpopw",
            RiscvInstName::Csrrc => "csrrc",
            RiscvInstName::Csrrci => "csrrci",
            RiscvInstName::Csrrs => "csrrs",
            RiscvInstName::Csrrsi => "csrrsi",
            RiscvInstName::Csrrw => "csrrw",
            RiscvInstName::Csrrwi => "csrrwi",
            RiscvInstName::Ctz => "ctz",
            RiscvInstName::Ctzw => "ctzw",
            RiscvInstName::Div => "div",
            RiscvInstName::Divu => "divu",
            RiscvInstName::Divuw => "divuw",
            RiscvInstName::Divw => "divw",
            RiscvInstName::Ebreak => "ebreak",
            RiscvInstName::Ecall => "ecall",
            RiscvInstName::FaddD => "fadd.d",
            RiscvInstName::FaddS => "fadd.s",
            RiscvInstName::FclassD => "fclass.d",
            RiscvInstName::FclassS => "fclass.s",
            RiscvInstName::FcvtDL => "fcvt.d.l",
            RiscvInstName::FcvtDLu => "fcvt.d.lu",
            RiscvInstName::FcvtDS => "fcvt.d.s",
            RiscvInstName::FcvtDW => "fcvt.d.w",
            RiscvInstName::FcvtDWu => "fcvt.d.wu",
            RiscvInstName::FcvtLD => "fcvt.l.d",
            RiscvInstName::FcvtLS => "fcvt.l.s",
            RiscvInstName::FcvtLuD => "fcvt.lu.d",
            RiscvInstName::FcvtLuS => "fcvt.lu.s",
            RiscvInstName::FcvtSD => "fcvt.s.d",
            RiscvInstName::FcvtSL => "fcvt.s.l",
            RiscvInstName::FcvtSLu => "fcvt.s.lu",
            RiscvInstName::FcvtSW => "fcvt.s.w",
            RiscvInstName::FcvtSWu => "fcvt.s.wu",
            RiscvInstName::FcvtWD => "fcvt.w.d",
            RiscvInstName::FcvtWS => "fcvt.w.s",
            RiscvInstName::FcvtWuD => "fcvt.wu.d",
            RiscvInstName::FcvtWuS => "fcvt.wu.s",
            RiscvInstName::FdivD => "fdiv.d",
            RiscvInstName::FdivS => "fdiv.s",
            RiscvInstName::Fence => "fence",
            RiscvInstName::FenceI => "fence.i",
            RiscvInstName::FeqD => "feq.d",
            RiscvInstName::FeqS => "feq.s",
            RiscvInstName::Fld => "fld",
            RiscvInstName::FleD => "fle.d",
            RiscvInstName::FleS => "fle.s",
            RiscvInstName::FltD => "flt.d",
            RiscvInstName::FltS => "flt.s",
            RiscvInstName::Flw => "flw",
            RiscvInstName::FmaddD => "fmadd.d",
            RiscvInstName::FmaddS => "fmadd.s",
            RiscvInstName::FmaxD => "fmax.d",
            RiscvInstName::FmaxS => "fmax.s",
            RiscvInstName::FminD => "fmin.d",
            RiscvInstName::FminS => "fmin.s",
            RiscvInstName::FmsubD => "fmsub.d",
            RiscvInstName::FmsubS => "fmsub.s",
            RiscvInstName::FmulD => "fmul.d",
            RiscvInstName::FmulS => "fmul.s",
            RiscvInstName::FmvDX => "fmv.d.x",
            RiscvInstName::FmvWX => "fmv.w.x",
            RiscvInstName::FmvXD => "fmv.x.d",
            RiscvInstName::FmvXW => "fmv.x.w",
            RiscvInstName::FnmaddD => "fnmadd.d",
            RiscvInstName::FnmaddS => "fnmadd.s",
            RiscvInstName::FnmsubD => "fnmsub.d",
            RiscvInstName::FnmsubS => "fnmsub.s",
            RiscvInstName::Fsd => "fsd",
            RiscvInstName::FsgnjD => "fsgnj.d",
            RiscvInstName::FsgnjS => "fsgnj.s",
            RiscvInstName::FsgnjnD => "fsgnjn.d",
            RiscvInstName::FsgnjnS => "fsgnjn.s",
            RiscvInstName::FsgnjxD => "fsgnjx.d",
            RiscvInstName::FsgnjxS => "fsgnjx.s",
            RiscvInstName::FsqrtD => "fsqrt.d",
            RiscvInstName::FsqrtS => "fsqrt.s",
            RiscvInstName::FsubD => "fsub.d",
            RiscvInstName::FsubS => "fsub.s",
            RiscvInstName::Fsw => "fsw",
            RiscvInstName::Jal => "jal",
            RiscvInstName::Jalr => "jalr",
            RiscvInstName::Lb => "lb",
            RiscvInstName::Lbu => "lbu",
            RiscvInstName::Ld => "ld",
            RiscvInstName::Lh => "lh",
            RiscvInstName::Lhu => "lhu",
            RiscvInstName::LrD => "lr.d",
            RiscvInstName::LrW => "lr.w",
            RiscvInstName::Lui => "lui",
            RiscvInstName::Lw => "lw",
            RiscvInstName::Lwu => "lwu",
            RiscvInstName::Max => "max",
            RiscvInstName::Maxu => "maxu",
            RiscvInstName::Min => "min",
            RiscvInstName::Minu => "minu",
            RiscvInstName::Mul => "mul",
            RiscvInstName::Mulh => "mulh",
            RiscvInstName::Mulhsu => "mulhsu",
            RiscvInstName::Mulhu => "mulhu",
            RiscvInstName::Mulw => "mulw",
            RiscvInstName::Or => "or",
            RiscvInstName::OrcB => "orc.b",
            RiscvInstName::Ori => "ori",
            RiscvInstName::Orn => "orn",
            RiscvInstName::Pack => "pack",
            RiscvInstName::Packh => "packh",
            RiscvInstName::Packw => "packw",
            RiscvInstName::Rem => "rem",
            RiscvInstName::Remu => "remu",
            RiscvInstName::Remuw => "remuw",
            RiscvInstName::Remw => "remw",
            RiscvInstName::Reserved => "reserved",
            RiscvInstName::Rev8 => "rev8",
            RiscvInstName::Rol => "rol",
            RiscvInstName::Rolw => "rolw",
            RiscvInstName::Ror => "ror",
            RiscvInstName::Rori => "rori",
            RiscvInstName::Roriw => "roriw",
            RiscvInstName::Rorw => "rorw",
            RiscvInstName::Sb => "sb",
            RiscvInstName::ScD => "sc.d",
            RiscvInstName::ScW => "sc.w",
            RiscvInstName::Sd => "sd",
            RiscvInstName::SextB => "sext.b",
            RiscvInstName::SextH => "sext.h",
            RiscvInstName::Sh => "sh",
            RiscvInstName::Sh1add => "sh1add",
            RiscvInstName::Sh1addUw => "sh1add.uw",
            RiscvInstName::Sh2add => "sh2add",
            RiscvInstName::Sh2addUw => "sh2add.uw",
            RiscvInstName::Sh3add => "sh3add",
            RiscvInstName::Sh3addUw => "sh3add.uw",
            RiscvInstName::Sll => "sll",
            RiscvInstName::Slli => "slli",
            RiscvInstName::SlliUw => "slli.uw",
            RiscvInstName::Slliw => "slliw",
            RiscvInstName::Sllw => "sllw",
            RiscvInstName::Slt => "slt",
            RiscvInstName::Slti => "slti",
            RiscvInstName::Sltiu => "sltiu",
            RiscvInstName::Sltu => "sltu",
            RiscvInstName::Sra => "sra",
            RiscvInstName::Srai => "srai",
            RiscvInstName::Sraiw => "sraiw",
            RiscvInstName::Sraw => "sraw",
            RiscvInstName::Srl => "srl",
            RiscvInstName::Srli => "srli",
            RiscvInstName::Srliw => "srliw",
            RiscvInstName::Srlw => "srlw",
            RiscvInstName::Sub => "sub",
            RiscvInstName::Subw => "subw",
            RiscvInstName::Sw => "sw",
            RiscvInstName::Xnor => "xnor",
            RiscvInstName::Xor => "xor",
            RiscvInstName::Xori => "xori",
            RiscvInstName::Xperm4 => "xperm4",
            RiscvInstName::Xperm8 => "xperm8",
            RiscvInstName::ZextH => "zext.h",
        }
    }
}

impl core::fmt::Display for RiscvInstName {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}
