//! Raw trace-authoring overrides for the unit-test executor.
//!
//! Where [`crate::unit_test_hooks`] patches individual rows *after* the SM's
//! `compute_witness` runs, a trace override *replaces* `compute_witness`
//! entirely for one AIR id: the registered closure receives the freshly
//! allocated typed trace and the planned inputs and writes the whole trace
//! itself. This is the lowest-level seam in the unit-test framework — use it
//! to author malformed or boundary-case traces and check what the
//! constraints do with them.
//!
//! Registration mirrors the hook bag: build a [`TraceOverrideBag`] with one
//! typed closure per SM marker via [`TraceOverrideBag::with`]. The SM marker
//! must have a [`DynTraceOverride`] impl (generated by
//! `zisk_common::unit_test_trace_override!`).

use std::any::Any;
use std::collections::HashMap;

use zisk_common::{TraceOverrideFn, UnitTestSm};

use crate::unit_test_targets::lookup_override_by_air_id;

/// One registered override: the user's typed closure, erased to `dyn Any`.
/// The matching [`zisk_common::DynTraceOverride`] builder (looked up by AIR
/// id) downcasts it back to the concrete `TraceOverrideFn` and runs it.
pub(crate) struct OverrideSlot {
    pub(crate) override_fn: Box<dyn Any + Send + Sync>,
}

/// A bag of per-SM raw trace-authoring overrides, keyed by AIR id.
///
/// Built via the chainable [`TraceOverrideBag::with`] method, e.g.:
///
/// ```ignore
/// TraceOverrideBag::new()
///     .with::<KeccakfSm>(|trace, _inputs| {
///         trace.buffer[0].set_step_addr(1);
///         Ok(())
///     })
/// ```
///
/// When an override is registered for an AIR id, the executor skips that
/// SM's `compute_witness` and builds the `AirInstance` from the override
/// closure instead. AIR ids without an override behave as before.
#[derive(Default)]
pub struct TraceOverrideBag {
    pub(crate) overrides: HashMap<usize /* air_id */, OverrideSlot>,
}

impl TraceOverrideBag {
    /// Create an empty override bag (no overrides registered).
    pub fn new() -> Self {
        Self { overrides: HashMap::new() }
    }

    /// Register a raw trace-authoring override for SM `S`.
    ///
    /// The closure receives the freshly allocated, zeroed typed trace
    /// (e.g. `&mut KeccakfTrace<KeccakfTraceRow<Goldilocks>>`) and the
    /// planned input chunk for that AIR instance. It writes the trace in
    /// place and returns `Ok(())`. The framework wraps the written trace
    /// into the `AirInstance`.
    ///
    /// `S` must have a `DynTraceOverride` impl (via
    /// `unit_test_trace_override!`) registered in the targets registry;
    /// otherwise this panics at registration with a clear message, since a
    /// closure with no matching builder could never be dispatched.
    ///
    /// A later `with::<S>` for the same SM replaces the earlier override
    /// (unlike hooks, overrides do not stack — there is one trace author).
    pub fn with<S, Trace>(
        mut self,
        override_fn: impl Fn(&mut Trace, &[S::Input]) -> proofman_common::ProofmanResult<()>
            + Send
            + Sync
            + 'static,
    ) -> Self
    where
        S: UnitTestSm<fields::Goldilocks>,
        Trace: 'static,
    {
        let air_id = S::air_id();

        assert!(
            lookup_override_by_air_id(air_id).is_some(),
            "TraceOverrideBag::with: no DynTraceOverride registered for air_id {air_id} \
             (SM {}). Add `unit_test_trace_override!` for this SM and register it in \
             unit_test_targets::OVERRIDE_REGISTRY.",
            S::name(),
        );

        let boxed: TraceOverrideFn<Trace, S::Input> = Box::new(override_fn);
        self.overrides.insert(air_id, OverrideSlot { override_fn: Box::new(boxed) });
        self
    }

    /// True if no overrides are registered. Used by the executor to take the
    /// normal `compute_witness` path cleanly when no override is requested.
    pub fn is_empty(&self) -> bool {
        self.overrides.is_empty()
    }
}
