[package]
name = "precomp-arith-256"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "arith_256_eqgen"
path = "src/arith_256_eqgen.rs"

[[bin]]
name = "arith_256_test"
path = "src/arith_256_test.rs"

[[bin]]
name = "arith_256_test_bigint"
path = "src/arith_256_test_bigint.rs"

[dependencies]
nom = "7"
sm-common = { path = "../../state-machines/common" }
zisk-core = { path = "../../core" }
data-bus = { path = "../../data-bus" }
zisk-pil = { path = "../../pil" }
precompiles-common = { path = "../common" }

proofman-common = { workspace = true }
proofman-macros = { workspace = true }
proofman-util = { workspace = true }
witness = { workspace = true }
pil-std-lib = { workspace = true }

p3-field = { workspace=true }
p3-goldilocks = { workspace=true }
log = { workspace = true }
rayon = { workspace = true }
num-bigint = { workspace = true }
num-traits = "0.2"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.11.1"
rustfmt-wrapper = "0.2.1"
k256 = {version = "0.13", features = ["arithmetic"] }
generic-array = "0.14"
typenum = "1.16"
ark-ff = "0.5.0"
ark-std = "0.5.0"
ark-secp256k1 = "0.5"
lazy_static = "1.4"

[features]
default = []
no_lib_link = ["proofman-common/no_lib_link"]
