//! FROPS (frequent operations) region data, shared by the state machines and the assembly
//! generator.
//!
//! A triple `(op, a, b)` that recurs enormously is cheaper to prove as one row of a fixed lookup
//! table whose multiplicity is incremented at runtime than as a fresh state-machine row. The set of
//! covered triples is described, per opcode, as a short list of boxes:
//!
//! ```text
//! a in {a_lo + i*a_stride : 0 <= i < a_count}   and   b in [b_lo, b_lo + b_count)
//! ```
//!
//! This module holds only the *shape* of that description. The actual boxes live in
//! [`crate::frops_regions`], which is generated by `frops-analyzer` from execution traces, and are
//! the single source of truth for:
//!
//! * the `*_frops.rs` predicates in the arith / binary state machines (`is_frequent_op`, `get_row`),
//! * the x86-64 counting code emitted by [`crate::frops_asm`] into the ROM-histogram assembly.
//!
//! # Row layout invariant
//!
//! Rows are grouped per opcode in ascending opcode order; within an opcode they follow box order,
//! and within a box they are row-major over `b`. [`FropsRegion::base_row`] is the row of
//! `(a_lo, b_lo)` in the *global* table, i.e. the three family tables (arith, binary basic, binary
//! extension) concatenated in that order. The per-family AIRs index their own table, so publishing a
//! global row to an AIR means subtracting that family's base (see `crate::frops_regions`).

pub use crate::frops_regions::{
    FROPS_ARITH_BASE, FROPS_BINARY_BASIC_BASE, FROPS_BINARY_EXT_BASE, FROPS_REGIONS,
    FROPS_TABLE_ROWS,
};

/// One box of a FROPS predicate. See the module documentation for the layout invariant.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct FropsRegion {
    /// Lowest covered `a`.
    pub a_lo: u64,
    /// Number of distinct covered `a` values (already accounts for the stride).
    pub a_count: u64,
    /// Spacing between consecutive covered `a` values: 1 for dense boxes, a power of two otherwise.
    pub a_stride: u64,
    /// Lowest covered `b`.
    pub b_lo: u64,
    /// Number of covered `b` values (contiguous).
    pub b_count: u64,
    /// Row of `(a_lo, b_lo)` in the global FROPS table.
    pub base_row: u64,
}

impl FropsRegion {
    /// Number of table rows this box materialises.
    pub const fn rows(&self) -> u64 {
        self.a_count * self.b_count
    }

    /// Exclusive upper bound on `a`, or `None` when the box extends up to `u64::MAX` (in which case
    /// no upper-bound test is needed).
    pub const fn a_hi(&self) -> Option<u64> {
        match (self.a_lo as u128) + (self.a_count as u128) * (self.a_stride as u128) {
            hi if hi == 1u128 << 64 => None,
            hi => Some(hi as u64),
        }
    }

    /// Exclusive upper bound on `b`, or `None` when the box extends up to `u64::MAX`.
    pub const fn b_hi(&self) -> Option<u64> {
        match self.b_lo.checked_add(self.b_count) {
            None => None,
            Some(hi) => Some(hi),
        }
    }

    /// The `a` alignment a strided box requires: `(a & (a_stride - 1)) == a_residue()`.
    pub const fn a_residue(&self) -> u64 {
        self.a_lo & (self.a_stride - 1)
    }

    /// Reference membership test. Mirrored by the generated `is_frequent_op` predicates and by the
    /// emitted assembly; the state-machine tests check all three agree.
    pub fn contains(&self, a: u64, b: u64) -> bool {
        if a < self.a_lo {
            return false;
        }
        if let Some(hi) = self.a_hi() {
            if a >= hi {
                return false;
            }
        }
        if self.a_stride > 1 && (a - self.a_lo) % self.a_stride != 0 {
            return false;
        }
        if b < self.b_lo {
            return false;
        }
        match self.b_hi() {
            Some(hi) => b < hi,
            None => true,
        }
    }

    /// Global table row of `(a, b)`. Caller must ensure [`Self::contains`].
    pub fn row(&self, a: u64, b: u64) -> u64 {
        debug_assert!(self.contains(a, b));
        self.base_row + ((a - self.a_lo) / self.a_stride) * self.b_count + (b - self.b_lo)
    }
}

/// The boxes covering `op`, in test order (cheapest / most frequent first). Empty when the opcode
/// has no frequent operations.
#[inline]
pub fn frops_regions(op: u8) -> &'static [FropsRegion] {
    FROPS_REGIONS[op as usize]
}

/// Global FROPS table row for `(op, a, b)`, or `None` when the triple is not a frequent operation.
///
/// This is the reference implementation: it is not on any hot path (the state machines use the
/// generated per-opcode predicates, the assembly uses emitted code), and exists so both of those can
/// be tested against it.
pub fn frops_row(op: u8, a: u64, b: u64) -> Option<u64> {
    frops_regions(op).iter().find(|r| r.contains(a, b)).map(|r| r.row(a, b))
}

/// Whether `(op, a, b)` is a frequent operation.
pub fn is_frop(op: u8, a: u64, b: u64) -> bool {
    frops_regions(op).iter().any(|r| r.contains(a, b))
}

/// The FROPS table multiplicity column, accumulated over executed operations: one counter per global
/// table row, exactly what the ROM-histogram assembly builds ([`crate::frops_asm`]).
///
/// This is the Rust counterpart of the assembly counting. It is used to cross-check the assembly
/// against the reference implementation, and it is what an execution path without the assembly needs
/// in order to produce the same column.
#[derive(Clone)]
pub struct FropsMultiplicity {
    rows: Vec<u64>,
    counted: u64,
}

impl Default for FropsMultiplicity {
    fn default() -> Self {
        Self::new()
    }
}

impl FropsMultiplicity {
    /// One zeroed counter per global FROPS table row. That is `FROPS_TABLE_ROWS * 8` bytes, tens of
    /// millions of rows, so build one per execution and not one per chunk.
    pub fn new() -> Self {
        Self { rows: vec![0; FROPS_TABLE_ROWS as usize], counted: 0 }
    }

    /// Counts one executed operation, and reports whether it was a frequent operation (i.e. whether
    /// it is proved by the table instead of by a state-machine row).
    #[inline]
    pub fn count(&mut self, op: u8, a: u64, b: u64) -> bool {
        match frops_row(op, a, b) {
            Some(row) => {
                self.rows[row as usize] += 1;
                self.counted += 1;
                true
            }
            None => false,
        }
    }

    /// The multiplicity column.
    pub fn rows(&self) -> &[u64] {
        &self.rows
    }

    /// How many executed operations were counted, i.e. the sum of the column.
    pub fn counted(&self) -> u64 {
        self.counted
    }
}

// =================================================================================================
// Where the multiplicity column comes from, and the debug cross-check between its two producers
// =================================================================================================

use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::OnceLock;

/// Whether the FROPS multiplicity column comes from the ROM-histogram assembly.
///
/// The column has exactly two producers — the assembly, which counts every executed operation in
/// one sequential pass on a single worker, and the state-machine collectors, which accumulate it as
/// they collect each instance on every worker. They are mutually exclusive: if both ran, every
/// multiplicity would be counted twice and the lookup argument would not balance.
///
/// The choice is a property of the whole execution rather than of any one component — every
/// collector in the process has to agree with whoever publishes the column — so it lives here as
/// process state. Set it once before witness computation starts; it is only read afterwards.
static MULTIPLICITY_FROM_ASM: AtomicBool = AtomicBool::new(false);

/// Selects the assembly as the producer of the multiplicity column. See [`MULTIPLICITY_FROM_ASM`].
pub fn set_frops_multiplicity_from_asm(from_asm: bool) {
    MULTIPLICITY_FROM_ASM.store(from_asm, Ordering::Relaxed);
}

/// Whether the multiplicity column comes from the assembly, in which case the collectors must not
/// accumulate it. Read once per collector, not per operation.
pub fn frops_multiplicity_from_asm() -> bool {
    MULTIPLICITY_FROM_ASM.load(Ordering::Relaxed)
}

/// Debug cross-check of the two producers.
///
/// The assembly's column is loaded here and every row a collector would publish is *subtracted* from
/// it, so the two kinds of disagreement are caught separately and precisely:
///
/// * a row that would go below zero is one the collectors counted and the assembly did not — caught
///   at the exact row, the moment it happens;
/// * a row still holding a count once every instance has been collected is one the assembly counted
///   and the collectors did not.
///
/// This is what makes it safe to stop accumulating in the collectors: it proves both producers see
/// the same operations over a real execution.
struct FropsCrossCheck {
    /// The assembly's column, decremented as the collectors claim rows.
    remaining: Vec<AtomicU64>,
    /// Rows the collectors claimed beyond what the assembly counted.
    overcounted: AtomicU64,
    /// The first such row, for the report.
    first_overcounted: AtomicU64,
}

static CROSS_CHECK: OnceLock<FropsCrossCheck> = OnceLock::new();
static CROSS_CHECK_ON: AtomicBool = AtomicBool::new(false);

/// No row: `first_overcounted` is only meaningful once `overcounted` is non-zero.
const NO_ROW: u64 = u64::MAX;

/// Arms the cross-check with the column the assembly produced. Idempotent per process: the column is
/// allocated once and reloaded on later calls, so it can be used across several executions.
pub fn load_frops_cross_check(asm_column: &[u64]) -> Result<(), String> {
    if asm_column.len() as u64 != FROPS_TABLE_ROWS {
        return Err(format!(
            "the assembly delivered {} counters, the in-tree table has {FROPS_TABLE_ROWS} rows",
            asm_column.len()
        ));
    }
    let check = CROSS_CHECK.get_or_init(|| FropsCrossCheck {
        remaining: (0..FROPS_TABLE_ROWS).map(|_| AtomicU64::new(0)).collect(),
        overcounted: AtomicU64::new(0),
        first_overcounted: AtomicU64::new(NO_ROW),
    });
    for (slot, &count) in check.remaining.iter().zip(asm_column) {
        slot.store(count, Ordering::Relaxed);
    }
    check.overcounted.store(0, Ordering::Relaxed);
    check.first_overcounted.store(NO_ROW, Ordering::Relaxed);
    CROSS_CHECK_ON.store(true, Ordering::Relaxed);
    Ok(())
}

/// Whether the cross-check is armed. Collectors read this once, at construction: when it is on they
/// have to compute the table row even if they no longer publish it.
pub fn frops_cross_check_enabled() -> bool {
    CROSS_CHECK_ON.load(Ordering::Relaxed)
}

/// Claims one global row on behalf of a collector. See [`FropsCrossCheck`].
#[inline]
pub fn frops_cross_check_row(global_row: u64) {
    let Some(check) = CROSS_CHECK.get() else { return };
    let Some(slot) = check.remaining.get(global_row as usize) else {
        check.overcounted.fetch_add(1, Ordering::Relaxed);
        let _ = check.first_overcounted.compare_exchange(
            NO_ROW,
            global_row,
            Ordering::Relaxed,
            Ordering::Relaxed,
        );
        return;
    };
    // Claim the row only while the assembly still has counts left on it, so a disagreement is
    // recorded instead of wrapping the counter around.
    let mut current = slot.load(Ordering::Relaxed);
    loop {
        if current == 0 {
            check.overcounted.fetch_add(1, Ordering::Relaxed);
            let _ = check.first_overcounted.compare_exchange(
                NO_ROW,
                global_row,
                Ordering::Relaxed,
                Ordering::Relaxed,
            );
            return;
        }
        match slot.compare_exchange_weak(current, current - 1, Ordering::Relaxed, Ordering::Relaxed)
        {
            Ok(_) => return,
            Err(actual) => current = actual,
        }
    }
}

/// Reports the state of the cross-check: `Ok(())` when both producers agree so far.
///
/// Over-counting is final as soon as it is seen. Rows still holding counts only mean a disagreement
/// once every instance has been collected — before that they are simply work not done yet — so the
/// caller says whether it is at that point.
pub fn frops_cross_check_report(all_instances_collected: bool) -> Result<(), String> {
    let Some(check) = CROSS_CHECK.get() else {
        return Ok(());
    };
    let overcounted = check.overcounted.load(Ordering::Relaxed);
    let mut problems = Vec::new();
    if overcounted > 0 {
        let first = check.first_overcounted.load(Ordering::Relaxed);
        problems.push(format!(
            "the collectors counted {overcounted} operation(s) the assembly did not \
             (first at global row {first})"
        ));
    }
    if all_instances_collected {
        let (rows, total) = check
            .remaining
            .iter()
            .map(|s| s.load(Ordering::Relaxed))
            .filter(|&c| c != 0)
            .fold((0u64, 0u64), |(rows, total), c| (rows + 1, total + c));
        if rows > 0 {
            problems.push(format!(
                "the assembly counted {total} operation(s) over {rows} row(s) that no collector \
                 claimed"
            ));
        }
    }
    if problems.is_empty() {
        Ok(())
    } else {
        Err(problems.join("; "))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every phase of the cross-check, in one test: the process state it lives in is shared, so
    /// splitting this into several `#[test]`s would let them run concurrently and interfere.
    #[test]
    fn the_cross_check_separates_the_two_kinds_of_disagreement() {
        let mut column = vec![0u64; FROPS_TABLE_ROWS as usize];
        let (row_a, row_b) = (7u64, FROPS_TABLE_ROWS - 1);
        column[row_a as usize] = 2;
        column[row_b as usize] = 1;

        // Agreement: the collectors claim exactly what the assembly counted.
        load_frops_cross_check(&column).expect("the column has the expected length");
        assert!(frops_cross_check_enabled());
        assert_eq!(frops_cross_check_report(false), Ok(()));
        frops_cross_check_row(row_a);
        frops_cross_check_row(row_a);
        frops_cross_check_row(row_b);
        assert_eq!(frops_cross_check_report(true), Ok(()), "the two producers agree");

        // The collectors claim a row the assembly did not count.
        load_frops_cross_check(&column).unwrap();
        frops_cross_check_row(row_a);
        frops_cross_check_row(row_a);
        frops_cross_check_row(row_a);
        let err = frops_cross_check_report(false).expect_err("over-counting must be reported");
        assert!(err.contains("the assembly did not"), "{err}");
        assert!(err.contains(&format!("global row {row_a}")), "{err}");

        // A row out of range is over-counting too, not a panic.
        load_frops_cross_check(&column).unwrap();
        frops_cross_check_row(FROPS_TABLE_ROWS);
        assert!(frops_cross_check_report(false).is_err());

        // The collectors miss a row the assembly counted: only a disagreement once they are done.
        load_frops_cross_check(&column).unwrap();
        frops_cross_check_row(row_a);
        frops_cross_check_row(row_b);
        assert_eq!(frops_cross_check_report(false), Ok(()), "still work to do, not a disagreement");
        let err = frops_cross_check_report(true).expect_err("a row left over must be reported");
        assert!(err.contains("no collector claimed"), "{err}");

        // A column of the wrong length is rejected instead of arming a shifted check.
        assert!(load_frops_cross_check(&column[1..]).is_err());
    }
}
