use serde::{de, Deserialize, Deserializer};

#[allow(dead_code)]
#[derive(Debug)]
pub enum ZiskOperator {
    Flag,
    CopyB,
    SignExtendB,
    SignExtendH,
    SignExtendW,
    Add,
    AddW,
    Sub,
    SubW,
    Sll,
    SllW,
    Sra,
    Srl,
    SraW,
    SrlW,
    Eq,
    EqW,
    Ltu,
    Lt,
    LtuW,
    LtW,
    Leu,
    Le,
    LeuW,
    LeW,
    And,
    Or,
    Xor,
    Mulu,
    Mul,
    MulW,
    MulUh,
    MulH,
    MulSuh,
    Divu,
    Div,
    DivuW,
    DivW,
    Remu,
    Rem,
    RemuW,
    RemW,
    Minu,
    Min,
    MinuW,
    MinW,
    Maxu,
    Max,
    MaxuW,
    MaxW,
}

impl<'de> Deserialize<'de> for ZiskOperator {
    fn deserialize<D>(deserializer: D) -> Result<ZiskOperator, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value: u8 = Deserialize::deserialize(deserializer)?;
        match value {
            0x00 => Ok(ZiskOperator::Flag),
            0x01 => Ok(ZiskOperator::CopyB),
            0x24 => Ok(ZiskOperator::SignExtendB),
            0x25 => Ok(ZiskOperator::SignExtendH),
            0x25 => Ok(ZiskOperator::SignExtendW),
            0x02 => Ok(ZiskOperator::Add),
            0x12 => Ok(ZiskOperator::AddW),
            0x03 => Ok(ZiskOperator::Sub),
            0x13 => Ok(ZiskOperator::SubW),
            0x0d => Ok(ZiskOperator::Sll),
            0x1d => Ok(ZiskOperator::SllW),
            0x0f => Ok(ZiskOperator::Sra),
            0x0e => Ok(ZiskOperator::Srl),
            0x1f => Ok(ZiskOperator::SraW),
            0x1e => Ok(ZiskOperator::SrlW),
            0x08 => Ok(ZiskOperator::Eq),
            0x18 => Ok(ZiskOperator::EqW),
            0x04 => Ok(ZiskOperator::Ltu),
            0x05 => Ok(ZiskOperator::Lt),
            0x14 => Ok(ZiskOperator::LtuW),
            0x15 => Ok(ZiskOperator::LtW),
            0x06 => Ok(ZiskOperator::Leu),
            0x07 => Ok(ZiskOperator::Le),
            0x16 => Ok(ZiskOperator::LeuW),
            0x17 => Ok(ZiskOperator::LeW),
            0x20 => Ok(ZiskOperator::And),
            0x21 => Ok(ZiskOperator::Or),
            0x22 => Ok(ZiskOperator::Xor),
            0xb0 => Ok(ZiskOperator::Mulu),
            0xb1 => Ok(ZiskOperator::Mul),
            0xb5 => Ok(ZiskOperator::MulW),
            0xb8 => Ok(ZiskOperator::MulUh),
            0xb9 => Ok(ZiskOperator::MulH),
            0xbb => Ok(ZiskOperator::MulSuh),
            0xc0 => Ok(ZiskOperator::Divu),
            0xc1 => Ok(ZiskOperator::Div),
            0xc4 => Ok(ZiskOperator::DivuW),
            0xc5 => Ok(ZiskOperator::DivW),
            0xc8 => Ok(ZiskOperator::Remu),
            0xc9 => Ok(ZiskOperator::Rem),
            0xcc => Ok(ZiskOperator::RemuW),
            0xcd => Ok(ZiskOperator::RemW),
            0x09 => Ok(ZiskOperator::Minu),
            0x0a => Ok(ZiskOperator::Min),
            0x19 => Ok(ZiskOperator::MinuW),
            0x1a => Ok(ZiskOperator::MinW),
            0x0b => Ok(ZiskOperator::Maxu),
            0x0c => Ok(ZiskOperator::Max),
            0x1b => Ok(ZiskOperator::MaxuW),
            0x1c => Ok(ZiskOperator::MaxW),
            _ => Err(de::Error::custom(format!("Unknown ZiskOperator code: {}", value))),
        }
    }
}
