#!/usr/bin/env python3
"""Writes ../secp256k1/glv4.zisk: the secp256k1 double-scalar multiplication
k1*G + k2*P (`zisklib_glv_double_scalar_mul_with_g_secp256k1`) as a 4-way GLV
Strauss-Shamir ladder over one 16-entry table.

Run from any directory: python3 secp256k1_glv4_gen.py
"""
import os

P = 2**256 - 2**32 - 977
GX = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798
GY = 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8
BETA = 0x7AE96A2B657C07106E64479EAC3434E99CF0497512F58995C1396C28719501EE
N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
LAMBDA = 0x5363AD4CC05C30E0A5261C028812645A122E22EA20816678DF02967C1B23BD72


def ec_add(p, q):
    (x1, y1), (x2, y2) = p, q
    assert x1 != x2
    l = (y2 - y1) * pow(x2 - x1, -1, P) % P
    x3 = (l * l - x1 - x2) % P
    return x3, (l * (x1 - x3) - y1) % P


def ec_mul(k, p):
    r = None
    for b in bin(k)[2:]:
        if r is not None:
            x, y = r
            l = 3 * x * x * pow(2 * y, -1, P) % P
            x3 = (l * l - 2 * x) % P
            r = (x3, (l * (x - x3) - y) % P)
        if b == '1':
            r = p if r is None else ec_add(r, p)
    return r


def neg(p):
    return p[0], (-p[1]) % P


G = (GX, GY)
PHI_G = (BETA * GX % P, GY)
assert ec_mul(LAMBDA, G) == PHI_G  # phi(G) = lambda*G


def limbs(v):
    return [(v >> (64 * i)) & (2**64 - 1) for i in range(4)]


def point(p):
    return limbs(p[0]) + limbs(p[1])


def spread(b):
    """Byte b with bit i moved to bit 4*i."""
    return sum(((b >> i) & 1) << (4 * i) for i in range(8))


# The four half-scalars a1, a2 (of k1, over +-G, +-phi(G)) and b1, b2 (of k2, over
# +-P, +-phi(P)) select bit 0..3 of a table index m; T[m] is the sum of the bases
# whose bit is set. Entry m is at SECP_G4_T + 64*m (x[4] || y[4], LE limbs).
SUMS = [(5, 1, 4), (6, 2, 4), (7, 3, 4), (9, 1, 8), (10, 2, 8), (11, 3, 8),
        (12, 4, 8), (13, 5, 8), (14, 6, 8), (15, 7, 8)]  # T[m] = T[lo] + T[hi]

# Caller-saved registers only (t0-t2, a0-a7, t3-t6): the routine runs under
# C callers through the EF ABI entry points, which keep s0-s11 live.
LIMB = [['r10', 'r11'], ['r12', 'r13'], ['r14', 'r15'], ['r16', 'r17']]  # a1 a2 b1 b2
NIB, OFF, NPTR = 'r5', 'r6', 'r7'


def gen():
    o = []
    w = o.append
    w(f"""; ============================================================================
; secp256k1/glv4.zisk - GENERATED by scripts/secp256k1_glv4_gen.py; do not edit.
;
; u64 zisklib_glv_double_scalar_mul_with_g_secp256k1(k1, k2, p, result)
;   [r10=k1, r11=k2, r12=p, r13=result] -> r10 = 1 if k1*G + k2*p is infinity,
;   else 0 (result = k1*G + k2*p). p must be on-curve, non-identity, canonical.
;
; 4-way GLV Strauss-Shamir: k1 = +-a1 +- a2*lambda and k2 = +-b1 +- b2*lambda
; (glv_decompose, verified), all four below 2^128. One table T[16] holds every
; sum of the bases +-G, +-phi(G), +-p, +-phi(p) (bit 0..3 of the index), so each
; of the 128 ladder bits costs one doubling and at most one addition:
;   - T[1..3] (+-G, +-phi(G), their sum) are constants, one block per sign pair;
;     T[4], T[8] (+-p, +-phi(p)) are computed; the other 10 take one addition each.
;   - The 128 4-bit indexes are built first, 16 per word (byte lookup tables that
;     move bit i to bit 4i), so the ladder reads its index with a shift and a mask.
;   - Before each addition the ladder compares only limb 0 of the two x
;     coordinates; on a match (the precompile needs distinct x) it takes a slow
;     path that compares the whole points and doubles, adds or reaches infinity.
; Any x match while building the table (p = +-G, +-phi(G), ...) is degenerate:
; the routine then runs the general version, secp_glv_dsm_general (glv.zisk).
;
; Registers: caller-saved only (r5-r7, r10-r17, r28-r31). Labels `g4_`.
; ============================================================================

u64 SECP_G4_T[128]   = 0
u64 SECP_G4_NIB[8]   = 0
u64 SECP_G4_RES[8]   = 0
u64 SECP_G4_HDR[2]   = 0
u64 SECP_G4_HDRB[2]  = 0
u64 SECP_G4_ARGS[4]  = 0
u64 SECP_G4_SC[16]   = 0
u64 SECP_G4_SIG[2]   = 0
""")
    # T[1], T[2], T[3] for sign bits (s1 of a1, s2 of a2): index s1 | s2 << 1.
    blocks = []
    for idx in range(4):
        s1, s2 = idx & 1, idx >> 1
        t1 = neg(G) if s1 else G
        t2 = neg(PHI_G) if s2 else PHI_G
        blocks += point(t1) + point(t2) + point(ec_add(t1, t2))
    w("; T[1..3] = +-G, +-phi(G), their sum; 4 blocks of 24 words, by sign pair.")
    w("const u64 SECP_G4_CG[96] =")
    for i in range(0, 96, 4):
        w("\t" + ", ".join(f"0x{v:016X}" for v in blocks[i:i + 4]) + ("," if i < 92 else ""))
    w("; byte -> its 8 bits at bits 0, 4, ..., 28 (LO) or 32, 36, ..., 60 (HI)")
    for name, sh in (("SECP_G4_SPRLO", 0), ("SECP_G4_SPRHI", 32)):
        vals = [spread(b) << sh for b in range(256)]
        w(f"const u64 {name}[256] =")
        for i in range(0, 256, 4):
            w("\t" + ", ".join(f"0x{v:016X}" for v in vals[i:i + 4]) + ("," if i < 252 else ""))
    w("")

    # ---- entry: decompose both scalars --------------------------------------
    w("""zisklib_glv_double_scalar_mul_with_g_secp256k1:
	push r1
	copyb(0, r10) -> [SECP_G4_ARGS + 0]
	copyb(0, r11) -> [SECP_G4_ARGS + 8]
	copyb(0, r12) -> [SECP_G4_ARGS + 16]
	copyb(0, r13) -> [SECP_G4_ARGS + 24]
	; (a1, a2, sa) = glv_decompose(k1); (b1, b2, sb) = glv_decompose(k2)
	copyb(0, SECP_G4_SC + 0) -> r11
	copyb(0, SECP_G4_SC + 32) -> r12
	call zisklib_glv_decompose_fn_secp256k1
	copyb(0, r10) -> [SECP_G4_SIG + 0]
	copyb(0, [SECP_G4_ARGS + 8]) -> r10
	copyb(0, SECP_G4_SC + 64) -> r11
	copyb(0, SECP_G4_SC + 96) -> r12
	call zisklib_glv_decompose_fn_secp256k1
	copyb(0, r10) -> [SECP_G4_SIG + 8]

	; ---- T[1..3] = the constant block for (sa & 1, sa >> 1) ----
	copyb(0, [SECP_G4_SIG + 0]) -> r5
	sll(r5, 6) -> r6
	sll(r5, 7)
	add(c, r6)
	add(c, SECP_G4_CG)
	dma_xmemcpy(SECP_G4_T + 64, c) -> r6, j(192, 4)
	; ---- T[4] = sb & 1 ? -p : p ----
	copyb(0, [SECP_G4_ARGS + 16]) -> r5
	dma_xmemcpy(SECP_G4_T + 256, r5) -> r6, j(64, 4)
	copyb(0, [SECP_G4_SIG + 8])
	and(c, 1)
	eq(c, 0), j(g4_t4pos)
	add(r5, 32) -> r10
	copyb(0, SECP_G4_T + 288) -> r11
	call zisklib_neg_fp_secp256k1
g4_t4pos:
	; ---- T[8] = (beta * p.x, sb & 2 ? -p.y : p.y) ----
	copyb(0, SECP_BETA) -> r10
	copyb(0, [SECP_G4_ARGS + 16]) -> r11
	copyb(0, SECP_G4_T + 512) -> r12
	call zisklib_mul_fp_secp256k1
	copyb(0, [SECP_G4_ARGS + 16]) -> r10
	add(r10, 32) -> r10
	copyb(0, [SECP_G4_SIG + 8])
	and(c, 2)
	eq(c, 0), j(g4_t8pos)
	copyb(0, SECP_G4_T + 544) -> r11
	call zisklib_neg_fp_secp256k1
	jump(g4_sums)
g4_t8pos:
	dma_xmemcpy(SECP_G4_T + 544, r10) -> r6, j(32, 4)
g4_sums:
	; ---- the other 10 entries: T[m] = T[lo] + T[hi] (x match -> general) ----""")
    for m, lo, hi in SUMS:
        w(f"""	dma_xmemcpy(SECP_G4_T + {64 * m}, SECP_G4_T + {64 * lo}) -> r6, j(64, 4)
	copyb(0, [SECP_G4_T + {64 * m}])
	eq(c, [SECP_G4_T + {64 * hi}]), j(g4_general)
	copyb(0, SECP_G4_T + {64 * m}) -> [SECP_G4_HDRB + 0]
	copyb(0, SECP_G4_T + {64 * hi}) -> [SECP_G4_HDRB + 8]
	secp256k1_add(0, SECP_G4_HDRB)""")

    # ---- the 128 indexes, 16 per word: NIB[w] holds bits 16w..16w+15 ----------
    w("""
	; ---- indexes: NIB[w] nibble j = bit (16w + j) of a1 | a2 << 1 | b1 << 2 | b2 << 3 ----""")
    for s in range(4):
        for li in range(2):
            w(f"\tcopyb(0, [SECP_G4_SC + {32 * s + 8 * li}]) -> {LIMB[s][li]}")
    w("\tcopyb(0, SECP_G4_SPRLO) -> r28")
    w("\tcopyb(0, SECP_G4_SPRHI) -> r29")
    for wd in range(8):
        li, sh = wd >> 2, 16 * (wd & 3)
        for s in range(4):
            reg = LIMB[s][li]
            if sh >= 3:
                w(f"\tsrl({reg}, {sh - 3})")
            else:
                w(f"\tsll({reg}, 3)")
            w("\tand(c, 0x7F8)")
            w("\tadd(c, r28)")
            w("\tcopyb(c, 8[a + 0]) -> r6")
            w(f"\tsrl({reg}, {sh + 5})")
            w("\tand(c, 0x7F8)")
            w("\tadd(c, r29)")
            w("\tcopyb(c, 8[a + 0])")
            last = s == 3
            if s == 0:
                w("\tor(c, r6) -> r30")
            else:
                w("\tor(c, r6)")
                w(f"\tsll(c, {s})")
                w(f"\tor(c, r30) -> {'[SECP_G4_NIB + %d]' % (8 * wd) if last else 'r30'}")

    # ---- ladder ---------------------------------------------------------------
    w(f"""
	; ---- ladder over bits 127..0: word NIB[7] first, its top nibble first ----
	copyb(0, SECP_G4_NIB + 56) -> {NPTR}
	copyb(0, [SECP_G4_NIB + 56]) -> {NIB}
	copyb(0, SECP_G4_RES) -> [SECP_G4_HDR + 0]""")
    # Phase A: the result is still infinity; the first nonzero index copies T[m].
    for i in range(16):
        w(f"""g4_a{i}:
	srl({NIB}, 54)
	and(c, 0x3C0) -> {OFF}
	sll({NIB}, 4) -> {NIB}
	eq({OFF}, 0), j(g4_a{i + 1})
	add({OFF}, SECP_G4_T)
	dma_xmemcpy(SECP_G4_RES, c) -> r6, j(64, 4)
	jump(g4_b{i + 1})""")
    w(f"""g4_a16:
	eq({NPTR}, SECP_G4_NIB), j(g4_inf)
	sub({NPTR}, 8) -> {NPTR}
	copyb({NPTR}, 8[a + 0]) -> {NIB}
	jump(g4_a0)""")
    # Phase B: double, then add T[m] (m != 0) after a limb-0 x check.
    for i in range(16):
        w(f"""g4_b{i}:
	secp256k1_dbl(0, SECP_G4_RES)
	srl({NIB}, 54)
	and(c, 0x3C0) -> {OFF}
	sll({NIB}, 4) -> {NIB}
	eq({OFF}, 0), j(g4_b{i + 1})
	add({OFF}, SECP_G4_T) -> [SECP_G4_HDR + 8]
	copyb(c, 8[a + 0])
	eq(c, [SECP_G4_RES]), j(g4_s{i})
	secp256k1_add(0, SECP_G4_HDR)""")
    w(f"""g4_b16:
	eq({NPTR}, SECP_G4_NIB), j(g4_done)
	sub({NPTR}, 8) -> {NPTR}
	copyb({NPTR}, 8[a + 0]) -> {NIB}
	jump(g4_b0)""")
    for i in range(16):
        w(f"""g4_s{i}:
	call secp_g4_slow_add
	eq(r10, 0), j(g4_b{i + 1}, g4_a{i + 1})""")

    w("""g4_done:
	copyb(0, [SECP_G4_ARGS + 24]) -> r5
	dma_xmemcpy(r5, SECP_G4_RES) -> r6, j(64, 4)
	copyb(0, 0) -> r10
	pop r1
	ret
g4_inf:
	copyb(0, 1) -> r10
	pop r1
	ret
g4_general:
	copyb(0, [SECP_G4_ARGS + 0]) -> r10
	copyb(0, [SECP_G4_ARGS + 8]) -> r11
	copyb(0, [SECP_G4_ARGS + 16]) -> r12
	copyb(0, [SECP_G4_ARGS + 24]) -> r13
	pop r1
	jump(secp_glv_dsm_general)

; secp_g4_slow_add [leaf]: RES += T (T = [SECP_G4_HDR + 8]) when x limb 0 matched.
;   Different x: add. Same point: double. Opposite points: r10 = 1 (infinity).
;   Else r10 = 0. Uses r10, r11.
secp_g4_slow_add:
	copyb(0, [SECP_G4_HDR + 8]) -> r11""")
    for i in (1, 2, 3):
        w(f"""	copyb(r11, 8[a + {8 * i}])
	eq(c, [SECP_G4_RES + {8 * i}]), j(g4_sx{i})
	jump(g4_sadd)
g4_sx{i}:""")
    for i in range(4):
        w(f"""	copyb(r11, 8[a + {32 + 8 * i}])
	eq(c, [SECP_G4_RES + {32 + 8 * i}]), j(g4_sy{i})
	copyb(0, 1) -> r10
	ret
g4_sy{i}:""")
    w("""	secp256k1_dbl(0, SECP_G4_RES)
	copyb(0, 0) -> r10
	ret
g4_sadd:
	secp256k1_add(0, SECP_G4_HDR)
	copyb(0, 0) -> r10
	ret""")
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "secp256k1", "glv4.zisk")
    with open(out, "w") as f:
        f.write(gen())
    print("wrote", os.path.normpath(out))
