[package]
name = "precompiles-helpers"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[dependencies]
ark-ff = { workspace = true }
ark-std = { workspace = true }
ark-secp256k1 = { workspace = true }
ark-bn254 = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
cfg-if = "1.0"
lib-c = { path = "../../lib-c" }
circuit = { path = "../../tools/circuit" }

[features]
default = []