[package]
name = "precompiles-helpers"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = { workspace = true }
ark-std = { workspace = true }
ark-secp256k1 = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
lib-c = { path = "../../lib-c" }
circuit = { path = "../../tools/circuit" }

[features]
default = []
secp256k1_rust = []