[package]
name = "fib"
version = "0.1.0"
edition = "2021"
default-run = "fib"
build = "build.rs"

[features]
default = []
zisk = []

[dependencies]
bytes = "1.6.0"
prost = "0.12.6"
prost-types = "0.12.6"
tiny-keccak = { version = "2.0.2", features = ["keccak", "sha3"] }


[build-dependencies]
prost-build = "0.12.6"

[lib]
name = "fib"

[[bin]]
name = "fib"
path = "src/bin/fib.rs"

[[bin]]
name = "input"
path = "src/bin/gen_input.rs"
