[package]
name = "consensus-prover-service"
description = "Command-line client for Consensus Network"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "consensus_client"
path = "src/lib.rs"

[[bin]]
name = "consensus-client"
path = "src/bin/main.rs"

[build-dependencies]
vergen = { version = "8", default-features = false, features = [
    "build",
    "git",
    "git2",
] }

[dependencies]
cargo-zisk = { workspace = true }
zisk-common = { workspace = true }
proofman-common = { workspace = true }
rom-setup = { workspace = true }
asm-runner = { workspace = true }
consensus-grpc-api = { workspace = true }
consensus-core = { workspace = true }
consensus-prover = { workspace = true }
consensus-common = { workspace = true }

tonic = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
prost-types = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
colored = { workspace = true }
toml = { workspace = true }
