[package]
name = "ziskemu"
version = "0.1.0"
edition = "2021"

[lib]
name = "ziskemu"
path = "src/lib.rs"

[[bin]]
name = "ziskemu"
path = "src/bin/ziskemu.rs"

[dependencies]
zisk-core = { path = "../core" }
clap = { version = "4.5.9", features = ["derive", "env"] }
riscv = { path="../riscv" }
sysinfo = "0.31.2"
p3-field = { workspace=true }

[build-dependencies]
vergen = { version = "8", default-features = false, features = [
    "build",
    "git",
    "git2",
] }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
pprof = { version = "0.13.0", features = ["flamegraph", "criterion"] }

[[bench]]
name = "benchmark"
harness = false
