[package]
name = "ziskemu"
version = "0.2.0"
edition = "2021"

[lib]
name = "ziskemu"
path = "src/lib.rs"

[[bin]]
name = "ziskemu"
path = "src/bin/ziskemu.rs"

[dependencies]
zisk-core = { path = "../core" }
riscv = { path = "../riscv" }
zisk-pil = { path = "../pil" }
data-bus = { path = "../data-bus" }
rayon = { workspace = true }

p3-field = { workspace=true }
clap = { version = "4.5.9", features = ["derive", "env"] }
sysinfo = "0.33"

[build-dependencies]
vergen = { version = "8", default-features = false, features = [
    "build",
    "git",
    "git2",
] }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
pprof = { version = "0.14.0", features = ["flamegraph", "criterion"] }

[[bench]]
name = "benchmark"
harness = false

[features]
default = []
# sp = []
no_lib_link = ["zisk-pil/no_lib_link"]
