[package]
name = "ziskclib"
description = "C library routines for ZisK guest programs"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
categories = { workspace = true }
publish = false

[lib]
name = "ziskclib"
# crate-type = ["cdylib"]      # Creates dynamic lib
crate-type = ["staticlib"] # Creates static lib

[dependencies]
tiny-keccak = { workspace = true, features = ["keccak"] }
sha2 = { workspace = true }
