profile = "compiler"
change-id = 126701

[build]
target = ["riscv64ima-polygon-ziskos-elf"]
#extended = true
tools = ["library/std","rustfmt"]
configure-args = []
#cargo-native-static = true

[llvm]
download-ci-llvm = false

[rust]
lld = true
#llvm-tools = true
#channel = "nightly"