[package]
name = "zisk-coordinator"
description = "Coordinator node for the ZisK distributed proving network"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
categories = { workspace = true }
publish = false

[dependencies]
zisk-cluster-api = { workspace = true }
zisk-cluster-common = { workspace = true }
zisk-common = { workspace = true }

proofman = { workspace = true }

bincode = { workspace = true }
blake3 = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
tonic = { workspace = true }
prost-types = { workspace = true }
config = { workspace = true }
reqwest = { workspace = true }
colored = { workspace = true }

signal-hook = { workspace = true }
signal-hook-tokio = { workspace = true }
humantime = "2.3"
futures-util = { workspace = true }
async-stream = { workspace = true }
metrics = { workspace = true }
