[package]
name = "asm-runner"
version = "0.1.0"
edition = "2021"

[lib]
name = "asm_runner"
path = "src/lib.rs"

[[bin]]
name = "asm-runner-main"
path = "src/main.rs"

[dependencies]
ziskemu = { path = "../../emulator" }
libc = "0.2"