[package]
name = "asm-runner"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[lib]
name = "asm_runner"
path = "src/lib.rs"

[[bin]]
name = "asm-runner-main"
path = "src/main.rs"

[dependencies]
log = { workspace = true }
ziskemu = { path = "../../emulator" }
zisk-common = { path = "../../common" }

clap = { version = "4", features = ["derive"] }
libc = "0.2"
named-sem = "0.2.2"
