[package]
name = "asm-runner"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[lib]
name = "asm_runner"
path = "src/lib.rs"

[dependencies]
zisk-common = { workspace = true }
zisk-core = { workspace = true }
mem-planner-cpp = { workspace = true }

tracing = { workspace = true}
rayon = { workspace = true}
anyhow = { workspace = true}

clap = { version = "4", features = ["derive"] }
libc = "0.2"
ureq = "3"
thiserror = "2"

[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
named-sem = { workspace = true }

[features]
stats = []
