[package]
name = "zisk-core"
description = "Core types and proving primitives for the ZisK zkVM"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
categories = { workspace = true }

[lib]
name = "zisk_core"
path = "src/lib.rs"

[dependencies]
zisk-precomp-helpers = { workspace = true }
ziskos = { workspace = true }
rayon = { workspace = true }
proofman-fields = { workspace = true }
sha2 = { workspace = true }
paste = { workspace = true }
zisk-definitions = { workspace = true }

tiny-keccak = { workspace = true, features = ["keccak"] }
elf = "0.7.4"

[build-dependencies]
zisk-lib-float = { workspace = true, optional = true }

[features]
default = []
debug_dma = []
log_dma_ops = []
# sp = []
float = ["dep:zisk-lib-float", "zisk-lib-float/float"]
zba = []
zbc = []
zbkc = []
zbkx = []
zba_native = []
zbc_native = []
zbkc_native = []
zbkx_native = []
zicond_native = []
