#![allow(dead_code)]
#![allow(clippy::manual_range_contains, clippy::nonminimal_bool)]
// @generated by frops-analyzer — do not edit by hand.
// generated with: max-table=16777216 partition-bits=21 low-cap=4096 max-regions-per-op=4 table-cost=3 nodes=1
use sm_frequent_ops::FrequentOpsHelpers;
use std::error::Error;
use zisk_core::zisk_ops::ZiskOp;

const OP_MULUH: u8 = ZiskOp::Muluh.code();
const OP_MUL: u8 = ZiskOp::Mul.code();
const OP_DIVU: u8 = ZiskOp::Divu.code();
const OP_REMU: u8 = ZiskOp::Remu.code();

const OP_TABLE_OFFSETS_START: usize = 177;
const OP_TABLE_OFFSETS: [usize; 9] = [0, 0, 0, 371536, 0, 0, 0, 860297, 2092523];

#[derive(Debug, Clone)]
pub struct ArithFrops {
    table: FrequentOpsHelpers,
}

const FREQUENT_OP_EMPTY: usize = 256;

impl Default for ArithFrops {
    fn default() -> Self {
        Self::new()
    }
}

impl ArithFrops {
    pub const TABLE_ID: usize = 5010;
    pub const NO_FROPS: usize = FrequentOpsHelpers::NO_FROPS;
    pub fn new() -> Self {
        Self { table: FrequentOpsHelpers::new() }
    }

    pub fn build_table(&mut self) {
        // op muluh
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a < 540 && b < 652
            for a in 0..540 {
                for b in 0..652 {
                    ops.push([a, b]);
                }
            }
            // mid_box: a >= 0xFFFFF000 && a < 0x100001000 && (a & 7) == 0 && b < 19
            for a in (0xFFFFF000..0x100001000).step_by(8) {
                for b in 0..19 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_MULUH, &mut ops, true);
        }
        // op mul
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a < 635 && b < 731
            for a in 0..635 {
                for b in 0..731 {
                    ops.push([a, b]);
                }
            }
            // mid_box: a >= 0xFFFFF000 && a < 0x100001000 && (a & 7) == 0 && b < 19
            for a in (0xFFFFF000..0x100001000).step_by(8) {
                for b in 0..19 {
                    ops.push([a, b]);
                }
            }
            // mid_box: a >= 0x7FFFFFF001 && a < 0x8000001001 && (a & 7) == 1 && b == 2045
            for a in (0x7FFFFFF001..0x8000001001).step_by(8) {
                for b in 0x7FD..0x7FE {
                    ops.push([a, b]);
                }
            }
            // mid_box: a >= 0x3FE8000000000 && a < 0x3FE8000001000 && b == 2045
            for a in 0x3FE8000000000..0x3FE8000001000 {
                for b in 0x7FD..0x7FE {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_MUL, &mut ops, true);
        }
        // op divu
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a < 2402 && b < 513
            for a in 0..2402 {
                for b in 0..513 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_DIVU, &mut ops, true);
        }
        // op remu
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a < 3 && b < 3
            for a in 0..3 {
                for b in 0..3 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_REMU, &mut ops, true);
        }
    }

    #[inline(always)]
    pub fn is_frequent_op(op: u8, a: u64, b: u64) -> bool {
        match op {
            OP_MULUH => {
                a < 540 && b < 652 || a >= 0xFFFFF000 && a < 0x100001000 && (a & 7) == 0 && b < 19
            }
            OP_MUL => {
                a < 635 && b < 731
                    || a >= 0xFFFFF000 && a < 0x100001000 && (a & 7) == 0 && b < 19
                    || a >= 0x7FFFFFF001 && a < 0x8000001001 && (a & 7) == 1 && b == 2045
                    || a >= 0x3FE8000000000 && a < 0x3FE8000001000 && b == 2045
            }
            OP_DIVU => a < 2402 && b < 513,
            OP_REMU => a < 3 && b < 3,
            _ => false,
        }
    }

    #[inline(always)]
    pub fn get_row(op: u8, a: u64, b: u64) -> usize {
        let relative_offset = match op {
            OP_MULUH => {
                if a < 540 && b < 652 {
                    (a * 652 + b) as usize
                } else if a >= 0xFFFFF000 && a < 0x100001000 && (a & 7) == 0 && b < 19 {
                    (((a - 0xFFFFF000) / 8) * 19 + b) as usize + 352080
                } else {
                    Self::NO_FROPS
                }
            }
            OP_MUL => {
                if a < 635 && b < 731 {
                    (a * 731 + b) as usize
                } else if a >= 0xFFFFF000 && a < 0x100001000 && (a & 7) == 0 && b < 19 {
                    (((a - 0xFFFFF000) / 8) * 19 + b) as usize + 464185
                } else if a >= 0x7FFFFFF001 && a < 0x8000001001 && (a & 7) == 1 && b == 2045 {
                    ((a - 0x7FFFFFF001) / 8) as usize + 483641
                } else if a >= 0x3FE8000000000 && a < 0x3FE8000001000 && b == 2045 {
                    (a - 0x3FE8000000000) as usize + 484665
                } else {
                    Self::NO_FROPS
                }
            }
            OP_DIVU => {
                if a < 2402 && b < 513 {
                    (a * 513 + b) as usize
                } else {
                    Self::NO_FROPS
                }
            }
            OP_REMU => {
                if a < 3 && b < 3 {
                    (a * 3 + b) as usize
                } else {
                    Self::NO_FROPS
                }
            }
            _ => return Self::NO_FROPS,
        };
        if relative_offset == Self::NO_FROPS {
            Self::NO_FROPS
        } else {
            relative_offset + OP_TABLE_OFFSETS[op as usize - OP_TABLE_OFFSETS_START]
        }
    }

    #[inline(always)]
    pub fn count(&self) -> usize {
        self.table.count()
    }

    #[cfg(test)]
    pub fn test_table_offsets(&mut self) {
        self.build_table();
        let (start, offsets) = self.table.generate_table_offsets();
        if (start != OP_TABLE_OFFSETS_START) || (offsets != OP_TABLE_OFFSETS) {
            self.table.print_table_offsets();
            panic!("Table offsets do not match expected values");
        }
        assert_eq!(start, OP_TABLE_OFFSETS_START);
        assert_eq!(offsets, OP_TABLE_OFFSETS);
    }

    #[inline(always)]
    pub fn generate_full_table(&self) -> Vec<(u8, u64, u64, u64, bool)> {
        self.table.generate_full_table()
    }

    #[inline(always)]
    pub fn generate_table(&self) -> Vec<(u8, u64, u64)> {
        self.table.generate_table()
    }

    #[inline(always)]
    pub fn generate_cmd(
        &mut self,
        cmd_name: &'static str,
        default_file: &'static str,
    ) -> Result<(), Box<dyn Error>> {
        self.build_table();
        let full_table = self.generate_full_table();
        let full_table_count = full_table.len();
        self.table.generate_cmd(
            "Zisk",
            "ArithFrops",
            cmd_name,
            default_file,
            full_table,
            full_table_count,
        )
    }
}

#[test]
fn test_table_offsets() {
    let mut fops = ArithFrops::new();
    fops.test_table_offsets();
}

#[test]
fn test_all_accessible_values() {
    let mut fops = ArithFrops::new();
    fops.build_table();
    let table = fops.generate_full_table();
    FrequentOpsHelpers::test_all_accessible_values(
        &table,
        ArithFrops::is_frequent_op,
        ArithFrops::get_row,
    );
}
