//! The `ArithRangeTableHelpers` module defines utilities for managing and validating
//! arithmetic range tables.
//!
//! ## Key Features
//!
//! - Provides utilities for working with arithmetic range tables, including:
//!   - Translating range indices to human-readable names.
//!   - Calculating row indices for range and carry checks based on input values.
//!   - Ensures values adhere to their defined ranges, distinguishing between full, positive, and
//!     negative ranges.
//!
//! Row-multiplicity counting for the range table is no longer done here: the prover derives it
//! directly from the committed trace.

const FULL: u8 = 0x00;
const POS: u8 = 0x01;
const NEG: u8 = 0x02;

/// Number of slots in the compressed range-id sequence (see `pil/arith_range_table.pil`).
const RANGE_SLOTS: usize = 20;

/// First row of the carry block: the chunk-range slots occupy
/// `12 * 2^16 + 8 * 2^15 = 32 * 0x8000` rows before it.
const CARRY_BASE: i64 = 0x100000;

/// Carry range covered by the table, must match `MIN/MAX_CARRY_RANGE` in the PIL.
/// The attainable carry range is +-262142; see `src/tools/arith_carry_range.rs`.
const MIN_CARRY: i64 = -262142;
const MAX_CARRY: i64 = 262142;

/// Total rows of the `ArithRangeTable` AIR. It is a `virtual` air, so it is sized to exactly this
/// many rows (no power-of-two padding); must match `ROWS` in `pil/arith_range_table.pil`.
const ROWS: usize = CARRY_BASE as usize + (MAX_CARRY - MIN_CARRY + 1) as usize;

/// `ceil(log2(ROWS))`, used to split the multiplicity vector into at most 64 chunks.
const ROWS_BITS: usize = usize::BITS as usize - (ROWS - 1).leading_zeros() as usize;

// ROWS as the PIL computes it: FULL_RANGES * 2^16 + (POS_RANGES + NEG_RANGES) * 2^15 + CARRY_RANGE_SIZE
const _: () = assert!(ROWS == 12 * (1 << 16) + 8 * (1 << 15) + 524_285);
// the `updated` bitmask has 64 slots, so the chunking must not produce more than that
const _: () = assert!((ROWS - 1) >> (ROWS_BITS - 6) < 64);

/// Generic "any 16-bit chunk" range id. Must be a FULL slot; matches `ARITH_RANGE_16_BITS`
/// in `pil/arith_range_table.pil`.
pub const ARITH_RANGE_16_BITS: u8 = 3;

/// The `ArithRangeTableHelpers` struct provides utility functions for working with
/// range tables, including converting range indices to names, calculating row indices,
/// and validating input ranges.
pub struct ArithRangeTableHelpers;

/// Slot pattern of the compressed range-id sequence: `-` NEG, `+` POS, `F` FULL.
/// Must match the `RANGE_ID` fixed column in `pil/arith_range_table.pil`. `RANGES` and `OFFSETS`
/// below are derived from it; `range_layout_tests` checks they still agree.
pub(crate) const RANGE_PATTERN: &str = "-F-FFFF-F+FFF+F+F-F-";

// Predefined range types for each range index. Generated by `generate_table()` below.
const RANGES: [u8; RANGE_SLOTS] = [
    NEG, FULL, NEG, FULL, FULL, FULL, FULL, NEG, FULL, POS, FULL, FULL, FULL, POS, FULL, POS, FULL,
    NEG, FULL, NEG,
];

// Offset values (in units of 0x8000) corresponding to each range index.
const OFFSETS: [usize; RANGE_SLOTS] =
    [27, 0, 28, 2, 4, 6, 8, 29, 10, 24, 12, 14, 16, 25, 18, 26, 20, 30, 22, 31];

impl ArithRangeTableHelpers {
    /// Returns a human-readable name for a given range index.
    ///
    /// # Arguments
    /// * `range_index` - The index of the range whose name is needed.
    ///
    /// # Returns
    /// A string slice representing the name of the range.
    pub fn get_range_name(range_index: u8) -> &'static str {
        // (x3, x1, y3, y1) types of each rid, i.e. slots [rid, rid+1, rid+2, rid+3] of
        // RANGE_PATTERN. Must match the rid table in pil/arith_range_table.pil.
        match range_index {
            0 => "-  F  -  F",
            1 => "F  -  F  F",
            2 => "-  F  F  F",
            3 => "F  F  F  F",
            4 => "F  F  F  -",
            5 => "F  F  -  F",
            6 => "F  -  F  +",
            7 => "-  F  +  F",
            8 => "F  +  F  F",
            9 => "+  F  F  F",
            10 => "F  F  F  +",
            11 => "F  F  +  F",
            12 => "F  +  F  +",
            13 => "+  F  +  F",
            14 => "F  +  F  -",
            15 => "+  F  -  F",
            16 => "F  -  F  -",
            _ => panic!("Invalid range index"),
        }
    }

    /// Calculates the row index for a chunk range check based on the range ID and value.
    ///
    /// # Arguments
    /// * `range_index` - The index of the range being checked.
    /// * `value` - The value being validated against the range.
    ///
    /// # Returns
    /// The calculated row index for the range table.
    pub fn get_row_chunk_range_check(range_index: u8, value: u64) -> usize {
        // - F - F F F F - F + F F F + F + F - F -
        assert!((range_index as usize) < RANGE_SLOTS);
        let range_type = RANGES[range_index as usize];
        assert!(value >= if range_type == NEG { 0x8000 } else { 0 });
        assert!(
            value
                <= match range_type {
                    FULL => 0xFFFF,
                    POS => 0x7FFF,
                    NEG => 0xFFFF,
                    _ => panic!("Invalid range type"),
                }
        );
        OFFSETS[range_index as usize] * 0x8000
            + if range_type == NEG { value - 0x8000 } else { value } as usize
    }

    /// Calculates the row index for a carry range check based on the value.
    ///
    /// # Arguments
    /// * `value` - The carry value being validated.
    ///
    /// # Returns
    /// The calculated row index for the carry range table.
    pub fn get_row_carry_range_check(value: i64) -> usize {
        assert!(value >= MIN_CARRY, "carry {value} below MIN_CARRY {MIN_CARRY}");
        assert!(value <= MAX_CARRY, "carry {value} above MAX_CARRY {MAX_CARRY}");
        (CARRY_BASE - MIN_CARRY + value) as usize
    }
}

#[cfg(feature = "generate_code_arith_range_table")]
#[allow(dead_code)]
fn generate_table() {
    let pattern = RANGE_PATTERN;
    let mut ranges = String::new();
    let mut offsets = [0usize; RANGE_SLOTS];
    let mut offset = 0;
    for range_loop in [FULL, POS, NEG] {
        let mut index = 0;
        for c in pattern.chars() {
            if c == ' ' || c == '_' {
                continue;
            }
            let range_id = match c {
                'F' => FULL,
                '+' => POS,
                '-' => NEG,
                _ => panic!("Invalid character in pattern"),
            };
            if range_loop == FULL {
                if index > 0 {
                    ranges.push_str(", ")
                }
                ranges.push_str(match range_id {
                    FULL => "FULL",
                    POS => "POS",
                    _ => "NEG",
                });
                // ranges[index] = range_id
            }
            if range_loop == range_id {
                offsets[index] = offset;
                offset += if range_loop == FULL { 2 } else { 1 };
            }
            index += 1;
        }
    }
    println!("const RANGES: [u8; RANGE_SLOTS] = [{}];", ranges);
    println!("const OFFSETS: [usize; RANGE_SLOTS] = {:?};", offsets);
    println!("// total rows before the carry block: {}", offset * 0x8000);
}

#[cfg(test)]
mod range_layout_tests {
    //! Ties every representation of the compressed range-id layout together, so that changing one
    //! of them without the others fails here instead of in the proof.

    use super::*;

    fn slot_types() -> Vec<u8> {
        RANGE_PATTERN
            .chars()
            .map(|c| match c {
                'F' => FULL,
                '+' => POS,
                '-' => NEG,
                _ => panic!("invalid character {c:?} in RANGE_PATTERN"),
            })
            .collect()
    }

    #[test]
    fn pattern_matches_ranges_and_offsets() {
        let types = slot_types();
        assert_eq!(types.len(), RANGE_SLOTS, "RANGE_PATTERN length vs RANGE_SLOTS");
        assert_eq!(types.as_slice(), RANGES.as_slice(), "RANGE_PATTERN vs RANGES");

        // FULL slots first (2 units of 0x8000 each), then POS, then NEG - the row order of the
        // RANGE_ID / RANGE_VALUES fixed columns in the PIL.
        let mut expected = [0usize; RANGE_SLOTS];
        let mut unit = 0;
        for group in [FULL, POS, NEG] {
            for (slot, &t) in types.iter().enumerate() {
                if t == group {
                    expected[slot] = unit;
                    unit += if group == FULL { 2 } else { 1 };
                }
            }
        }
        assert_eq!(expected.as_slice(), OFFSETS.as_slice(), "RANGE_PATTERN vs OFFSETS");
        assert_eq!(
            unit * 0x8000,
            CARRY_BASE as usize,
            "chunk-range rows vs CARRY_BASE (the carry block must start right after them)"
        );
    }

    #[test]
    fn generic_16_bit_range_is_a_full_slot() {
        assert_eq!(RANGES[ARITH_RANGE_16_BITS as usize], FULL);
    }

    #[test]
    fn rid_names_match_the_pattern() {
        let types = slot_types();
        let sym = |t: u8| match t {
            FULL => "F",
            POS => "+",
            _ => "-",
        };
        for rid in 0..17u8 {
            let expected: Vec<&str> =
                (0..4).map(|j| sym(types[rid as usize + j as usize])).collect();
            let got: Vec<&str> =
                ArithRangeTableHelpers::get_range_name(rid).split_whitespace().collect();
            assert_eq!(got, expected, "get_range_name({rid}) vs RANGE_PATTERN slots");
        }
    }

    #[test]
    fn the_17_rids_cover_exactly_the_required_tuples() {
        let types = slot_types();
        // (x3, x1, y3, y1) of each rid, read through the four consecutive offsets
        let tuples: Vec<[u8; 4]> = (0..17)
            .map(|rid| [types[rid], types[rid + 1], types[rid + 2], types[rid + 3]])
            .collect();

        // required: any (x3, y3) with x1 = y1 = FULL, and any (x1, y1) with x3 = y3 = FULL
        let mut required: Vec<[u8; 4]> = Vec::new();
        for u in [FULL, POS, NEG] {
            for v in [FULL, POS, NEG] {
                required.push([u, FULL, v, FULL]);
                required.push([FULL, u, FULL, v]);
            }
        }
        required.sort_unstable();
        required.dedup();
        assert_eq!(required.len(), 17);

        let mut sorted = tuples.clone();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(sorted.len(), 17, "the 17 rids must map to 17 distinct tuples");
        assert_eq!(sorted, required, "rids do not cover exactly the required tuples");

        // each column view must use exactly 11 FULL, 3 POS and 3 NEG slots
        for col in 0..4 {
            let count = |t: u8| tuples.iter().filter(|tp| tp[col] == t).count();
            assert_eq!((count(FULL), count(POS), count(NEG)), (11, 3, 3), "column {col}");
        }
    }

    /// The rid table in `pil/arith_range_table.pil` documents, per rid, which of the two views
    /// (`range_ab`, `range_cd`) ever takes it, and gives a reason for the ones restricted to a single
    /// view. That column is an observation about the generated table, so it can go stale; keep it
    /// honest here.
    #[test]
    fn rid_view_usage_matches_the_pil_table() {
        use crate::ARITH_TABLE;

        const AB_ONLY: [u16; 4] = [2, 9, 14, 15];
        const CD_ONLY: [u16; 4] = [4, 5, 10, 11];
        const BOTH: [u16; 9] = [0, 1, 3, 6, 7, 8, 12, 13, 16];

        let ab: Vec<u16> = {
            let mut v: Vec<u16> = ARITH_TABLE.iter().map(|r| r[2]).collect();
            v.sort_unstable();
            v.dedup();
            v
        };
        let cd: Vec<u16> = {
            let mut v: Vec<u16> = ARITH_TABLE.iter().map(|r| r[3]).collect();
            v.sort_unstable();
            v.dedup();
            v
        };

        let msg = "the `views` column of the rid table in pil/arith_range_table.pil no longer \
                   matches the generated table; update it (and its reason column) or the filters";
        for rid in AB_ONLY {
            assert!(
                ab.contains(&rid),
                "rid {rid} is documented as ab-only but ab never uses it: {msg}"
            );
            assert!(!cd.contains(&rid), "rid {rid} is documented as ab-only but cd uses it: {msg}");
        }
        for rid in CD_ONLY {
            assert!(
                cd.contains(&rid),
                "rid {rid} is documented as cd-only but cd never uses it: {msg}"
            );
            assert!(!ab.contains(&rid), "rid {rid} is documented as cd-only but ab uses it: {msg}");
        }
        for rid in BOTH {
            assert!(
                ab.contains(&rid) && cd.contains(&rid),
                "rid {rid} is documented as used by both: {msg}"
            );
        }
        // and the 17 rids are exactly accounted for
        let documented = AB_ONLY.len() + CD_ONLY.len() + BOTH.len();
        assert_eq!(documented, 17, "the rid table must cover all 17 rids");
        let used: std::collections::BTreeSet<u16> = ab.iter().chain(cd.iter()).copied().collect();
        assert_eq!(used.len(), 17, "every rid must be used by at least one view: {msg}");
    }

    #[test]
    fn carry_block_fits_in_the_air() {
        let last = CARRY_BASE - MIN_CARRY + MAX_CARRY;
        assert_eq!(last as usize, ROWS - 1, "the carry block must end on the last row");
        assert_eq!(
            ArithRangeTableHelpers::get_row_carry_range_check(MIN_CARRY),
            CARRY_BASE as usize
        );
        assert_eq!(ArithRangeTableHelpers::get_row_carry_range_check(MAX_CARRY), last as usize);
    }
}
