[package]
name = "zisk-definitions"
description = "Shared low-level definitions (syscalls, hints, labels) for the ZisK zkVM"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
categories = { workspace = true }

[lib]
name = "zisk_definitions"
path = "src/lib.rs"

[dependencies]

# QUIC networking

[features]
default = []
stats = []
