#!/usr/bin/env python3
"""mlbatch.py <curve> : emit the batched (multi-pair) Miller loop for bn254 / bls12_381.

Appended to the pre-optimization miller_loop.zisk and then run through zopt.py.
  zisklib_ml_batch_reset_<c>()            empty the batch
  zisklib_ml_batch_push_<c>(p, q)         add a pair (both non-identity, validated)
  zisklib_ml_batch_finish_<c>(dst)        dst = ∏ MillerLoop(p_i, q_i)  (1 if none)
The pairs share the f² of every iteration; each pair's state (R, the precomputed
P terms, the Q pointer) is swapped into the single-pair helpers' static buffers.
At most MLB_K pairs per run: a full batch is run and folded into an accumulator.
"""
import sys
c = sys.argv[1]
bls = c == 'bls12_381'
K = 8
P = 'BLS_ML_' if bls else 'ML_'
RW, XW, FW = (24, 12, 72) if bls else (16, 4, 48)
S = c
out = []
def w(s=''): out.append(s)
def raw(s): w('\t' + s)
def call(fn, *args):
    for r, a in zip(('r10', 'r11', 'r12'), args):
        raw(f'copyb(0, {a}) -> {r}')
    raw(f'call {fn}')
def cp(dst, src, nw): call('bn254_memcpy', src, dst, nw)
def slot(buf, idxslot, width, reg='r10'):
    """reg = buf + [idxslot]*width*8"""
    raw(f'copyb(0, [{idxslot}]) -> r6')
    bits = [b for b in range(16) if (width * 8) >> b & 1]
    raw(f'copyb(0, {buf}) -> {reg}')
    for b in bits:
        raw(f'sll(r6, {b}) -> r7')
        raw(f'add({reg}, r7) -> {reg}')

B = 'MLB_' if not bls else 'BMLB_'
L = 'mlb' if not bls else 'bmlb'
w(f'; ---- batched Miller loop (GENERATED by scripts/pairing/mlbatch.py) ----')
for n, sz in (('N', 1), ('I', 1), ('BIT', 1), ('FLAG', 1), ('SP', 1), ('SQ', 1), ('DST', 1),
              ('BP', K), ('BQ', K), ('BR', K * RW), ('BX', K * XW), ('BY', K * XW), ('TMP', FW), ('ACC', FW)):
    w(f'u64 {B}{n}[{sz}] = ' + ', '.join(['0'] * sz))
w(f'const u64 {B}ONE[{FW}] = 1' + ', 0' * (FW - 1))
w()

# ---- reset ----
w(f'; void zisklib_ml_batch_reset_{S}()')
w(f'zisklib_ml_batch_reset_{S}:')
raw(f'copyb(0, 0) -> [{B}N]'); raw(f'copyb(0, 0) -> [{B}FLAG]'); raw('ret'); w()

# ---- push ----
w(f'; void zisklib_ml_batch_push_{S}(const u64* p, const u64* q)  [r10=p, r11=q]')
w(f'zisklib_ml_batch_push_{S}:')
raw('push r1')
raw(f'copyb(0, r10) -> [{B}SP]'); raw(f'copyb(0, r11) -> [{B}SQ]')
raw(f'copyb(0, [{B}N]) -> r6')
raw(f'eq(r6, {K}), j({L}_push_full)')
w(f'{L}_push_add:')
raw(f'copyb(0, [{B}N]) -> r6'); raw('sll(r6, 3) -> r6')
raw(f'copyb(0, {B}BP) -> r7'); raw('add(r7, r6) -> r7'); raw(f'copyb(0, [{B}SP]) -> r5'); raw('copyb(r7, r5) -> 8[a + 0]')
raw(f'copyb(0, {B}BQ) -> r7'); raw('add(r7, r6) -> r7'); raw(f'copyb(0, [{B}SQ]) -> r5'); raw('copyb(r7, r5) -> 8[a + 0]')
raw(f'copyb(0, [{B}N]) -> r6'); raw('add(r6, 1) -> r6'); raw(f'copyb(0, r6) -> [{B}N]')
raw('pop r1'); raw('ret')
w(f'{L}_push_full:')
raw(f'call {L}_fold')
raw(f'jump({L}_push_add)')
w()

# ---- finish ----
w(f'; void zisklib_ml_batch_finish_{S}(u64* dst)  [r10=dst]')
w(f'zisklib_ml_batch_finish_{S}:')
raw('push r1')
raw(f'copyb(0, r10) -> [{B}DST]')
raw(f'copyb(0, [{B}N]) -> r6')
raw(f'eq(r6, 0), j({L}_fin_nofold)')
raw(f'call {L}_fold')
w(f'{L}_fin_nofold:')
raw(f'copyb(0, [{B}FLAG]) -> r6')
raw(f'eq(r6, 0), j({L}_fin_one)')
raw(f'copyb(0, [{B}DST]) -> r5'); raw(f'dma_xmemcpy(r5, {B}ACC) -> r5, j({FW * 8}, 4)')
raw(f'jump({L}_fin_done)')
w(f'{L}_fin_one:')
raw(f'copyb(0, [{B}DST]) -> r5'); raw(f'dma_xmemcpy(r5, {B}ONE) -> r5, j({FW * 8}, 4)')
w(f'{L}_fin_done:')
raw(f'copyb(0, 0) -> [{B}N]'); raw(f'copyb(0, 0) -> [{B}FLAG]')
raw('pop r1'); raw('ret')
w()

# ---- fold: TMP = run(batch) ; ACC = FLAG ? ACC*TMP : TMP ; N = 0 ----
w(f'{L}_fold:')
raw('push r1')
raw(f'call {L}_run')
raw(f'copyb(0, [{B}FLAG]) -> r6')
raw(f'eq(r6, 0), j({L}_fold_first)')
call(f'zisklib_mul_fp12_{S}', f'{B}ACC', f'{B}TMP', f'{B}ACC')
raw(f'jump({L}_fold_done)')
w(f'{L}_fold_first:')
raw(f'dma_xmemcpy({B}ACC, {B}TMP) -> r5, j({FW * 8}, 4)')
raw(f'copyb(0, 1) -> [{B}FLAG]')
w(f'{L}_fold_done:')
raw(f'copyb(0, 0) -> [{B}N]')
raw('pop r1'); raw('ret')
w()

# ---- run: TMP = ∏ MillerLoop over the N batched pairs ----
def swap_in():
    slot(f'{B}BR', f'{B}I', RW)
    raw(f'dma_xmemcpy({P}R, r10) -> r5, j({RW * 8}, 4)')
    slot(f'{B}BX', f'{B}I', XW); raw(f'dma_xmemcpy({P}XPP, r10) -> r5, j({XW * 8}, 4)')
    slot(f'{B}BY', f'{B}I', XW); raw(f'dma_xmemcpy({P}NEGYPP, r10) -> r5, j({XW * 8}, 4)')
    slot(f'{B}BQ', f'{B}I', 1); raw('copyb(r10, 8[a + 0]) -> r5'); raw(f'copyb(0, r5) -> [{P}Q]')
def swap_out():
    slot(f'{B}BR', f'{B}I', RW); raw(f'dma_xmemcpy(r10, {P}R) -> r5, j({RW * 8}, 4)')
def loadq(reg):
    raw(f'copyb(0, [{P}Q]) -> {reg}')
def add_step(q):
    """add line through R and q (q: static symbol or '*Q' = the pair's Q pointer)."""
    def qarg():
        if q == '*Q':
            loadq('r11')
        else:
            raw(f'copyb(0, {q}) -> r11')
    raw(f'copyb(0, {P}R) -> r10'); qarg(); raw(f'call zisklib_ml_add_coeffs_{S}')
    raw(f'copyb(0, {P}R) -> r10'); qarg(); raw(f'call zisklib_ml_is_line_{S}'); raw(f'eq(r10, 0), j({L}_bad)')
    raw(f'call zisklib_ml_line_eval_{S}')
    call(f'zisklib_sparse_mul_fp12_{S}', f'{P}F', f'{P}L', f'{P}F')
def add_wh(q):
    raw(f'copyb(0, {P}R) -> r10')
    loadq('r11') if q == '*Q' else raw(f'copyb(0, {q}) -> r11')
    raw(f'call zisklib_ml_add_wh_{S}')
    raw(f'dma_xmemcpy({P}R, {P}R2) -> r5, j({RW * 8}, 4)')
def pair_loop(tag, body):
    raw(f'copyb(0, 0) -> [{B}I]')
    w(f'{L}_{tag}_pl:')
    raw(f'copyb(0, [{B}I]) -> r6'); raw(f'copyb(0, [{B}N]) -> r7')
    raw(f'eq(r6, r7), j({L}_{tag}_pd)')
    body()
    raw(f'copyb(0, [{B}I]) -> r6'); raw('add(r6, 1) -> r6'); raw(f'copyb(0, r6) -> [{B}I]')
    raw(f'jump({L}_{tag}_pl)')
    w(f'{L}_{tag}_pd:')

w(f'{L}_run:')
raw('push r1')
# per-pair precompute
def pre():
    slot(f'{B}BP', f'{B}I', 1); raw('copyb(r10, 8[a + 0]) -> r5'); raw(f'copyb(0, r5) -> [{P}P]')
    if bls:
        raw(f'copyb(0, [{P}P]) -> r10'); raw('add(r10, 48) -> r10'); raw(f'copyb(0, {P}YP) -> r11'); raw(f'call zisklib_inv_fp_{S}')
        raw(f'copyb(0, [{P}P]) -> r10'); raw(f'copyb(0, {P}XP) -> r11'); raw(f'call zisklib_neg_fp_{S}')
        call(f'zisklib_mul_fp_{S}', f'{P}XP', f'{P}YP', f'{P}XP')
        call(f'zisklib_scalar_mul_fp2_{S}', 'BLS_EXT_U_INV', f'{P}XP', f'{P}XPP')
        call(f'zisklib_scalar_mul_fp2_{S}', 'BLS_EXT_U_INV', f'{P}YP', f'{P}YPP')
        call(f'zisklib_neg_fp2_{S}', f'{P}YPP', f'{P}NEGYPP')
    else:
        raw(f'copyb(0, [{P}P]) -> r10'); raw('add(r10, 32) -> r10'); raw(f'copyb(0, {P}YPP) -> r11'); raw(f'call zisklib_inv_fp_{S}')
        raw(f'copyb(0, [{P}P]) -> r10'); raw(f'copyb(0, {P}XPP) -> r11'); raw(f'call zisklib_neg_fp_{S}')
        call(f'zisklib_mul_fp_{S}', f'{P}XPP', f'{P}YPP', f'{P}XPP')
        call(f'zisklib_neg_fp_{S}', f'{P}YPP', f'{P}NEGYPP')
    slot(f'{B}BX', f'{B}I', XW); raw(f'dma_xmemcpy(r10, {P}XPP) -> r5, j({XW * 8}, 4)')
    slot(f'{B}BY', f'{B}I', XW); raw(f'dma_xmemcpy(r10, {P}NEGYPP) -> r5, j({XW * 8}, 4)')
    slot(f'{B}BQ', f'{B}I', 1); raw('copyb(r10, 8[a + 0]) -> r11')
    slot(f'{B}BR', f'{B}I', RW); raw(f'dma_xmemcpy(r10, r11) -> r5, j({RW * 8}, 4)')
pair_loop('pre', pre)
raw(f'dma_xmemcpy({P}F, {B}ONE) -> r5, j({FW * 8}, 4)')
raw(f'copyb(0, 1) -> [{B}BIT]')
w(f'{L}_loop:')
raw(f'copyb(0, [{B}BIT]) -> r6')
raw(f'eq(r6, {65 if not bls else 64}), j({L}_final)')
raw(f'eq(r6, 1), j({L}_nosq)')
call(f'zisklib_square_fp12_{S}', f'{P}F', f'{P}F')
w(f'{L}_nosq:')
def step():
    swap_in()
    raw(f'copyb(0, {P}R) -> r10'); raw(f'call zisklib_ml_dbl_coeffs_{S}')
    raw(f'copyb(0, {P}R) -> r10'); raw(f'call zisklib_ml_is_tangent_{S}'); raw(f'eq(r10, 0), j({L}_bad)')
    raw(f'call zisklib_ml_line_eval_{S}')
    call(f'zisklib_sparse_mul_fp12_{S}', f'{P}F', f'{P}L', f'{P}F')
    raw(f'copyb(0, {P}R) -> r10'); raw(f'call zisklib_ml_dbl_wh_{S}')
    raw(f'dma_xmemcpy({P}R, {P}R2) -> r5, j({RW * 8}, 4)')
    raw(f'copyb(0, [{B}BIT]) -> r6'); raw('sll(r6, 3) -> r6'); raw(f'copyb(0, {P}LOOP) -> r5'); raw('add(r5, r6) -> r5')
    raw('copyb(r5, 8[a + 0]) -> r6')
    raw(f'eq(r6, 0), j({L}_st_out)')
    if bls:
        add_step('*Q'); add_wh('*Q')
    else:
        raw(f'eq(r6, 1), j({L}_st_qpos)')
        loadq('r10'); raw(f'copyb(0, {P}QP) -> r11'); raw(f'call zisklib_neg_twist_{S}'); raw(f'jump({L}_st_qdone)')
        w(f'{L}_st_qpos:')
        loadq('r10'); raw(f'dma_xmemcpy({P}QP, r10) -> r5, j({RW * 8}, 4)')
        w(f'{L}_st_qdone:')
        add_step(f'{P}QP'); add_wh(f'{P}QP')
    w(f'{L}_st_out:')
    swap_out()
pair_loop('it', step)
raw(f'copyb(0, [{B}BIT]) -> r6'); raw('add(r6, 1) -> r6'); raw(f'copyb(0, r6) -> [{B}BIT]')
raw(f'jump({L}_loop)')
w(f'{L}_final:')
if bls:
    call(f'zisklib_conjugate_fp12_{S}', f'{P}F', f'{B}TMP')
else:
    def fin():
        swap_in()
        loadq('r10'); raw(f'copyb(0, {P}QF) -> r11'); raw(f'call zisklib_utf_endomorphism_twist_{S}')
        add_step(f'{P}QF'); add_wh(f'{P}QF')
        call(f'zisklib_utf_endomorphism_twist_{S}', f'{P}QF', f'{P}UT')
        call(f'zisklib_neg_twist_{S}', f'{P}UT', f'{P}QF2')
        add_step(f'{P}QF2')
    pair_loop('fin', fin)
    raw(f'dma_xmemcpy({B}TMP, {P}F) -> r5, j({FW * 8}, 4)')
raw('pop r1'); raw('ret')
w(f'{L}_bad:')
raw('copyb(0, 0) -> r10, end')
w()
print('\n'.join(out))
