[package]
name = "riscv2zisk"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[[bin]]
name = "riscv2zisk"
path = "src/bin/riscv2zisk.rs"

[dependencies]
zisk-definitions = { workspace = true }
zisk-core = { workspace = true }
transpilers-common = { workspace = true }

[build-dependencies]
lib-float = { workspace = true, optional = true }

[features]
default = []
zba = ["transpilers-common/zba", "zisk-core/zba"]
zbc = ["transpilers-common/zbc", "zisk-core/zbc"]
zbkc = ["transpilers-common/zbkc", "zisk-core/zbkc"]
zbkx = ["transpilers-common/zbkx", "zisk-core/zbkx"]
float = ["transpilers-common/float"]