//! A guest whose ROM is large and whose work is trivial. Reads a `seed: u64`, threads it
//! through every generated function in order, and commits `(seed, result)`.
//!
//! It exists for tests that need two programs with very different ROM sizes in one
//! process. The ROM histogram's size grows with the number of ROM instructions, and is
//! rounded up to `TRACE_SIZE_GRANULARITY` (about 1 MB, `emulator-asm/src/constants.hpp`),
//! so a second program only needs a bigger histogram than the first when its ROM is
//! larger by well over a hundred thousand instructions. None of the other test programs
//! that run on arbitrary input is that much larger than `fib_mod`.
//!
//! The functions are generated by `build.rs` and called through a table, so none is
//! inlined or dropped.

#![no_main]
ziskos::entrypoint!(main);

include!(concat!(env!("OUT_DIR"), "/functions.rs"));

fn main() {
    let seed: u64 = ziskos::io::read();
    let result = FUNCTIONS.iter().fold(seed, |x, f| f(x));
    ziskos::io::commit(&seed);
    ziskos::io::commit(&result);
}
