[package]
name = "transpilers-common"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[dependencies]
zisk-definitions = { workspace = true }
zisk-core = { workspace = true }
riscv = { workspace = true }
elf = "0.7.4"

[build-dependencies]
lib-float = { workspace = true, optional = true }

[features]
default = []
float = ["dep:lib-float", "lib-float/float", "riscv/float", "zisk-core/float"]
zba = ["riscv/zba", "zisk-core/zba"]
zbc = ["riscv/zbc", "zisk-core/zbc"]
zbkc = ["riscv/zbkc", "zisk-core/zbkc"]
zbkx = ["riscv/zbkx", "zisk-core/zbkx"]