// WARNING: This file has been autogenerated from the PILOUT file.
// Manual modifications are not recommended and may be overwritten.
use proofman_common::WitnessPilout;

pub const PILOUT_HASH: &[u8] = b"Zisk-hash";

//SUBPROOFS CONSTANTS

pub const MAIN_SUBPROOF_ID: &[usize] = &[0];

//AIR CONSTANTS

pub const MAIN_AIR_IDS: &[usize] = &[0];

pub struct Pilout;

impl Pilout {
    pub fn pilout() -> WitnessPilout {
        let mut pilout = WitnessPilout::new("Zisk", 2, PILOUT_HASH.to_vec());

        let air_group = pilout.add_air_group(Some("Main"));

        air_group.add_air(Some("Main"), 2097152);

        pilout
    }
}
