[package]
name = "ziskos"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[dependencies]
lib-c = { path = "../../lib-c" }
lazy_static = "1.5.0"
static_assertions = "1.1"
rand = "0.8.5"
getrandom = { version = "0.2", features = ["custom"] }
cfg-if = "1.0"
num-bigint = { workspace = true }
num-traits = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_vendor, values("zisk"))'] }