[workspace]
members = [
  "sha-hasher/host",
  "multiple-programs/host",
  "aggregation/host",
  "big-program/host",
  "hints/host",
  "hash/host",
  "hash/guest",
  "fibonacci/host",
  "fibonacci/guest",
  "merkle-tree/host",
  "gcd/host",
  "gcd/guest",
  "primes/host",
  "primes/guest",
  "collatz/host",
  "collatz/guest",
  "recurser/l2/host",
  "recurser/hash/host",
  "utils"
]

resolver = "2"

[profile.release]
opt-level = 3

[workspace.dependencies]
ziskos = { path = "../ziskos/entrypoint" }
zisk-sdk = { path = "../sdk" }
zisk-test-artifacts = { path = "../test-artifacts" }
examples-utils = { path = "utils"}
proofman-util = { git = "https://github.com/0xPolygonHermez/pil2-proofman.git", branch = "predev-1.0.0-beta-crates-io", version = "1.1.0-alpha" }
proofman-fields = { git = "https://github.com/0xPolygonHermez/pil2-proofman.git", branch = "predev-1.0.0-beta-crates-io", version = "1.1.0-alpha" }
