.intel_syntax noprefix
.code64

# @generated by frops-analyzer — FROPS multiplicity-count macros (x86-64).
# generated with: max-table=25165824 partition-bits=21 low-cap=4096 max-regions-per-op=4 table-cost=3 nodes=1
# One macro per operation:  FROP_<OP>  a, b, t0, t1
#   a, b  : operands (register or immediate, read-only).
#   t0,t1 : the only two registers the macro clobbers freely (plus FLAGS).
#           The overflow path additionally push/pops rax, rcx, rdx.
# Behaviour: if (op,a,b) is a FROP, mult[row] += 1; on u32 wrap (counter hits 0) the
# row offset is appended to the overflow vector. If not a FROP / op has no FROPS: nothing.

.extern frops_arith_mult
.extern frops_arith_overflow
.extern frops_arith_overflow_index
.extern frops_binary_basic_mult
.extern frops_binary_basic_overflow
.extern frops_binary_basic_overflow_index
.extern frops_binary_extension_mult
.extern frops_binary_extension_overflow
.extern frops_binary_extension_overflow_index

# ---- arith ----
.macro FROP_MULUH a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 69 | FROP+incr best 14 worst 75 (no overflow)
    mov     \t0, \a
    cmp     \t0, 517
    jae     .Lfrop_MULUH_n1_\@
    imul    \t0, \t0, 517
    mov     \t1, \b
    cmp     \t1, 517
    jae     .Lfrop_MULUH_n1_\@
    add     \t0, \t1
    jmp     .Lfrop_MULUH_incr_\@
.Lfrop_MULUH_n1_\@:
    mov     \t0, \a
    mov     \t1, 0xFFFFF000
    cmp     \t0, \t1
    jb     .Lfrop_MULUH_n2_\@
    mov     \t1, 0x100001000
    cmp     \t0, \t1
    jae     .Lfrop_MULUH_n2_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_MULUH_n2_\@
    mov     \t1, 0xFFFFF000
    sub     \t0, \t1
    shr     \t0, 3
    imul    \t0, \t0, 19
    mov     \t1, \b
    cmp     \t1, 19
    jae     .Lfrop_MULUH_n2_\@
    add     \t0, \t1
    add     \t0, 267289
    jmp     .Lfrop_MULUH_incr_\@
.Lfrop_MULUH_n2_\@:
    mov     \t0, \a
    mov     \t1, 0x11BC4E7A1FF93003
    cmp     \t0, \t1
    jb     .Lfrop_MULUH_n3_\@
    mov     \t1, 0x11BC4E7A1FF94003
    cmp     \t0, \t1
    jae     .Lfrop_MULUH_n3_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 3
    jne     .Lfrop_MULUH_n3_\@
    mov     \t1, 0x11BC4E7A1FF93003
    sub     \t0, \t1
    shr     \t0, 3
    imul    \t0, \t0, 2
    mov     \t1, \b
    cmp     \t1, 2
    jae     .Lfrop_MULUH_n3_\@
    add     \t0, \t1
    add     \t0, 286745
    jmp     .Lfrop_MULUH_incr_\@
.Lfrop_MULUH_n3_\@:
    mov     \t0, \a
    mov     \t1, 0x3FD8EE048ED3F003
    cmp     \t0, \t1
    jb     .Lfrop_MULUH_done_\@
    mov     \t1, 0x3FD8EE048ED40003
    cmp     \t0, \t1
    jae     .Lfrop_MULUH_done_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 3
    jne     .Lfrop_MULUH_done_\@
    mov     \t1, 0x3FD8EE048ED3F003
    sub     \t0, \t1
    shr     \t0, 3
    imul    \t0, \t0, 2
    mov     \t1, \b
    cmp     \t1, 2
    jae     .Lfrop_MULUH_done_\@
    add     \t0, \t1
    add     \t0, 287769
    jmp     .Lfrop_MULUH_incr_\@
.Lfrop_MULUH_incr_\@:
    lea     \t1, [rip + frops_arith_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_MULUH_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_arith_overflow]
    mov     ecx, dword ptr [rip + frops_arith_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_arith_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_MULUH_done_\@:
.endm

.macro FROP_MUL a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 58 | FROP+incr best 15 worst 63 (no overflow)
    mov     \t0, \a
    cmp     \t0, 2406
    jae     .Lfrop_MUL_n1_\@
    imul    \t0, \t0, 388
    mov     \t1, \b
    cmp     \t1, 388
    jae     .Lfrop_MUL_n1_\@
    add     \t0, \t1
    add     \t0, 288793
    jmp     .Lfrop_MUL_incr_\@
.Lfrop_MUL_n1_\@:
    mov     \t0, \a
    mov     \t1, 0xFFFFF000
    cmp     \t0, \t1
    jb     .Lfrop_MUL_n2_\@
    mov     \t1, 0x100001000
    cmp     \t0, \t1
    jae     .Lfrop_MUL_n2_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_MUL_n2_\@
    mov     \t1, 0xFFFFF000
    sub     \t0, \t1
    shr     \t0, 3
    imul    \t0, \t0, 19
    mov     \t1, \b
    cmp     \t1, 19
    jae     .Lfrop_MUL_n2_\@
    add     \t0, \t1
    add     \t0, 1222321
    jmp     .Lfrop_MUL_incr_\@
.Lfrop_MUL_n2_\@:
    mov     \t0, \a
    mov     \t1, 0x7FFFFFF001
    cmp     \t0, \t1
    jb     .Lfrop_MUL_n3_\@
    mov     \t1, 0x8000001001
    cmp     \t0, \t1
    jae     .Lfrop_MUL_n3_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 1
    jne     .Lfrop_MUL_n3_\@
    mov     \t1, 0x7FFFFFF001
    sub     \t0, \t1
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 2045
    jne     .Lfrop_MUL_n3_\@
    add     \t0, 1241777
    jmp     .Lfrop_MUL_incr_\@
.Lfrop_MUL_n3_\@:
    mov     \t0, \a
    mov     \t1, 0x3FE8000000000
    cmp     \t0, \t1
    jb     .Lfrop_MUL_done_\@
    mov     \t1, 0x3FE8000001000
    cmp     \t0, \t1
    jae     .Lfrop_MUL_done_\@
    mov     \t1, 0x3FE8000000000
    sub     \t0, \t1
    mov     \t1, \b
    cmp     \t1, 2045
    jne     .Lfrop_MUL_done_\@
    add     \t0, 1242801
    jmp     .Lfrop_MUL_incr_\@
.Lfrop_MUL_incr_\@:
    lea     \t1, [rip + frops_arith_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_MUL_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_arith_overflow]
    mov     ecx, dword ptr [rip + frops_arith_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_arith_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_MUL_done_\@:
.endm

.macro FROP_DIVU a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 9 | FROP+incr best 15 worst 15 (no overflow)
    mov     \t0, \a
    cmp     \t0, 1601
    jae     .Lfrop_DIVU_done_\@
    imul    \t0, \t0, 513
    mov     \t1, \b
    cmp     \t1, 513
    jae     .Lfrop_DIVU_done_\@
    add     \t0, \t1
    add     \t0, 1246897
    jmp     .Lfrop_DIVU_incr_\@
.Lfrop_DIVU_incr_\@:
    lea     \t1, [rip + frops_arith_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_DIVU_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_arith_overflow]
    mov     ecx, dword ptr [rip + frops_arith_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_arith_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_DIVU_done_\@:
.endm

.macro FROP_MULU a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_MULSUH a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_MULH a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_MUL_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_REMU a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_DIV a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_REM a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_DIVU_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_REMU_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_DIV_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_REM_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

# ---- binary_basic ----
.macro FROP_MINU a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 9 | FROP+incr best 14 worst 14 (no overflow)
    mov     \t0, \a
    cmp     \t0, 166
    jae     .Lfrop_MINU_done_\@
    imul    \t0, \t0, 69
    mov     \t1, \b
    cmp     \t1, 69
    jae     .Lfrop_MINU_done_\@
    add     \t0, \t1
    jmp     .Lfrop_MINU_incr_\@
.Lfrop_MINU_incr_\@:
    lea     \t1, [rip + frops_binary_basic_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_MINU_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_basic_overflow]
    mov     ecx, dword ptr [rip + frops_binary_basic_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_basic_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_MINU_done_\@:
.endm

.macro FROP_MAXU a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 9 | FROP+incr best 15 worst 15 (no overflow)
    mov     \t0, \a
    cmp     \t0, 104
    jae     .Lfrop_MAXU_done_\@
    imul    \t0, \t0, 18
    mov     \t1, \b
    cmp     \t1, 18
    jae     .Lfrop_MAXU_done_\@
    add     \t0, \t1
    add     \t0, 11454
    jmp     .Lfrop_MAXU_incr_\@
.Lfrop_MAXU_incr_\@:
    lea     \t1, [rip + frops_binary_basic_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_MAXU_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_basic_overflow]
    mov     ecx, dword ptr [rip + frops_binary_basic_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_basic_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_MAXU_done_\@:
.endm

.macro FROP_LTU a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 9 | FROP+incr best 15 worst 15 (no overflow)
    mov     \t0, \a
    cmp     \t0, 1026
    jae     .Lfrop_LTU_done_\@
    imul    \t0, \t0, 1026
    mov     \t1, \b
    cmp     \t1, 1026
    jae     .Lfrop_LTU_done_\@
    add     \t0, \t1
    add     \t0, 13326
    jmp     .Lfrop_LTU_incr_\@
.Lfrop_LTU_incr_\@:
    lea     \t1, [rip + frops_binary_basic_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_LTU_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_basic_overflow]
    mov     ecx, dword ptr [rip + frops_binary_basic_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_basic_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_LTU_done_\@:
.endm

.macro FROP_LT a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 50 | FROP+incr best 15 worst 56 (no overflow)
    mov     \t0, \a
    cmp     \t0, 537
    jae     .Lfrop_LT_n1_\@
    imul    \t0, \t0, 128
    mov     \t1, \b
    cmp     \t1, 128
    jae     .Lfrop_LT_n1_\@
    add     \t0, \t1
    add     \t0, 1066002
    jmp     .Lfrop_LT_incr_\@
.Lfrop_LT_n1_\@:
    mov     \t0, \a
    mov     \t1, 0x7FFFFFFFFFFFF000
    cmp     \t0, \t1
    jb     .Lfrop_LT_n2_\@
    mov     \t1, 0x8000000000001000
    cmp     \t0, \t1
    jae     .Lfrop_LT_n2_\@
    mov     \t1, 0x7FFFFFFFFFFFF000
    sub     \t0, \t1
    mov     \t1, \b
    cmp     \t1, 0
    jne     .Lfrop_LT_n2_\@
    add     \t0, 1134738
    jmp     .Lfrop_LT_incr_\@
.Lfrop_LT_n2_\@:
    mov     \t0, \a
    mov     \t1, 0x9400000000000000
    cmp     \t0, \t1
    jb     .Lfrop_LT_n3_\@
    mov     \t1, 0x9400000000001000
    cmp     \t0, \t1
    jae     .Lfrop_LT_n3_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_LT_n3_\@
    mov     \t1, 0x9400000000000000
    sub     \t0, \t1
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 0
    jne     .Lfrop_LT_n3_\@
    add     \t0, 1142930
    jmp     .Lfrop_LT_incr_\@
.Lfrop_LT_n3_\@:
    mov     \t0, \a
    mov     \t1, 0xFFFFFFFFFFFAC847
    cmp     \t0, \t1
    jb     .Lfrop_LT_done_\@
    mov     \t1, 0xFFFFFFFFFFFAC847
    sub     \t0, \t1
    imul    \t0, \t0, 2
    mov     \t1, \b
    cmp     \t1, 2
    jae     .Lfrop_LT_done_\@
    add     \t0, \t1
    add     \t0, 1143442
    jmp     .Lfrop_LT_incr_\@
.Lfrop_LT_incr_\@:
    lea     \t1, [rip + frops_binary_basic_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_LT_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_basic_overflow]
    mov     ecx, dword ptr [rip + frops_binary_basic_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_basic_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_LT_done_\@:
.endm

.macro FROP_EQ a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 63 | FROP+incr best 15 worst 68 (no overflow)
    mov     \t0, \a
    cmp     \t0, 534
    jae     .Lfrop_EQ_n1_\@
    imul    \t0, \t0, 1026
    mov     \t1, \b
    cmp     \t1, 1026
    jae     .Lfrop_EQ_n1_\@
    add     \t0, \t1
    add     \t0, 1827332
    jmp     .Lfrop_EQ_incr_\@
.Lfrop_EQ_n1_\@:
    mov     \t0, \a
    mov     \t1, 0x43E1F593F0000001
    cmp     \t0, \t1
    jb     .Lfrop_EQ_n2_\@
    mov     \t1, 0x43E1F593F0001001
    cmp     \t0, \t1
    jae     .Lfrop_EQ_n2_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 1
    jne     .Lfrop_EQ_n2_\@
    mov     \t1, 0x43E1F593F0000001
    sub     \t0, \t1
    shr     \t0, 3
    imul    \t0, \t0, 2
    mov     \t1, \b
    cmp     \t1, 2
    jae     .Lfrop_EQ_n2_\@
    add     \t0, \t1
    add     \t0, 2375216
    jmp     .Lfrop_EQ_incr_\@
.Lfrop_EQ_n2_\@:
    mov     \t0, \a
    mov     \t1, 0x8080808080808000
    cmp     \t0, \t1
    jb     .Lfrop_EQ_n3_\@
    mov     \t1, 0x8080808080809000
    cmp     \t0, \t1
    jae     .Lfrop_EQ_n3_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_EQ_n3_\@
    mov     \t1, 0x8080808080808000
    sub     \t0, \t1
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 0
    jne     .Lfrop_EQ_n3_\@
    add     \t0, 2376240
    jmp     .Lfrop_EQ_incr_\@
.Lfrop_EQ_n3_\@:
    mov     \t0, \a
    mov     \t1, 0xFBF7FFFFF9B9F005
    cmp     \t0, \t1
    jb     .Lfrop_EQ_done_\@
    mov     \t1, 0xFBF7FFFFF9BA0005
    cmp     \t0, \t1
    jae     .Lfrop_EQ_done_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 5
    jne     .Lfrop_EQ_done_\@
    mov     \t1, 0xFBF7FFFFF9B9F005
    sub     \t0, \t1
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 0
    jne     .Lfrop_EQ_done_\@
    add     \t0, 2376752
    jmp     .Lfrop_EQ_incr_\@
.Lfrop_EQ_incr_\@:
    lea     \t1, [rip + frops_binary_basic_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_EQ_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_basic_overflow]
    mov     ecx, dword ptr [rip + frops_binary_basic_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_basic_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_EQ_done_\@:
.endm

.macro FROP_ADD a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 60 | FROP+incr best 15 worst 65 (no overflow)
    mov     \t0, \a
    cmp     \t0, 547
    jae     .Lfrop_ADD_n1_\@
    imul    \t0, \t0, 534
    mov     \t1, \b
    cmp     \t1, 534
    jae     .Lfrop_ADD_n1_\@
    add     \t0, \t1
    add     \t0, 2377264
    jmp     .Lfrop_ADD_incr_\@
.Lfrop_ADD_n1_\@:
    mov     \t0, \a
    cmp     \t0, 0x100F000
    jb     .Lfrop_ADD_n2_\@
    cmp     \t0, 0x1011000
    jae     .Lfrop_ADD_n2_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_ADD_n2_\@
    sub     \t0, 0x100F000
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 257
    jne     .Lfrop_ADD_n2_\@
    add     \t0, 2669362
    jmp     .Lfrop_ADD_incr_\@
.Lfrop_ADD_n2_\@:
    mov     \t0, \a
    mov     \t1, 0xA03F3000
    cmp     \t0, \t1
    jb     .Lfrop_ADD_n3_\@
    mov     \t1, 0xA03FC000
    cmp     \t0, \t1
    jae     .Lfrop_ADD_n3_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_ADD_n3_\@
    mov     \t1, 0xA03F3000
    sub     \t0, \t1
    shr     \t0, 3
    imul    \t0, \t0, 2048
    mov     \t1, \b
    cmp     \t1, 2048
    jae     .Lfrop_ADD_n3_\@
    add     \t0, \t1
    add     \t0, 2670386
    jmp     .Lfrop_ADD_incr_\@
.Lfrop_ADD_n3_\@:
    mov     \t0, \a
    mov     \t1, 0xFFFFFFFF80808000
    cmp     \t0, \t1
    jb     .Lfrop_ADD_done_\@
    mov     \t1, 0xFFFFFFFF80809000
    cmp     \t0, \t1
    jae     .Lfrop_ADD_done_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_ADD_done_\@
    mov     \t1, 0xFFFFFFFF80808000
    sub     \t0, \t1
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 128
    jne     .Lfrop_ADD_done_\@
    add     \t0, 12107570
    jmp     .Lfrop_ADD_incr_\@
.Lfrop_ADD_incr_\@:
    lea     \t1, [rip + frops_binary_basic_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_ADD_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_basic_overflow]
    mov     ecx, dword ptr [rip + frops_binary_basic_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_basic_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_ADD_done_\@:
.endm

.macro FROP_SUB a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 63 | FROP+incr best 15 worst 68 (no overflow)
    mov     \t0, \a
    cmp     \t0, 534
    jae     .Lfrop_SUB_n1_\@
    imul    \t0, \t0, 532
    mov     \t1, \b
    cmp     \t1, 532
    jae     .Lfrop_SUB_n1_\@
    add     \t0, \t1
    add     \t0, 12108082
    jmp     .Lfrop_SUB_incr_\@
.Lfrop_SUB_n1_\@:
    mov     \t0, \a
    mov     \t1, 0xA03F5000
    cmp     \t0, \t1
    jb     .Lfrop_SUB_n2_\@
    mov     \t1, 0xA03FC000
    cmp     \t0, \t1
    jae     .Lfrop_SUB_n2_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_SUB_n2_\@
    mov     \t1, 0xA03F5000
    sub     \t0, \t1
    shr     \t0, 3
    imul    \t0, \t0, 33
    mov     \t1, \b
    cmp     \t1, 33
    jae     .Lfrop_SUB_n2_\@
    add     \t0, \t1
    add     \t0, 12392170
    jmp     .Lfrop_SUB_incr_\@
.Lfrop_SUB_n2_\@:
    mov     \t0, \a
    mov     \t1, 0xAF89EFC2C1EA000
    cmp     \t0, \t1
    jb     .Lfrop_SUB_n3_\@
    mov     \t1, 0xAF89EFC2C1EB000
    cmp     \t0, \t1
    jae     .Lfrop_SUB_n3_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_SUB_n3_\@
    mov     \t1, 0xAF89EFC2C1EA000
    sub     \t0, \t1
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 0
    jne     .Lfrop_SUB_n3_\@
    add     \t0, 12510442
    jmp     .Lfrop_SUB_incr_\@
.Lfrop_SUB_n3_\@:
    mov     \t0, \a
    mov     \t1, 0x2725DD1D243AB006
    cmp     \t0, \t1
    jb     .Lfrop_SUB_done_\@
    mov     \t1, 0x2725DD1D243AC006
    cmp     \t0, \t1
    jae     .Lfrop_SUB_done_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 6
    jne     .Lfrop_SUB_done_\@
    mov     \t1, 0x2725DD1D243AB006
    sub     \t0, \t1
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 0
    jne     .Lfrop_SUB_done_\@
    add     \t0, 12510954
    jmp     .Lfrop_SUB_incr_\@
.Lfrop_SUB_incr_\@:
    lea     \t1, [rip + frops_binary_basic_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_SUB_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_basic_overflow]
    mov     ecx, dword ptr [rip + frops_binary_basic_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_basic_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_SUB_done_\@:
.endm

.macro FROP_AND a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 44 | FROP+incr best 15 worst 50 (no overflow)
    mov     \t0, \a
    cmp     \t0, 1190
    jae     .Lfrop_AND_n1_\@
    imul    \t0, \t0, 256
    mov     \t1, \b
    cmp     \t1, 256
    jae     .Lfrop_AND_n1_\@
    add     \t0, \t1
    add     \t0, 12511466
    jmp     .Lfrop_AND_incr_\@
.Lfrop_AND_n1_\@:
    mov     \t0, \a
    mov     \t1, 0x1FFFFFFF007
    cmp     \t0, \t1
    jb     .Lfrop_AND_n2_\@
    mov     \t1, 0x20000000007
    cmp     \t0, \t1
    jae     .Lfrop_AND_n2_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 7
    jne     .Lfrop_AND_n2_\@
    mov     \t1, 0x1FFFFFFF007
    sub     \t0, \t1
    shr     \t0, 3
    imul    \t0, \t0, 3
    mov     \t1, \b
    cmp     \t1, 3
    jae     .Lfrop_AND_n2_\@
    add     \t0, \t1
    add     \t0, 12816106
    jmp     .Lfrop_AND_incr_\@
.Lfrop_AND_n2_\@:
    mov     \t0, \a
    mov     \t1, 0x7FFFFFFFFFFFF000
    cmp     \t0, \t1
    jb     .Lfrop_AND_done_\@
    mov     \t1, 0x8000000000001000
    cmp     \t0, \t1
    jae     .Lfrop_AND_done_\@
    mov     \t1, 0x7FFFFFFFFFFFF000
    sub     \t0, \t1
    imul    \t0, \t0, 4
    mov     \t1, \b
    cmp     \t1, 4
    jae     .Lfrop_AND_done_\@
    add     \t0, \t1
    add     \t0, 12817642
    jmp     .Lfrop_AND_incr_\@
.Lfrop_AND_incr_\@:
    lea     \t1, [rip + frops_binary_basic_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_AND_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_basic_overflow]
    mov     ecx, dword ptr [rip + frops_binary_basic_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_basic_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_AND_done_\@:
.endm

.macro FROP_OR a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 57 | FROP+incr best 15 worst 62 (no overflow)
    mov     \t0, \a
    cmp     \t0, 1541
    jae     .Lfrop_OR_n1_\@
    imul    \t0, \t0, 267
    mov     \t1, \b
    cmp     \t1, 267
    jae     .Lfrop_OR_n1_\@
    add     \t0, \t1
    add     \t0, 12850410
    jmp     .Lfrop_OR_incr_\@
.Lfrop_OR_n1_\@:
    mov     \t0, \a
    cmp     \t0, 4096
    jb     .Lfrop_OR_n2_\@
    cmp     \t0, 0x10000
    jae     .Lfrop_OR_n2_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_OR_n2_\@
    sub     \t0, 4096
    shr     \t0, 3
    imul    \t0, \t0, 690
    mov     \t1, \b
    cmp     \t1, 690
    jae     .Lfrop_OR_n2_\@
    add     \t0, \t1
    add     \t0, 13261857
    jmp     .Lfrop_OR_incr_\@
.Lfrop_OR_n2_\@:
    mov     \t0, \a
    cmp     \t0, 0x4C440000
    jb     .Lfrop_OR_n3_\@
    cmp     \t0, 0x4C441000
    jae     .Lfrop_OR_n3_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_OR_n3_\@
    sub     \t0, 0x4C440000
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 1024
    jne     .Lfrop_OR_n3_\@
    add     \t0, 18561057
    jmp     .Lfrop_OR_incr_\@
.Lfrop_OR_n3_\@:
    mov     \t0, \a
    mov     \t1, 0xA0110000
    cmp     \t0, \t1
    jb     .Lfrop_OR_done_\@
    mov     \t1, 0xA0111000
    cmp     \t0, \t1
    jae     .Lfrop_OR_done_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_OR_done_\@
    mov     \t1, 0xA0110000
    sub     \t0, \t1
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 761
    jne     .Lfrop_OR_done_\@
    add     \t0, 18561569
    jmp     .Lfrop_OR_incr_\@
.Lfrop_OR_incr_\@:
    lea     \t1, [rip + frops_binary_basic_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_OR_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_basic_overflow]
    mov     ecx, dword ptr [rip + frops_binary_basic_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_basic_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_OR_done_\@:
.endm

.macro FROP_XOR a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 9 | FROP+incr best 15 worst 15 (no overflow)
    mov     \t0, \a
    cmp     \t0, 255
    jae     .Lfrop_XOR_done_\@
    imul    \t0, \t0, 260
    mov     \t1, \b
    cmp     \t1, 260
    jae     .Lfrop_XOR_done_\@
    add     \t0, \t1
    add     \t0, 18562081
    jmp     .Lfrop_XOR_incr_\@
.Lfrop_XOR_incr_\@:
    lea     \t1, [rip + frops_binary_basic_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_XOR_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_basic_overflow]
    mov     ecx, dword ptr [rip + frops_binary_basic_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_basic_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_XOR_done_\@:
.endm

.macro FROP_ADD_W a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 18 | FROP+incr best 15 worst 23 (no overflow)
    mov     \t0, \a
    cmp     \t0, 256
    jae     .Lfrop_ADD_W_n1_\@
    imul    \t0, \t0, 8
    mov     \t1, \b
    cmp     \t1, 8
    jae     .Lfrop_ADD_W_n1_\@
    add     \t0, \t1
    add     \t0, 18628381
    jmp     .Lfrop_ADD_W_incr_\@
.Lfrop_ADD_W_n1_\@:
    mov     \t0, \a
    mov     \t1, 0xFFFFFFFFFFFFFF01
    cmp     \t0, \t1
    jb     .Lfrop_ADD_W_done_\@
    mov     \t1, 0xFFFFFFFFFFFFFF01
    sub     \t0, \t1
    mov     \t1, \b
    cmp     \t1, 0
    jne     .Lfrop_ADD_W_done_\@
    add     \t0, 18630429
    jmp     .Lfrop_ADD_W_incr_\@
.Lfrop_ADD_W_incr_\@:
    lea     \t1, [rip + frops_binary_basic_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_ADD_W_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_basic_overflow]
    mov     ecx, dword ptr [rip + frops_binary_basic_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_basic_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_ADD_W_done_\@:
.endm

.macro FROP_SUB_W a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 9 | FROP+incr best 15 worst 15 (no overflow)
    mov     \t0, \a
    cmp     \t0, 129
    jae     .Lfrop_SUB_W_done_\@
    imul    \t0, \t0, 256
    mov     \t1, \b
    cmp     \t1, 256
    jae     .Lfrop_SUB_W_done_\@
    add     \t0, \t1
    add     \t0, 18630684
    jmp     .Lfrop_SUB_W_incr_\@
.Lfrop_SUB_W_incr_\@:
    lea     \t1, [rip + frops_binary_basic_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_SUB_W_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_basic_overflow]
    mov     ecx, dword ptr [rip + frops_binary_basic_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_basic_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_SUB_W_done_\@:
.endm

.macro FROP_ANDN a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 9 | FROP+incr best 15 worst 15 (no overflow)
    mov     \t0, \a
    cmp     \t0, 3
    jae     .Lfrop_ANDN_done_\@
    imul    \t0, \t0, 13
    mov     \t1, \b
    cmp     \t1, 13
    jae     .Lfrop_ANDN_done_\@
    add     \t0, \t1
    add     \t0, 18663708
    jmp     .Lfrop_ANDN_incr_\@
.Lfrop_ANDN_incr_\@:
    lea     \t1, [rip + frops_binary_basic_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_ANDN_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_basic_overflow]
    mov     ecx, dword ptr [rip + frops_binary_basic_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_basic_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_ANDN_done_\@:
.endm

.macro FROP_ORN a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 15 | FROP+incr best 11 worst 20 (no overflow)
    mov     \t0, \a
    cmp     \t0, 63
    jae     .Lfrop_ORN_n1_\@
    mov     \t1, \b
    cmp     \t1, 0
    jne     .Lfrop_ORN_n1_\@
    add     \t0, 18663747
    jmp     .Lfrop_ORN_incr_\@
.Lfrop_ORN_n1_\@:
    mov     \t0, \a
    mov     \t1, 0xFFFFFFFFFFFFFFFF
    cmp     \t0, \t1
    jb     .Lfrop_ORN_done_\@
    mov     \t1, 0xFFFFFFFFFFFFFFFF
    sub     \t0, \t1
    mov     \t1, \b
    cmp     \t1, 0
    jne     .Lfrop_ORN_done_\@
    add     \t0, 18663810
    jmp     .Lfrop_ORN_incr_\@
.Lfrop_ORN_incr_\@:
    lea     \t1, [rip + frops_binary_basic_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_ORN_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_basic_overflow]
    mov     ecx, dword ptr [rip + frops_binary_basic_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_basic_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_ORN_done_\@:
.endm

.macro FROP_MIN a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_MAX a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_LEU a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_LE a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_MINU_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_MIN_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_MAXU_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_MAX_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_LTU_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_LT_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_EQ_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_LEU_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_LE_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_BREV8 a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_XNOR a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

# ---- binary_extension ----
.macro FROP_SLL a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 63 | FROP+incr best 14 worst 68 (no overflow)
    mov     \t0, \a
    cmp     \t0, 4096
    jae     .Lfrop_SLL_n1_\@
    imul    \t0, \t0, 161
    mov     \t1, \b
    cmp     \t1, 161
    jae     .Lfrop_SLL_n1_\@
    add     \t0, \t1
    jmp     .Lfrop_SLL_incr_\@
.Lfrop_SLL_n1_\@:
    mov     \t0, \a
    cmp     \t0, 4096
    jb     .Lfrop_SLL_n2_\@
    cmp     \t0, 0x10000
    jae     .Lfrop_SLL_n2_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_SLL_n2_\@
    sub     \t0, 4096
    shr     \t0, 3
    imul    \t0, \t0, 243
    mov     \t1, \b
    cmp     \t1, 243
    jae     .Lfrop_SLL_n2_\@
    add     \t0, \t1
    add     \t0, 659456
    jmp     .Lfrop_SLL_incr_\@
.Lfrop_SLL_n2_\@:
    mov     \t0, \a
    mov     \t1, 0xFFFFF007
    cmp     \t0, \t1
    jb     .Lfrop_SLL_n3_\@
    mov     \t1, 0x100000007
    cmp     \t0, \t1
    jae     .Lfrop_SLL_n3_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 7
    jne     .Lfrop_SLL_n3_\@
    mov     \t1, 0xFFFFF007
    sub     \t0, \t1
    shr     \t0, 3
    imul    \t0, \t0, 225
    mov     \t1, \b
    cmp     \t1, 225
    jae     .Lfrop_SLL_n3_\@
    add     \t0, \t1
    add     \t0, 2525696
    jmp     .Lfrop_SLL_incr_\@
.Lfrop_SLL_n3_\@:
    mov     \t0, \a
    mov     \t1, 0xFFFFFFFFFEFEF007
    cmp     \t0, \t1
    jb     .Lfrop_SLL_done_\@
    mov     \t1, 0xFFFFFFFFFEFF0007
    cmp     \t0, \t1
    jae     .Lfrop_SLL_done_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 7
    jne     .Lfrop_SLL_done_\@
    mov     \t1, 0xFFFFFFFFFEFEF007
    sub     \t0, \t1
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 32
    jne     .Lfrop_SLL_done_\@
    add     \t0, 2640896
    jmp     .Lfrop_SLL_incr_\@
.Lfrop_SLL_incr_\@:
    lea     \t1, [rip + frops_binary_extension_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_SLL_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_extension_overflow]
    mov     ecx, dword ptr [rip + frops_binary_extension_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_extension_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_SLL_done_\@:
.endm

.macro FROP_SRL a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 75 | FROP+incr best 15 worst 82 (no overflow)
    mov     \t0, \a
    cmp     \t0, 4096
    jae     .Lfrop_SRL_n1_\@
    imul    \t0, \t0, 65
    mov     \t1, \b
    cmp     \t1, 65
    jae     .Lfrop_SRL_n1_\@
    add     \t0, \t1
    add     \t0, 2641408
    jmp     .Lfrop_SRL_incr_\@
.Lfrop_SRL_n1_\@:
    mov     \t0, \a
    mov     \t1, 0xFFFFFFFFFFF000
    cmp     \t0, \t1
    jb     .Lfrop_SRL_n2_\@
    mov     \t1, 0x100000000001000
    cmp     \t0, \t1
    jae     .Lfrop_SRL_n2_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_SRL_n2_\@
    mov     \t1, 0xFFFFFFFFFFF000
    sub     \t0, \t1
    shr     \t0, 3
    imul    \t0, \t0, 120
    mov     \t1, \b
    cmp     \t1, 1
    jb     .Lfrop_SRL_n2_\@
    cmp     \t1, 121
    jae     .Lfrop_SRL_n2_\@
    sub     \t1, 1
    add     \t0, \t1
    add     \t0, 2907648
    jmp     .Lfrop_SRL_incr_\@
.Lfrop_SRL_n2_\@:
    mov     \t0, \a
    mov     \t1, 0x1102000000000000
    cmp     \t0, \t1
    jb     .Lfrop_SRL_n3_\@
    mov     \t1, 0x1102000000001000
    cmp     \t0, \t1
    jae     .Lfrop_SRL_n3_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_SRL_n3_\@
    mov     \t1, 0x1102000000000000
    sub     \t0, \t1
    shr     \t0, 3
    imul    \t0, \t0, 49
    mov     \t1, \b
    cmp     \t1, 8
    jb     .Lfrop_SRL_n3_\@
    cmp     \t1, 57
    jae     .Lfrop_SRL_n3_\@
    sub     \t1, 8
    add     \t0, \t1
    add     \t0, 3030528
    jmp     .Lfrop_SRL_incr_\@
.Lfrop_SRL_n3_\@:
    mov     \t0, \a
    mov     \t1, 0xFFFFFFFF00000000
    cmp     \t0, \t1
    jb     .Lfrop_SRL_done_\@
    mov     \t1, 0xFFFFFFFF00001000
    cmp     \t0, \t1
    jae     .Lfrop_SRL_done_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_SRL_done_\@
    mov     \t1, 0xFFFFFFFF00000000
    sub     \t0, \t1
    shr     \t0, 3
    imul    \t0, \t0, 49
    mov     \t1, \b
    cmp     \t1, 8
    jb     .Lfrop_SRL_done_\@
    cmp     \t1, 57
    jae     .Lfrop_SRL_done_\@
    sub     \t1, 8
    add     \t0, \t1
    add     \t0, 3055616
    jmp     .Lfrop_SRL_incr_\@
.Lfrop_SRL_incr_\@:
    lea     \t1, [rip + frops_binary_extension_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_SRL_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_extension_overflow]
    mov     ecx, dword ptr [rip + frops_binary_extension_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_extension_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_SRL_done_\@:
.endm

.macro FROP_SRA a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 57 | FROP+incr best 15 worst 62 (no overflow)
    mov     \t0, \a
    cmp     \t0, 4096
    jae     .Lfrop_SRA_n1_\@
    imul    \t0, \t0, 64
    mov     \t1, \b
    cmp     \t1, 64
    jae     .Lfrop_SRA_n1_\@
    add     \t0, \t1
    add     \t0, 3080704
    jmp     .Lfrop_SRA_incr_\@
.Lfrop_SRA_n1_\@:
    mov     \t0, \a
    cmp     \t0, 4096
    jb     .Lfrop_SRA_n2_\@
    cmp     \t0, 24576
    jae     .Lfrop_SRA_n2_\@
    sub     \t0, 4096
    imul    \t0, \t0, 3
    mov     \t1, \b
    cmp     \t1, 3
    jb     .Lfrop_SRA_n2_\@
    cmp     \t1, 6
    jae     .Lfrop_SRA_n2_\@
    sub     \t1, 3
    add     \t0, \t1
    add     \t0, 3342848
    jmp     .Lfrop_SRA_incr_\@
.Lfrop_SRA_n2_\@:
    mov     \t0, \a
    mov     \t1, 0x6000000000000000
    cmp     \t0, \t1
    jb     .Lfrop_SRA_n3_\@
    mov     \t1, 0x6000000000001000
    cmp     \t0, \t1
    jae     .Lfrop_SRA_n3_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_SRA_n3_\@
    mov     \t1, 0x6000000000000000
    sub     \t0, \t1
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 56
    jne     .Lfrop_SRA_n3_\@
    add     \t0, 3404288
    jmp     .Lfrop_SRA_incr_\@
.Lfrop_SRA_n3_\@:
    mov     \t0, \a
    mov     \t1, 0x6100000000000000
    cmp     \t0, \t1
    jb     .Lfrop_SRA_done_\@
    mov     \t1, 0x6100000000001000
    cmp     \t0, \t1
    jae     .Lfrop_SRA_done_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_SRA_done_\@
    mov     \t1, 0x6100000000000000
    sub     \t0, \t1
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 56
    jne     .Lfrop_SRA_done_\@
    add     \t0, 3404800
    jmp     .Lfrop_SRA_incr_\@
.Lfrop_SRA_incr_\@:
    lea     \t1, [rip + frops_binary_extension_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_SRA_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_extension_overflow]
    mov     ecx, dword ptr [rip + frops_binary_extension_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_extension_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_SRA_done_\@:
.endm

.macro FROP_SRL_W a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 60 | FROP+incr best 15 worst 65 (no overflow)
    mov     \t0, \a
    cmp     \t0, 530
    jae     .Lfrop_SRL_W_n1_\@
    imul    \t0, \t0, 32
    mov     \t1, \b
    cmp     \t1, 32
    jae     .Lfrop_SRL_W_n1_\@
    add     \t0, \t1
    add     \t0, 3405312
    jmp     .Lfrop_SRL_W_incr_\@
.Lfrop_SRL_W_n1_\@:
    mov     \t0, \a
    mov     \t1, 0xFFFFA007
    cmp     \t0, \t1
    jb     .Lfrop_SRL_W_n2_\@
    mov     \t1, 0x100000007
    cmp     \t0, \t1
    jae     .Lfrop_SRL_W_n2_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 7
    jne     .Lfrop_SRL_W_n2_\@
    mov     \t1, 0xFFFFA007
    sub     \t0, \t1
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 24
    jne     .Lfrop_SRL_W_n2_\@
    add     \t0, 3422272
    jmp     .Lfrop_SRL_W_incr_\@
.Lfrop_SRL_W_n2_\@:
    mov     \t0, \a
    mov     \t1, 0x11020000000000
    cmp     \t0, \t1
    jb     .Lfrop_SRL_W_n3_\@
    mov     \t1, 0x11020000001000
    cmp     \t0, \t1
    jae     .Lfrop_SRL_W_n3_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_SRL_W_n3_\@
    mov     \t1, 0x11020000000000
    sub     \t0, \t1
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 24
    jne     .Lfrop_SRL_W_n3_\@
    add     \t0, 3425344
    jmp     .Lfrop_SRL_W_incr_\@
.Lfrop_SRL_W_n3_\@:
    mov     \t0, \a
    mov     \t1, 0x1102000000000000
    cmp     \t0, \t1
    jb     .Lfrop_SRL_W_done_\@
    mov     \t1, 0x1102000000001000
    cmp     \t0, \t1
    jae     .Lfrop_SRL_W_done_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_SRL_W_done_\@
    mov     \t1, 0x1102000000000000
    sub     \t0, \t1
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 24
    jne     .Lfrop_SRL_W_done_\@
    add     \t0, 3425856
    jmp     .Lfrop_SRL_W_incr_\@
.Lfrop_SRL_W_incr_\@:
    lea     \t1, [rip + frops_binary_extension_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_SRL_W_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_extension_overflow]
    mov     ecx, dword ptr [rip + frops_binary_extension_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_extension_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_SRL_W_done_\@:
.endm

.macro FROP_SRA_W a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 9 | FROP+incr best 15 worst 15 (no overflow)
    mov     \t0, \a
    cmp     \t0, 25
    jae     .Lfrop_SRA_W_done_\@
    imul    \t0, \t0, 32
    mov     \t1, \b
    cmp     \t1, 32
    jae     .Lfrop_SRA_W_done_\@
    add     \t0, \t1
    add     \t0, 3426368
    jmp     .Lfrop_SRA_W_incr_\@
.Lfrop_SRA_W_incr_\@:
    lea     \t1, [rip + frops_binary_extension_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_SRA_W_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_extension_overflow]
    mov     ecx, dword ptr [rip + frops_binary_extension_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_extension_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_SRA_W_done_\@:
.endm

.macro FROP_SIGNEXTEND_B a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 9 | FROP+incr best 15 worst 15 (no overflow)
    mov     \t0, \a
    cmp     \t0, 1
    jae     .Lfrop_SIGNEXTEND_B_done_\@
    imul    \t0, \t0, 256
    mov     \t1, \b
    cmp     \t1, 256
    jae     .Lfrop_SIGNEXTEND_B_done_\@
    add     \t0, \t1
    add     \t0, 3427168
    jmp     .Lfrop_SIGNEXTEND_B_incr_\@
.Lfrop_SIGNEXTEND_B_incr_\@:
    lea     \t1, [rip + frops_binary_extension_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_SIGNEXTEND_B_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_extension_overflow]
    mov     ecx, dword ptr [rip + frops_binary_extension_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_extension_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_SIGNEXTEND_B_done_\@:
.endm

.macro FROP_SIGNEXTEND_W a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 17 | FROP+incr best 22 worst 22 (no overflow)
    mov     \t0, \a
    mov     \t1, 0x804DB000
    cmp     \t0, \t1
    jb     .Lfrop_SIGNEXTEND_W_done_\@
    mov     \t1, 0x804DC000
    cmp     \t0, \t1
    jae     .Lfrop_SIGNEXTEND_W_done_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 0
    jne     .Lfrop_SIGNEXTEND_W_done_\@
    mov     \t1, 0x804DB000
    sub     \t0, \t1
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 0
    jne     .Lfrop_SIGNEXTEND_W_done_\@
    add     \t0, 3427424
    jmp     .Lfrop_SIGNEXTEND_W_incr_\@
.Lfrop_SIGNEXTEND_W_incr_\@:
    lea     \t1, [rip + frops_binary_extension_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_SIGNEXTEND_W_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_extension_overflow]
    mov     ecx, dword ptr [rip + frops_binary_extension_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_extension_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_SIGNEXTEND_W_done_\@:
.endm

.macro FROP_REV8 a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 9 | FROP+incr best 15 worst 15 (no overflow)
    mov     \t0, \a
    cmp     \t0, 1
    jae     .Lfrop_REV8_done_\@
    imul    \t0, \t0, 4096
    mov     \t1, \b
    cmp     \t1, 4096
    jae     .Lfrop_REV8_done_\@
    add     \t0, \t1
    add     \t0, 3427936
    jmp     .Lfrop_REV8_incr_\@
.Lfrop_REV8_incr_\@:
    lea     \t1, [rip + frops_binary_extension_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_REV8_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_extension_overflow]
    mov     ecx, dword ptr [rip + frops_binary_extension_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_extension_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_REV8_done_\@:
.endm

.macro FROP_PACK a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 26 | FROP+incr best 15 worst 31 (no overflow)
    mov     \t0, \a
    cmp     \t0, 519
    jae     .Lfrop_PACK_n1_\@
    imul    \t0, \t0, 2
    mov     \t1, \b
    cmp     \t1, 2
    jae     .Lfrop_PACK_n1_\@
    add     \t0, \t1
    add     \t0, 3432032
    jmp     .Lfrop_PACK_incr_\@
.Lfrop_PACK_n1_\@:
    mov     \t0, \a
    mov     \t1, 0xFFFFF007
    cmp     \t0, \t1
    jb     .Lfrop_PACK_done_\@
    mov     \t1, 0x100000007
    cmp     \t0, \t1
    jae     .Lfrop_PACK_done_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 7
    jne     .Lfrop_PACK_done_\@
    mov     \t1, 0xFFFFF007
    sub     \t0, \t1
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 0
    jne     .Lfrop_PACK_done_\@
    add     \t0, 3433070
    jmp     .Lfrop_PACK_incr_\@
.Lfrop_PACK_incr_\@:
    lea     \t1, [rip + frops_binary_extension_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_PACK_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_extension_overflow]
    mov     ecx, dword ptr [rip + frops_binary_extension_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_extension_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_PACK_done_\@:
.endm

.macro FROP_PACK_H a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 9 | FROP+incr best 15 worst 15 (no overflow)
    mov     \t0, \a
    cmp     \t0, 256
    jae     .Lfrop_PACK_H_done_\@
    imul    \t0, \t0, 256
    mov     \t1, \b
    cmp     \t1, 256
    jae     .Lfrop_PACK_H_done_\@
    add     \t0, \t1
    add     \t0, 3433582
    jmp     .Lfrop_PACK_H_incr_\@
.Lfrop_PACK_H_incr_\@:
    lea     \t1, [rip + frops_binary_extension_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_PACK_H_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_extension_overflow]
    mov     ecx, dword ptr [rip + frops_binary_extension_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_extension_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_PACK_H_done_\@:
.endm

.macro FROP_PACK_W a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 6 | FROP+incr best 11 worst 11 (no overflow)
    mov     \t0, \a
    cmp     \t0, 5
    jae     .Lfrop_PACK_W_done_\@
    mov     \t1, \b
    cmp     \t1, 0
    jne     .Lfrop_PACK_W_done_\@
    add     \t0, 3499118
    jmp     .Lfrop_PACK_W_incr_\@
.Lfrop_PACK_W_incr_\@:
    lea     \t1, [rip + frops_binary_extension_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_PACK_W_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_extension_overflow]
    mov     ecx, dword ptr [rip + frops_binary_extension_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_extension_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_PACK_W_done_\@:
.endm

.macro FROP_ROR a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 60 | FROP+incr best 15 worst 65 (no overflow)
    mov     \t0, \a
    cmp     \t0, 1
    jae     .Lfrop_ROR_n1_\@
    imul    \t0, \t0, 39
    mov     \t1, \b
    cmp     \t1, 39
    jae     .Lfrop_ROR_n1_\@
    add     \t0, \t1
    add     \t0, 3499123
    jmp     .Lfrop_ROR_incr_\@
.Lfrop_ROR_n1_\@:
    mov     \t0, \a
    mov     \t1, 0x3AF7879156A36007
    cmp     \t0, \t1
    jb     .Lfrop_ROR_n2_\@
    mov     \t1, 0x3AF7879156A37007
    cmp     \t0, \t1
    jae     .Lfrop_ROR_n2_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 7
    jne     .Lfrop_ROR_n2_\@
    mov     \t1, 0x3AF7879156A36007
    sub     \t0, \t1
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 38
    jne     .Lfrop_ROR_n2_\@
    add     \t0, 3499162
    jmp     .Lfrop_ROR_incr_\@
.Lfrop_ROR_n2_\@:
    mov     \t0, \a
    mov     \t1, 0x98F726F10695F006
    cmp     \t0, \t1
    jb     .Lfrop_ROR_n3_\@
    mov     \t1, 0x98F726F106960006
    cmp     \t0, \t1
    jae     .Lfrop_ROR_n3_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 6
    jne     .Lfrop_ROR_n3_\@
    mov     \t1, 0x98F726F10695F006
    sub     \t0, \t1
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 38
    jne     .Lfrop_ROR_n3_\@
    add     \t0, 3499674
    jmp     .Lfrop_ROR_incr_\@
.Lfrop_ROR_n3_\@:
    mov     \t0, \a
    mov     \t1, 0xDAD4333928708005
    cmp     \t0, \t1
    jb     .Lfrop_ROR_done_\@
    mov     \t1, 0xDAD4333928709005
    cmp     \t0, \t1
    jae     .Lfrop_ROR_done_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 5
    jne     .Lfrop_ROR_done_\@
    mov     \t1, 0xDAD4333928708005
    sub     \t0, \t1
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 38
    jne     .Lfrop_ROR_done_\@
    add     \t0, 3500186
    jmp     .Lfrop_ROR_incr_\@
.Lfrop_ROR_incr_\@:
    lea     \t1, [rip + frops_binary_extension_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_ROR_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_extension_overflow]
    mov     ecx, dword ptr [rip + frops_binary_extension_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_extension_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_ROR_done_\@:
.endm

.macro FROP_ROR_W a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 9 | FROP+incr best 15 worst 15 (no overflow)
    mov     \t0, \a
    cmp     \t0, 1
    jae     .Lfrop_ROR_W_done_\@
    imul    \t0, \t0, 20
    mov     \t1, \b
    cmp     \t1, 20
    jae     .Lfrop_ROR_W_done_\@
    add     \t0, \t1
    add     \t0, 3500698
    jmp     .Lfrop_ROR_W_incr_\@
.Lfrop_ROR_W_incr_\@:
    lea     \t1, [rip + frops_binary_extension_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_ROR_W_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_extension_overflow]
    mov     ecx, dword ptr [rip + frops_binary_extension_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_extension_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_ROR_W_done_\@:
.endm

.macro FROP_CLZ a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 9 | FROP+incr best 15 worst 15 (no overflow)
    mov     \t0, \a
    cmp     \t0, 1
    jae     .Lfrop_CLZ_done_\@
    imul    \t0, \t0, 4096
    mov     \t1, \b
    cmp     \t1, 4096
    jae     .Lfrop_CLZ_done_\@
    add     \t0, \t1
    add     \t0, 3500718
    jmp     .Lfrop_CLZ_incr_\@
.Lfrop_CLZ_incr_\@:
    lea     \t1, [rip + frops_binary_extension_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_CLZ_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_extension_overflow]
    mov     ecx, dword ptr [rip + frops_binary_extension_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_extension_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_CLZ_done_\@:
.endm

.macro FROP_CTZ a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 9 | FROP+incr best 15 worst 15 (no overflow)
    mov     \t0, \a
    cmp     \t0, 1
    jae     .Lfrop_CTZ_done_\@
    imul    \t0, \t0, 129
    mov     \t1, \b
    cmp     \t1, 129
    jae     .Lfrop_CTZ_done_\@
    add     \t0, \t1
    add     \t0, 3504814
    jmp     .Lfrop_CTZ_incr_\@
.Lfrop_CTZ_incr_\@:
    lea     \t1, [rip + frops_binary_extension_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_CTZ_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_extension_overflow]
    mov     ecx, dword ptr [rip + frops_binary_extension_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_extension_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_CTZ_done_\@:
.endm

.macro FROP_CPOP_W a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 9 | FROP+incr best 15 worst 15 (no overflow)
    mov     \t0, \a
    cmp     \t0, 1
    jae     .Lfrop_CPOP_W_done_\@
    imul    \t0, \t0, 32
    mov     \t1, \b
    cmp     \t1, 32
    jae     .Lfrop_CPOP_W_done_\@
    add     \t0, \t1
    add     \t0, 3504943
    jmp     .Lfrop_CPOP_W_incr_\@
.Lfrop_CPOP_W_incr_\@:
    lea     \t1, [rip + frops_binary_extension_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_CPOP_W_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_extension_overflow]
    mov     ecx, dword ptr [rip + frops_binary_extension_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_extension_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_CPOP_W_done_\@:
.endm

.macro FROP_BCLR a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 9 | FROP+incr best 15 worst 15 (no overflow)
    mov     \t0, \a
    cmp     \t0, 1
    jae     .Lfrop_BCLR_done_\@
    imul    \t0, \t0, 64
    mov     \t1, \b
    cmp     \t1, 64
    jae     .Lfrop_BCLR_done_\@
    add     \t0, \t1
    add     \t0, 3504975
    jmp     .Lfrop_BCLR_incr_\@
.Lfrop_BCLR_incr_\@:
    lea     \t1, [rip + frops_binary_extension_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_BCLR_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_extension_overflow]
    mov     ecx, dword ptr [rip + frops_binary_extension_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_extension_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_BCLR_done_\@:
.endm

.macro FROP_BEXT a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 28 | FROP+incr best 15 worst 35 (no overflow)
    mov     \t0, \a
    cmp     \t0, 201
    jae     .Lfrop_BEXT_n1_\@
    imul    \t0, \t0, 8
    mov     \t1, \b
    cmp     \t1, 8
    jae     .Lfrop_BEXT_n1_\@
    add     \t0, \t1
    add     \t0, 3505039
    jmp     .Lfrop_BEXT_incr_\@
.Lfrop_BEXT_n1_\@:
    mov     \t0, \a
    cmp     \t0, 0x3F0006
    jb     .Lfrop_BEXT_done_\@
    cmp     \t0, 0x3F1006
    jae     .Lfrop_BEXT_done_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 6
    jne     .Lfrop_BEXT_done_\@
    sub     \t0, 0x3F0006
    shr     \t0, 3
    imul    \t0, \t0, 16
    mov     \t1, \b
    cmp     \t1, 1
    jb     .Lfrop_BEXT_done_\@
    cmp     \t1, 17
    jae     .Lfrop_BEXT_done_\@
    sub     \t1, 1
    add     \t0, \t1
    add     \t0, 3506647
    jmp     .Lfrop_BEXT_incr_\@
.Lfrop_BEXT_incr_\@:
    lea     \t1, [rip + frops_binary_extension_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_BEXT_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_extension_overflow]
    mov     ecx, dword ptr [rip + frops_binary_extension_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_extension_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_BEXT_done_\@:
.endm

.macro FROP_BINV a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 12 | FROP+incr best 17 worst 17 (no overflow)
    mov     \t0, \a
    mov     \t1, 0x8000000000000000
    cmp     \t0, \t1
    jb     .Lfrop_BINV_done_\@
    mov     \t1, 0x8000000000001000
    cmp     \t0, \t1
    jae     .Lfrop_BINV_done_\@
    mov     \t1, 0x8000000000000000
    sub     \t0, \t1
    mov     \t1, \b
    cmp     \t1, 63
    jne     .Lfrop_BINV_done_\@
    add     \t0, 3514839
    jmp     .Lfrop_BINV_incr_\@
.Lfrop_BINV_incr_\@:
    lea     \t1, [rip + frops_binary_extension_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_BINV_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_extension_overflow]
    mov     ecx, dword ptr [rip + frops_binary_extension_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_extension_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_BINV_done_\@:
.endm

.macro FROP_BSET a, b, t0, t1
    # cost (cyc, imul=3 else=1): reject-non-FROP worst 26 | FROP+incr best 15 worst 31 (no overflow)
    mov     \t0, \a
    cmp     \t0, 69
    jae     .Lfrop_BSET_n1_\@
    imul    \t0, \t0, 128
    mov     \t1, \b
    cmp     \t1, 128
    jae     .Lfrop_BSET_n1_\@
    add     \t0, \t1
    add     \t0, 3518935
    jmp     .Lfrop_BSET_incr_\@
.Lfrop_BSET_n1_\@:
    mov     \t0, \a
    mov     \t1, 0xC71E8005
    cmp     \t0, \t1
    jb     .Lfrop_BSET_done_\@
    mov     \t1, 0xC71E9005
    cmp     \t0, \t1
    jae     .Lfrop_BSET_done_\@
    mov     \t1, \t0
    and     \t1, 7
    cmp     \t1, 5
    jne     .Lfrop_BSET_done_\@
    mov     \t1, 0xC71E8005
    sub     \t0, \t1
    shr     \t0, 3
    mov     \t1, \b
    cmp     \t1, 32
    jne     .Lfrop_BSET_done_\@
    add     \t0, 3527767
    jmp     .Lfrop_BSET_incr_\@
.Lfrop_BSET_incr_\@:
    lea     \t1, [rip + frops_binary_extension_mult]
    inc     dword ptr [\t1 + \t0*4]
    jnz     .Lfrop_BSET_done_\@
    push    rax
    push    rcx
    push    rdx
    mov     rdx, \t0
    lea     rax, [rip + frops_binary_extension_overflow]
    mov     ecx, dword ptr [rip + frops_binary_extension_overflow_index]
    mov     dword ptr [rax + rcx*4], edx
    inc     dword ptr [rip + frops_binary_extension_overflow_index]
    pop     rdx
    pop     rcx
    pop     rax
.Lfrop_BSET_done_\@:
.endm

.macro FROP_SLL_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_SIGNEXTEND_H a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_ROL a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_ROL_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_CLZ_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_CTZ_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_CPOP a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_ORC_B a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_ADD_U_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_SH1ADD a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_SH1ADD_U_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_SH2ADD a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_SH2ADD_U_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_SH3ADD a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_SH3ADD_U_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_SLL_U_W a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_CLMUL a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_CLMUL_H a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_CLMUL_R a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_XPERM4 a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

.macro FROP_XPERM8 a, b, t0, t1
    # no FROPS for this op: does nothing (0 cyc)
.endm

