use crate::cluster::ClusterRegistry;
use crate::config::NodeConfig;
use crate::daemon::shutdown::wait_for_shutdown;
use crate::grpc::logging::GrpcLoggingLayer;
use crate::grpc::node_api::NodeApiService;
use crate::grpc::user::zisk_user_api_server::ZiskUserApiServer;
use crate::grpc::user_api::{UserApiService, UserApiState};
use crate::grpc::zisk_node_api_server::ZiskNodeApiServer;
use crate::grpc::MAX_MESSAGE_SIZE;
use anyhow::Result;
use std::net::SocketAddr;
use std::sync::Arc;
use tonic_health::server::health_reporter;
use tonic_reflection::server::Builder as ReflectionBuilder;
use tracing::info;

/// Encoded proto descriptor set generated by build.rs — used by gRPC reflection.
pub const FILE_DESCRIPTOR_SET: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/zisk_descriptor.bin"));

pub struct NodeServer {
    config: NodeConfig,
    cluster_registry: Option<Arc<ClusterRegistry>>,
}

impl NodeServer {
    pub fn new(config: NodeConfig, cluster_registry: Option<Arc<ClusterRegistry>>) -> Self {
        Self { config, cluster_registry }
    }

    pub async fn run(self) -> Result<()> {
        let addr: SocketAddr =
            format!("{}:{}", self.config.server.host, self.config.server.port).parse()?;

        if let Some(ref reg) = self.cluster_registry {
            info!("Active cluster: '{}'", reg.cluster_name());
        }

        // ── Health ────────────────────────────────────────────────────────────
        let (health_reporter, health_service) = health_reporter();
        health_reporter.set_serving::<ZiskUserApiServer<UserApiService>>().await;
        health_reporter.set_serving::<ZiskNodeApiServer<NodeApiService>>().await;

        // ── Reflection ────────────────────────────────────────────────────────
        let reflection_service = ReflectionBuilder::configure()
            .register_encoded_file_descriptor_set(FILE_DESCRIPTOR_SET)
            .build_v1()?;

        // ── Services ──────────────────────────────────────────────────────────
        let user_svc =
            ZiskUserApiServer::new(UserApiService::new(Arc::new(UserApiState::new(self.cluster_registry))))
                .max_decoding_message_size(MAX_MESSAGE_SIZE)
                .max_encoding_message_size(MAX_MESSAGE_SIZE);

        let node_svc = ZiskNodeApiServer::new(NodeApiService::new())
            .max_decoding_message_size(MAX_MESSAGE_SIZE)
            .max_encoding_message_size(MAX_MESSAGE_SIZE);

        info!("zisklet listening on {addr}");
        info!("  ZiskUserApi  — user-facing proof gateway  (zisk.user.v1)");
        info!("  ZiskNodeApi  — operator API               (zisk.node.v1)");
        info!("  Health       — grpc.health.v1.Health");
        info!("  Reflection   — grpc.reflection.v1.ServerReflection");

        // ── Graceful shutdown ─────────────────────────────────────────────────
        // Mark both services NOT_SERVING before the server stops accepting
        // connections so load balancers and Kubernetes drain traffic cleanly.
        let shutdown = async move {
            wait_for_shutdown().await;
            info!("Shutdown signal received — draining traffic");
            health_reporter.set_not_serving::<ZiskNodeApiServer<NodeApiService>>().await;
            health_reporter.set_not_serving::<ZiskUserApiServer<UserApiService>>().await;
        };

        tonic::transport::Server::builder()
            .layer(GrpcLoggingLayer)
            .add_service(health_service)
            .add_service(reflection_service)
            .add_service(user_svc)
            .add_service(node_svc)
            .serve_with_shutdown(addr, shutdown)
            .await?;

        info!("zisklet shut down cleanly");
        Ok(())
    }
}
