[package]
name = "consensus-coordinator"
description = "Core types and functionality for Consensus Network"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
proofman = { workspace = true }
consensus-grpc-api = { workspace = true }
consensus-config = { path = "../config" }
consensus-common = { path = "../common" }

serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
futures = { workspace = true }
signal-hook = { version = "0.3" }
signal-hook-tokio = { version = "0.3", features = ["futures-v0_3"] }
