use log::info;
use p3_field::PrimeField;
use sm_common::InstanceExpanderCtx;

use std::sync::Arc;
use zisk_core::{zisk_ops::ZiskOp, ZiskRom, ROM_ENTRY};

use proofman::WitnessManager;
use proofman_common::{AirInstance, ProofCtx};

use proofman::WitnessComponent;
use zisk_pil::{MainRow, MainTrace, MAIN_AIR_IDS, ZISK_AIRGROUP_ID};
use ziskemu::{Emu, EmuTrace};

/// This is a multithreaded implementation of the Zisk MainSM state machine.
///
/// The MainSM state machine is responsible for orchestrating the execution of the program and
/// processing the inputs generated by the emulator. The MainSM state machine interacts with the
/// secondary state machines to process the inputs generated by the emulator.
pub struct MainSM<F: PrimeField> {
    /// Witness computation manager
    wcm: Arc<WitnessManager<F>>,
}

impl<F: PrimeField> MainSM<F> {
    const MY_NAME: &'static str = "MainSM  ";

    /// Constructor for the MainSM state machine
    /// Registers the state machine at the WCManager and stores references to the secondary state
    /// machines that directly interact with the MainSM
    /// Returns an Arc to the MainSM state machine
    /// # Arguments
    /// * `wcm` - Witness computation manager to register the state machine
    /// * `arith_sm` - Arc to the ArithSM state machine
    /// * `binary_sm` - Arc to the BinarySM state machine
    /// * `mem_sm` - Arc to the MemSM state machine
    /// # Returns
    /// * Arc to the MainSM state machine
    pub fn new(wcm: Arc<WitnessManager<F>>) -> Arc<Self> {
        let main_sm = Arc::new(Self { wcm: wcm.clone() });

        wcm.register_component(main_sm.clone(), Some(ZISK_AIRGROUP_ID), Some(MAIN_AIR_IDS));

        main_sm
    }

    pub fn prove_main<'a>(
        &self,
        zisk_rom: &ZiskRom,
        vec_traces: &'a [EmuTrace],
        iectx: &mut InstanceExpanderCtx<F>,
        pctx: &ProofCtx<F>,
    ) {
        let segment_id = iectx.plan.segment_id.unwrap();
        let segment_trace = &vec_traces[segment_id];

        let offset = iectx.buffer.offset;
        let air = pctx.pilout.get_air(ZISK_AIRGROUP_ID, MAIN_AIR_IDS[0]);
        let filled = segment_trace.steps.len() + 1;
        info!(
            "{}: ··· Creating Main segment #{} [{} / {} rows filled {:.2}%]",
            Self::MY_NAME,
            segment_id,
            filled,
            air.num_rows(),
            filled as f64 / air.num_rows() as f64 * 100.0
        );

        // Set Row 0 of the current segment
        let row0 = if segment_id == 0 {
            MainRow::<F> {
                pc: F::from_canonical_u64(ROM_ENTRY),
                op: F::from_canonical_u8(ZiskOp::CopyB.code()),
                a_src_imm: F::one(),
                b_src_imm: F::one(),
                ..MainRow::default()
            }
        } else {
            let emu_trace_previous = vec_traces[segment_id - 1].steps.last().unwrap();
            let mut emu =
                Emu::from_emu_trace_start(zisk_rom, &vec_traces[segment_id - 1].last_state);
            let row_previous = emu.step_slice_full_trace(emu_trace_previous);

            MainRow::<F> {
                set_pc: row_previous.set_pc,
                jmp_offset1: row_previous.jmp_offset1,
                jmp_offset2: if row_previous.flag == F::one() {
                    row_previous.jmp_offset1
                } else {
                    row_previous.jmp_offset2
                },
                a: row_previous.a,
                b: row_previous.c,
                c: row_previous.c,
                a_offset_imm0: row_previous.a[0],
                b_offset_imm0: row_previous.c[0],
                addr1: row_previous.c[0],
                a_imm1: row_previous.a[1],
                b_imm1: row_previous.c[1],
                op: F::from_canonical_u8(ZiskOp::CopyB.code()),
                pc: row_previous.pc,
                a_src_imm: F::one(),
                b_src_imm: F::one(),
                ..MainRow::default()
            }
        };

        let mut emu = Emu::from_emu_trace_start(zisk_rom, &segment_trace.start_state);

        let rng = offset as usize..(offset as usize + MainRow::<F>::ROW_SIZE);
        iectx.buffer.buffer[rng].copy_from_slice(row0.as_slice());

        // Set Rows 1 to N of the current segment (N = maximum number of air rows)
        let total_rows = segment_trace.steps.len();
        const SLICE_ROWS: usize = 4096;
        let mut partial_trace = MainTrace::<F>::new(SLICE_ROWS);

        let mut last_row = MainRow::<F>::default();
        for slice in (0..(air.num_rows())).step_by(SLICE_ROWS) {
            // process the steps of the chunk
            let slice_start = std::cmp::min(slice, total_rows);
            let slice_end = std::cmp::min(slice + SLICE_ROWS, total_rows);

            for (i, emu_trace_step) in
                segment_trace.steps[slice_start..slice_end].iter().enumerate()
            {
                partial_trace[i] = emu.step_slice_full_trace(emu_trace_step);
            }

            // if there are steps in the chunk update last row
            if slice_end - slice_start > 0 {
                last_row = partial_trace[slice_end - slice_start - 1];
            }

            // if there are less steps than the chunk size, fill the rest with the last row
            for i in (slice_end - slice_start)..SLICE_ROWS {
                partial_trace[i] = last_row;
            }

            //copy the chunk to the prover buffer
            let partial_buffer = partial_trace.buffer.as_ref().unwrap();
            let buffer_offset_slice = offset as usize + (slice + 1) * MainRow::<F>::ROW_SIZE;

            let rng = buffer_offset_slice..buffer_offset_slice + partial_buffer.len();
            iectx.buffer.buffer[rng].copy_from_slice(partial_buffer);
        }

        let buffer = std::mem::take(&mut iectx.buffer.buffer);
        let sctx = self.wcm.get_sctx();
        let mut air_instance = AirInstance::new(
            sctx.clone(),
            ZISK_AIRGROUP_ID,
            MAIN_AIR_IDS[0],
            Some(segment_id),
            buffer,
        );

        let main_last_segment = F::from_bool(segment_id == vec_traces.len() - 1);
        let main_segment = F::from_canonical_usize(segment_id);

        air_instance.set_airvalue(&sctx, "Main.main_last_segment", main_last_segment);
        air_instance.set_airvalue(&sctx, "Main.main_segment", main_segment);

        self.wcm
            .get_pctx()
            .air_instance_repo
            .add_air_instance(air_instance, Some(iectx.instance_global_idx));
    }
}

impl<F: PrimeField> WitnessComponent<F> for MainSM<F> {}
