[package]
name = "zisk-executor"
description = "Execution engine that orchestrates witness generation across ZisK state machines"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
categories = { workspace = true }

[dependencies]
zisk-sm-main = { workspace = true }
zisk-sm-rom = { workspace = true }
zisk-pil = { workspace = true }
ziskemu = { workspace = true }
zisk-core = { workspace = true }
zisk-common = { workspace = true }
zisk-asm-runner = { workspace = true }
zisk-sm-mem-common = { workspace = true }

proofman = { workspace = true }
proofman-common = { workspace = true }
proofman-util = { workspace = true }
proofman-witness = { workspace = true }
proofman-fields = { workspace = true }
tracing = { workspace = true }
rayon = { workspace = true }
pil2-std-lib = { workspace = true }
zisk-precomp-hints = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
arc-swap = { workspace = true }
paste = { workspace = true }
crossbeam = "0.8.4"

zisk-precomp-common = { workspace = true }
zisk-precomp-keccakf = { workspace = true }
zisk-precomp-sha256f = { workspace = true }
zisk-precomp-poseidon = { workspace = true }
zisk-precomp-blake2 = { workspace = true }
zisk-precomp-arith-eq = { workspace = true }
zisk-precomp-arith-eq-384 = { workspace = true }
zisk-precomp-big-int = { workspace = true }
zisk-precomp-dma = { workspace = true }
zisk-precomp-evm = { workspace = true }

zisk-sm-arith = { workspace = true }
zisk-sm-binary = { workspace = true }
zisk-sm-mem = { workspace = true }

[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
named-sem = { workspace = true }

[features]
default = []
stats = []
cpu-only = ["zisk-asm-runner/cpu-only"]
