[package]
name = "zisk-build"
description = "Build tooling for compiling guest programs to RISC-V ELF for the ZisK zkVM"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[dependencies]
clap = { workspace = true }
cargo_metadata = "0.23.0"
anyhow = { workspace = true }
zisk-rom-setup = { workspace = true }
blake3 = { workspace = true }

[build-dependencies]
vergen-git2 = { workspace = true }

[features]
cpu-only = []
