[package]
name = "riscv2zisk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elf = "0.7.4"
json = "0.12.4"

[lib]
name = "riscv2zisk"
path = "src/lib.rs"

[[bin]]
name = "riscv2zisk"
path = "src/bin/riscv2zisk.rs"