[book]
authors = ["Eduardo Antuña Díez"]
language = "en"
multilingual = false
src = "."
title = "ZisK Documentation"

[output.html.playground]
runnable = false

[build]
build-dir = "target/book"

[preprocessor.mermaid]