[package]
name = "zisk-precomp-arith-eq-384"
description = "384-bit arithmetic-equality precompile for the ZisK zkVM"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[[bin]]
name = "zisk-arith-eq-384-generator"
path = "src/arith_eq_384_generator.rs"

[[bin]]
name = "zisk-arith-eq-384-test-bigint"
path = "src/arith_eq_384_test_bigint.rs"
required-features = ["test_data"]

[[bin]]
name = "zisk-arith-eq-384-test-generator"
path = "src/arith_eq_384_test_generator.rs"

[dependencies]
zisk-core = { workspace = true }
zisk-pil = { workspace = true }
zisk-precomp-common = { workspace = true }
zisk-precomp-helpers = { workspace = true }
zisk-precomp-arith-eq = { workspace = true }
zisk-common = { workspace = true }

proofman-common = { workspace = true }
proofman-util = { workspace = true }
pil2-std-lib = { workspace = true }

proofman-fields = { workspace = true }
tracing = { workspace = true }
rayon = { workspace = true }
ark-ff = { workspace = true }
ark-bls12-381 = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }

rustfmt-wrapper = { workspace = true }
lazy_static = { workspace = true }
path-clean = { workspace = true }

[dev-dependencies]
zisk-test-artifacts = { workspace = true }
serial_test = { workspace = true }

[features]
default = []
test_data = []
