[package]
name = "zisk-sm-binary"
description = "Binary operations state machine for the ZisK zkVM"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
categories = { workspace = true }

[[bin]]
name = "zisk-binary-basic-frops-fixed-gen"
path = "src/binary_basic_frops_fixed_gen.rs"

[[bin]]
name = "zisk-binary-extension-frops-fixed-gen"
path = "src/binary_extension_frops_fixed_gen.rs"

[dependencies]
zisk-core = { workspace = true }
zisk-common = { workspace = true }
zisk-pil = { workspace = true }
zisk-sm-frequent-ops = { workspace = true }

proofman-fields = { workspace = true }
proofman-common = { workspace = true }
pil2-std-lib = { workspace = true }

tracing = { workspace = true }
rayon = { workspace = true }
static_assertions = { workspace = true }
