#!/bin/sh

command_to_run="cargo fix --all-features"
crates="common hints pilout proofman provers/stark provers/starks-lib-c transcript util"
original_dir=`pwd`

for crate in $crates; do
  if [ -d "$crate" ]; then
    echo "$command_to_run ($crate)"
    cd $crate
    `$command_to_run`
    cd $original_dir
  else
    echo "Crate not found: $crate"
  fi
done
