apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: ${ZISK_PROMETHEUS_URL}
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 5s
      httpMethod: POST
