//! Indexed (compact) Main packing, defined beside the autogenerated `MainTraceRow` without
//! touching `traces.rs`. The single tagged `indexed_trace_row!` invocation below generates
//! the compact row, the instruction-table entry, `impl MainTraceRowOps`, the `IndexedFill`
//! impls, and the `col_source` descriptor. The column list/order mirrors `MainTraceRow`;
//! any structural drift (added/renamed/retyped column) is a compile error.

use fields::PrimeField64;
use proofman_macros::indexed_trace_row;

use crate::{MainTrace, MainTraceRow, MainTraceRowOps, MainTraceRowPacked};

/// Re-export so the emulator / main SM can bound generic fills on `zisk_pil::IndexedFill`.
pub use proofman_common::trace::IndexedFill;

// Derived from the autogenerated `MainTrace` alias, so they track the pilout — not hardcoded.
pub const MAIN_AIRGROUP_ID: usize = MainTrace::<()>::AIRGROUP_ID;
pub const MAIN_AIR_ID: usize = MainTrace::<()>::AIR_ID;

indexed_trace_row!(MainTraceRow<F> {
    a: [u32; 2],
    b: [u32; 2],
    c: [u32; 2],
    flag: bit,
    pc: u32 @instr,
    a_src_imm: bit @instr,
    a_src_mem: bit @instr,
    a_offset_imm0: u64 @instr,
    a_imm1: u32 @instr,
    is_precompiled: bit @instr,
    b_src_imm: bit @instr,
    b_src_mem: bit @instr,
    b_offset_imm0: u64 @instr,
    b_imm1: u32 @instr,
    b_src_ind: bit @instr,
    ind_width: ubit(4) @instr,
    is_external_op: bit @instr,
    op: u8 @instr,
    store_pc: bit @instr,
    store_mem: bit @instr,
    store_ind: bit @instr,
    store_offset: u64 @instr,
    set_pc: bit @instr,
    jmp_offset1: u64 @instr,
    jmp_offset2: u64 @instr,
    m32: bit @instr,
    addr1: u32,
    a_reg_prev_mem_step: ubit(38),
    b_reg_prev_mem_step: ubit(38),
    store_reg_prev_mem_step: ubit(38),
    store_reg_prev_value: [u32; 2],
    a_src_reg: bit @instr,
    b_src_reg: bit @instr,
    store_reg: bit @instr,
});
