use std::{any::Any, fmt::Debug};

use proofman_common::WitnessPilout;
use zisk_core::{InstContext, ZiskInst};

/// Trait for output plans generated by planners
pub trait OutputPlan: Any {
    fn as_any(&self) -> &dyn Any;
}

/// Trait for a layout planner
pub trait LayoutPlanner: Send + Sync {
    fn new_session(&mut self, pilout: &WitnessPilout);
    fn on_instruction(&mut self, zisk_inst: &ZiskInst, inst_ctx: &InstContext);
    fn get_plan(&self) -> Box<dyn OutputPlan>;
}

pub trait PlannerProvider {
    fn get_planner(&self) -> Box<dyn LayoutPlanner>;
}
