//! Smoke test driving the `diagnostic_hints` guest ELF through a hints-backed
//! `execute`. Exercises the full hints path: the Assembly ROM is set up with
//! hint support, a pre-generated hints binary is streamed in, and every
//! accelerator precompile is checked against it in one shot.
//!
//! Uses the execute-only client, so no proving key is loaded.
//! Execute explicitly with:
//!
//!     cargo test -p zisk-sdk --test diagnostic_hints_smoke -- --nocapture
//!
//! The hints binary at `test-artifacts/programs/diagnostic_hints/tmp/hints.bin`
//! (the default below) is generated automatically by that crate's `build.rs`
//! when its ELF is built. Override the location with `ZISK_TEST_HINTS`.
//!

use std::path::PathBuf;

use test_artifacts::ELF_DIAGNOSTIC_HINTS;
use zisk_sdk::{EmbeddedClientBuilder, ZiskHints, ZiskStdin};

/// Default hints binary, written by a native run of the `diagnostic_hints` guest.
const DEFAULT_HINTS: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../test-artifacts/programs/diagnostic_hints/tmp/hints.bin"
);

#[test]
fn execute_diagnostic_hints() {
    // Resolve the hints binary (env override, else the native-run default).
    let hints_path = std::env::var_os("ZISK_TEST_HINTS")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(DEFAULT_HINTS));
    eprintln!("[diagnostic_hints_smoke] using hints {}", hints_path.display());
    let hints = ZiskHints::from_file(&hints_path).unwrap_or_else(|e| {
        panic!(
            "failed to load hints {}: {e}\n\
             These are generated by the diagnostic_hints build.rs when its ELF is built;\n\
             regenerate with: cargo run -p diagnostic-hints --release\n\
             (or point ZISK_TEST_HINTS at a hints binary)",
            hints_path.display()
        )
    });

    // Hints require the Assembly executor
    let client = EmbeddedClientBuilder::default()
        .assembly()
        .execute_only()
        .build()
        .expect("failed to build execute-only client");

    // Set up the ROM with hint support enabled.
    client.setup(&ELF_DIAGNOSTIC_HINTS, true).expect("ROM setup failed");

    // Execute, streaming the hints in.
    let result = client
        .execute(&ELF_DIAGNOSTIC_HINTS, ZiskStdin::new(), Some(hints))
        .expect("execute failed");

    assert!(result.get_execution_steps() > 0, "execution did no work");
    eprintln!(
        "[diagnostic_hints_smoke] executed {} steps in {} ms",
        result.get_execution_steps(),
        result.get_execution_time()
    );
}
