[package]
name = "zisk-verifier"
description = "Proof verifier for the ZisK zkVM proofs"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
categories = { workspace = true }

[dependencies]
proofman-verifier = { workspace = true, features = ["verify"] }

[features]
default = []
std = ["proofman-verifier/std"]
