[package]
name = "verifier"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[dependencies]
tracing = { workspace = true }
fields = { workspace = true }
proofman-common = { workspace = true }
proofman = { workspace = true }

[features]
default = []
verify = ["fields/verify"]
