[package]
name = "zisk-verifier"
description = "Proof verifier for the ZisK zkVM proofs"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[dependencies]
proofman-verifier = { path = "../../pil2-proofman/verifier", version = "1.0.0-beta", default-features = false, features = [
  "verify",
] }

[features]
default = []
std = ["proofman-verifier/std"]
