[package]
name = "verifier"
version = "0.11.0"
edition = "2021"
license = "Apache-2.0 or MIT"
keywords = ["zisk", "zkvm", "zero-knowledge"]
repository = "https://github.com/0xPolygonHermez/zisk"
categories = ["cryptography"]

[dependencies]
fields = { git = "https://github.com/0xPolygonHermez/pil2-proofman.git", branch = "feature/rust-verifier" }
proofman-verifier = { git = "https://github.com/0xPolygonHermez/pil2-proofman.git", branch = "feature/rust-verifier" }
ziskos = { git = "https://github.com/0xPolygonHermez/zisk.git" }
bytemuck = "1.23.1"

[features]
default = []
verify = ["fields/verify"]
