[package]
name = "verifier"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[dependencies]
fields = { git = "https://github.com/0xPolygonHermez/pil2-proofman.git", branch = "pre-develop-0.10.0" }
proofman-verifier = { git = "https://github.com/0xPolygonHermez/pil2-proofman.git", branch = "pre-develop-0.10.0" }
ziskos = { git = "https://github.com/0xPolygonHermez/zisk.git" }
bytemuck = "1.23.1"

[features]
default = []
verify = ["fields/verify"]
