profile = "compiler"
change-id = 126701

[build]
target = ["riscv64ima-zisk-zkvm-elf"]
extended = true
tools = ["cargo", "cargo-clippy", "clippy", "rustfmt"]
configure-args = []
#cargo-native-static = true

[target.riscv64ima-zisk-zkvm-elf]
cc = "riscv64-unknown-elf-gcc"

[llvm]
download-ci-llvm = false

[rust]
lld = true
llvm-tools = true
