[build]
target = ["riscv64ima-zisk-zkvm-elf"]
extended = true
tools = ["cargo", "cargo-clippy", "clippy", "rustfmt"]
configure-args = []
cargo-native-static = true

[llvm]
download-ci-llvm = false

[rust]
lld = true
llvm-tools = true
