# This silences a bootstrap warning about missing change tracking in config.toml.
# It acknowledges the latest major configuration version used by the Rust build system.
change-id = 134650

[build]
target = ["riscv64ima-zisk-zkvm-elf"]
extended = true
tools = ["cargo", "cargo-clippy", "clippy", "rustfmt"]
configure-args = []
cargo-native-static = true

[llvm]
download-ci-llvm = false

[rust]
lld = true
llvm-tools = true
