[package]
name = "sm-mem-aligned"
version = "0.1.0"
edition = "2021"

[dependencies]
sm-common = { path = "../common" }
zisk-core = { path = "../../core" }

proofman-common = { workspace = true }
proofman = { workspace = true }

log = { version = "0.4", default-features = false }
rayon = "1.10.0"
