#![allow(dead_code)]
#![allow(clippy::manual_range_contains, clippy::nonminimal_bool)]
// @generated by frops-analyzer — do not edit by hand.
// generated with: max-table=25165824 partition-bits=21 low-cap=4096 max-regions-per-op=4 table-cost=3 nodes=1
use std::error::Error;
use zisk_core::zisk_ops::ZiskOp;
use zisk_sm_frequent_ops::FrequentOpsHelpers;

const OP_SLL: u8 = ZiskOp::Sll.code();
const OP_SRL: u8 = ZiskOp::Srl.code();
const OP_SRA: u8 = ZiskOp::Sra.code();
const OP_SLLW: u8 = ZiskOp::SllW.code();
const OP_SRLW: u8 = ZiskOp::SrlW.code();
const OP_SRAW: u8 = ZiskOp::SraW.code();
const OP_SIGNEXTENDB: u8 = ZiskOp::SignExtendB.code();
const OP_SIGNEXTENDH: u8 = ZiskOp::SignExtendH.code();
const OP_SIGNEXTENDW: u8 = ZiskOp::SignExtendW.code();
const OP_REV8: u8 = ZiskOp::Rev8.code();
const OP_CLZ: u8 = ZiskOp::Clz.code();
const OP_CLZW: u8 = ZiskOp::ClzW.code();
const OP_CPOP: u8 = ZiskOp::Cpop.code();
const OP_ORCB: u8 = ZiskOp::OrcB.code();
const OP_BEXT: u8 = ZiskOp::Bext.code();
const OP_BINV: u8 = ZiskOp::Binv.code();
const OP_BSET: u8 = ZiskOp::Bset.code();
const OP_SLLUW: u8 = ZiskOp::SllUW.code();

const OP_TABLE_OFFSETS_START: usize = 33;
const OP_TABLE_OFFSETS: [usize; 47] = [
    0, 540160, 2300416, 2456793, 2481345, 2481409, 2483187, 2870516, 2877001, 0, 0, 0, 0, 0, 0, 0,
    2916425, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2920521, 2924617, 0, 0, 2924686, 0, 2924942, 0,
    2928856, 2930221, 2930349, 0, 0, 0, 0, 0, 0, 0, 2934445,
];

#[derive(Debug, Clone)]
pub struct BinaryExtensionFrops {
    table: FrequentOpsHelpers,
}

const FREQUENT_OP_EMPTY: usize = 256;

impl Default for BinaryExtensionFrops {
    fn default() -> Self {
        Self::new()
    }
}

impl BinaryExtensionFrops {
    pub const TABLE_ID: usize = 5012;
    pub const NO_FROPS: usize = FrequentOpsHelpers::NO_FROPS;
    pub fn new() -> Self {
        Self { table: FrequentOpsHelpers::new() }
    }

    pub fn build_table(&mut self) {
        // op sll
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a < 4096 && b < 64
            for a in 0..4096 {
                for b in 0..64 {
                    ops.push([a, b]);
                }
            }
            // mid_box: a >= 4096 && a < 8192 && b < 64
            for a in 0x1000..0x2000 {
                for b in 0..64 {
                    ops.push([a, b]);
                }
            }
            // mid_box: a >= 0x3C23F006 && a < 0x3C240006 && (a & 7) == 6 && b == 32
            for a in (0x3C23F006..0x3C240006).step_by(8) {
                for b in 0x20..0x21 {
                    ops.push([a, b]);
                }
            }
            // mid_box: a >= 0x4EC4E007 && a < 0x4EC4F007 && (a & 7) == 7 && b >= 3 && b < 33
            for a in (0x4EC4E007..0x4EC4F007).step_by(8) {
                for b in 0x3..0x21 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_SLL, &mut ops, true);
        }
        // op srl
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a < 4096 && b < 64
            for a in 0..4096 {
                for b in 0..64 {
                    ops.push([a, b]);
                }
            }
            // mid_box: a >= 4096 && a < 24576 && b < 64
            for a in 0x1000..0x6000 {
                for b in 0..64 {
                    ops.push([a, b]);
                }
            }
            // mid_box: a >= 0x7FFFFFFFFFFFD000 && a < 0x8000000000001000 && (a & 7) == 0 && b < 64
            for a in (0x7FFFFFFFFFFFD000..0x8000000000001000).step_by(8) {
                for b in 0..64 {
                    ops.push([a, b]);
                }
            }
            // mid_box: a >= 0xDE0B6B3A763FF000 && a < 0xDE0B6B3A76401000 && (a & 7) == 0 && b >= 1 && b < 56
            for a in (0xDE0B6B3A763FF000..0xDE0B6B3A76401000).step_by(8) {
                for b in 0x1..0x38 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_SRL, &mut ops, true);
        }
        // op sra
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a < 4041 && b < 17
            for a in 0..4041 {
                for b in 0..17 {
                    ops.push([a, b]);
                }
            }
            // mid_box: a >= 4096 && a < 28672 && (a & 3) == 0 && b >= 3 && b < 17
            for a in (0x1000..0x7000).step_by(4) {
                for b in 0x3..0x11 {
                    ops.push([a, b]);
                }
            }
            // mid_box: a >= 0x12C00004 && a < 0x12C01004 && (a & 7) == 4 && b == 16
            for a in (0x12C00004..0x12C01004).step_by(8) {
                for b in 0x10..0x11 {
                    ops.push([a, b]);
                }
            }
            // high_box: a >= 0xFFFFFFFFFFFFFF80 && b < 9
            for a in 0xFFFFFFFFFFFFFF80..=u64::MAX {
                for b in 0..9 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_SRA, &mut ops, true);
        }
        // op sll_w
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a < 2046 && b < 12
            for a in 0..2046 {
                for b in 0..12 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_SLLW, &mut ops, true);
        }
        // op srl_w
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a < 16 && b < 4
            for a in 0..16 {
                for b in 0..4 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_SRLW, &mut ops, true);
        }
        // op sra_w
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a < 254 && b < 7
            for a in 0..254 {
                for b in 0..7 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_SRAW, &mut ops, true);
        }
        // op signextend_b
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a == 0 && b < 257
            for a in 0..1 {
                for b in 0..257 {
                    ops.push([a, b]);
                }
            }
            // mid_box: a >= 0xA03FC000 && a < 0xA03FF000 && (a & 7) == 0 && b < 252
            for a in (0xA03FC000..0xA03FF000).step_by(8) {
                for b in 0..252 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_SIGNEXTENDB, &mut ops, true);
        }
        // op signextend_h
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a == 0 && b < 2901
            for a in 0..1 {
                for b in 0..2901 {
                    ops.push([a, b]);
                }
            }
            // mid_box: a >= 0x800D5000 && a < 0x800D6000 && (a & 7) == 0 && b < 6
            for a in (0x800D5000..0x800D6000).step_by(8) {
                for b in 0..6 {
                    ops.push([a, b]);
                }
            }
            // mid_box: a >= 0x800D5000 && a < 0x800D6000 && (a & 7) == 0 && b == 100
            for a in (0x800D5000..0x800D6000).step_by(8) {
                for b in 0x64..0x65 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_SIGNEXTENDH, &mut ops, true);
        }
        // op signextend_w
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // mid_box: a >= 0x800D5000 && a < 0x800D6000 && (a & 3) == 0 && b == 100
            for a in (0x800D5000..0x800D6000).step_by(4) {
                for b in 0x64..0x65 {
                    ops.push([a, b]);
                }
            }
            // mid_box: a >= 0xAABC9000 && a < 0xAABCA000 && (a & 7) == 0 && b < 15
            for a in (0xAABC9000..0xAABCA000).step_by(8) {
                for b in 0..15 {
                    ops.push([a, b]);
                }
            }
            // mid_box: a >= 0xAAC0C000 && a < 0xAAC0E000 && (a & 7) == 0 && b < 15
            for a in (0xAAC0C000..0xAAC0E000).step_by(8) {
                for b in 0..15 {
                    ops.push([a, b]);
                }
            }
            // mid_box: a >= 0xAACAE000 && a < 0xAACB0000 && (a & 7) == 0 && b < 15
            for a in (0xAACAE000..0xAACB0000).step_by(8) {
                for b in 0..15 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_SIGNEXTENDW, &mut ops, true);
        }
        // op rev8
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a == 0 && b < 4096
            for a in 0..1 {
                for b in 0..4096 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_REV8, &mut ops, true);
        }
        // op clz
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a == 0 && b < 4096
            for a in 0..1 {
                for b in 0..4096 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_CLZ, &mut ops, true);
        }
        // op clz_w
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a == 0 && b < 69
            for a in 0..1 {
                for b in 0..69 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_CLZW, &mut ops, true);
        }
        // op cpop
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a == 0 && b < 256
            for a in 0..1 {
                for b in 0..256 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_CPOP, &mut ops, true);
        }
        // op orc_b
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a == 0 && b < 3914
            for a in 0..1 {
                for b in 0..3914 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_ORCB, &mut ops, true);
        }
        // op bext
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a < 273 && b < 5
            for a in 0..273 {
                for b in 0..5 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_BEXT, &mut ops, true);
        }
        // op binv
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a < 2 && b < 64
            for a in 0..2 {
                for b in 0..64 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_BINV, &mut ops, true);
        }
        // op bset
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a == 0 && b < 4096
            for a in 0..1 {
                for b in 0..4096 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_BSET, &mut ops, true);
        }
        // op sll_u_w
        {
            let mut ops: Vec<[u64; 2]> = Vec::new();
            // low_rect: a < 1109 && b < 10
            for a in 0..1109 {
                for b in 0..10 {
                    ops.push([a, b]);
                }
            }
            self.table.add_ops(OP_SLLUW, &mut ops, true);
        }
    }

    #[inline(always)]
    pub fn is_frequent_op(op: u8, a: u64, b: u64) -> bool {
        match op {
            OP_SLL => {
                a < 4096 && b < 64
                    || a >= 4096 && a < 8192 && b < 64
                    || a >= 0x3C23F006 && a < 0x3C240006 && (a & 7) == 6 && b == 32
                    || a >= 0x4EC4E007 && a < 0x4EC4F007 && (a & 7) == 7 && b >= 3 && b < 33
            }
            OP_SRL => {
                a < 4096 && b < 64
                    || a >= 4096 && a < 24576 && b < 64
                    || a >= 0x7FFFFFFFFFFFD000 && a < 0x8000000000001000 && (a & 7) == 0 && b < 64
                    || a >= 0xDE0B6B3A763FF000
                        && a < 0xDE0B6B3A76401000
                        && (a & 7) == 0
                        && b >= 1
                        && b < 56
            }
            OP_SRA => {
                a < 4041 && b < 17
                    || a >= 4096 && a < 28672 && (a & 3) == 0 && b >= 3 && b < 17
                    || a >= 0x12C00004 && a < 0x12C01004 && (a & 7) == 4 && b == 16
                    || a >= 0xFFFFFFFFFFFFFF80 && b < 9
            }
            OP_SLLW => a < 2046 && b < 12,
            OP_SRLW => a < 16 && b < 4,
            OP_SRAW => a < 254 && b < 7,
            OP_SIGNEXTENDB => {
                a == 0 && b < 257 || a >= 0xA03FC000 && a < 0xA03FF000 && (a & 7) == 0 && b < 252
            }
            OP_SIGNEXTENDH => {
                a == 0 && b < 2901
                    || a >= 0x800D5000 && a < 0x800D6000 && (a & 7) == 0 && b < 6
                    || a >= 0x800D5000 && a < 0x800D6000 && (a & 7) == 0 && b == 100
            }
            OP_SIGNEXTENDW => {
                a >= 0x800D5000 && a < 0x800D6000 && (a & 3) == 0 && b == 100
                    || a >= 0xAABC9000 && a < 0xAABCA000 && (a & 7) == 0 && b < 15
                    || a >= 0xAAC0C000 && a < 0xAAC0E000 && (a & 7) == 0 && b < 15
                    || a >= 0xAACAE000 && a < 0xAACB0000 && (a & 7) == 0 && b < 15
            }
            OP_REV8 => a == 0 && b < 4096,
            OP_CLZ => a == 0 && b < 4096,
            OP_CLZW => a == 0 && b < 69,
            OP_CPOP => a == 0 && b < 256,
            OP_ORCB => a == 0 && b < 3914,
            OP_BEXT => a < 273 && b < 5,
            OP_BINV => a < 2 && b < 64,
            OP_BSET => a == 0 && b < 4096,
            OP_SLLUW => a < 1109 && b < 10,
            _ => false,
        }
    }

    #[inline(always)]
    pub fn get_row(op: u8, a: u64, b: u64) -> usize {
        let relative_offset = match op {
            OP_SLL => {
                if a < 4096 && b < 64 {
                    (a * 64 + b) as usize
                } else if a >= 4096 && a < 8192 && b < 64 {
                    ((a - 0x1000) * 64 + b) as usize + 262144
                } else if a >= 0x3C23F006 && a < 0x3C240006 && (a & 7) == 6 && b == 32 {
                    ((a - 0x3C23F006) / 8) as usize + 524288
                } else if a >= 0x4EC4E007 && a < 0x4EC4F007 && (a & 7) == 7 && b >= 3 && b < 33 {
                    (((a - 0x4EC4E007) / 8) * 30 + (b - 0x3)) as usize + 524800
                } else {
                    Self::NO_FROPS
                }
            }
            OP_SRL => {
                if a < 4096 && b < 64 {
                    (a * 64 + b) as usize
                } else if a >= 4096 && a < 24576 && b < 64 {
                    ((a - 0x1000) * 64 + b) as usize + 262144
                } else if a >= 0x7FFFFFFFFFFFD000
                    && a < 0x8000000000001000
                    && (a & 7) == 0
                    && b < 64
                {
                    (((a - 0x7FFFFFFFFFFFD000) / 8) * 64 + b) as usize + 1572864
                } else if a >= 0xDE0B6B3A763FF000
                    && a < 0xDE0B6B3A76401000
                    && (a & 7) == 0
                    && b >= 1
                    && b < 56
                {
                    (((a - 0xDE0B6B3A763FF000) / 8) * 55 + (b - 0x1)) as usize + 1703936
                } else {
                    Self::NO_FROPS
                }
            }
            OP_SRA => {
                if a < 4041 && b < 17 {
                    (a * 17 + b) as usize
                } else if a >= 4096 && a < 28672 && (a & 3) == 0 && b >= 3 && b < 17 {
                    (((a - 0x1000) / 4) * 14 + (b - 0x3)) as usize + 68697
                } else if a >= 0x12C00004 && a < 0x12C01004 && (a & 7) == 4 && b == 16 {
                    ((a - 0x12C00004) / 8) as usize + 154713
                } else if a >= 0xFFFFFFFFFFFFFF80 && b < 9 {
                    ((a - 0xFFFFFFFFFFFFFF80) * 9 + b) as usize + 155225
                } else {
                    Self::NO_FROPS
                }
            }
            OP_SLLW => {
                if a < 2046 && b < 12 {
                    (a * 12 + b) as usize
                } else {
                    Self::NO_FROPS
                }
            }
            OP_SRLW => {
                if a < 16 && b < 4 {
                    (a * 4 + b) as usize
                } else {
                    Self::NO_FROPS
                }
            }
            OP_SRAW => {
                if a < 254 && b < 7 {
                    (a * 7 + b) as usize
                } else {
                    Self::NO_FROPS
                }
            }
            OP_SIGNEXTENDB => {
                if a == 0 && b < 257 {
                    (a * 257 + b) as usize
                } else if a >= 0xA03FC000 && a < 0xA03FF000 && (a & 7) == 0 && b < 252 {
                    (((a - 0xA03FC000) / 8) * 252 + b) as usize + 257
                } else {
                    Self::NO_FROPS
                }
            }
            OP_SIGNEXTENDH => {
                if a == 0 && b < 2901 {
                    (a * 2901 + b) as usize
                } else if a >= 0x800D5000 && a < 0x800D6000 && (a & 7) == 0 && b < 6 {
                    (((a - 0x800D5000) / 8) * 6 + b) as usize + 2901
                } else if a >= 0x800D5000 && a < 0x800D6000 && (a & 7) == 0 && b == 100 {
                    ((a - 0x800D5000) / 8) as usize + 5973
                } else {
                    Self::NO_FROPS
                }
            }
            OP_SIGNEXTENDW => {
                if a >= 0x800D5000 && a < 0x800D6000 && (a & 3) == 0 && b == 100 {
                    ((a - 0x800D5000) / 4) as usize
                } else if a >= 0xAABC9000 && a < 0xAABCA000 && (a & 7) == 0 && b < 15 {
                    (((a - 0xAABC9000) / 8) * 15 + b) as usize + 1024
                } else if a >= 0xAAC0C000 && a < 0xAAC0E000 && (a & 7) == 0 && b < 15 {
                    (((a - 0xAAC0C000) / 8) * 15 + b) as usize + 8704
                } else if a >= 0xAACAE000 && a < 0xAACB0000 && (a & 7) == 0 && b < 15 {
                    (((a - 0xAACAE000) / 8) * 15 + b) as usize + 24064
                } else {
                    Self::NO_FROPS
                }
            }
            OP_REV8 => {
                if a == 0 && b < 4096 {
                    (a * 4096 + b) as usize
                } else {
                    Self::NO_FROPS
                }
            }
            OP_CLZ => {
                if a == 0 && b < 4096 {
                    (a * 4096 + b) as usize
                } else {
                    Self::NO_FROPS
                }
            }
            OP_CLZW => {
                if a == 0 && b < 69 {
                    (a * 69 + b) as usize
                } else {
                    Self::NO_FROPS
                }
            }
            OP_CPOP => {
                if a == 0 && b < 256 {
                    (a * 256 + b) as usize
                } else {
                    Self::NO_FROPS
                }
            }
            OP_ORCB => {
                if a == 0 && b < 3914 {
                    (a * 3914 + b) as usize
                } else {
                    Self::NO_FROPS
                }
            }
            OP_BEXT => {
                if a < 273 && b < 5 {
                    (a * 5 + b) as usize
                } else {
                    Self::NO_FROPS
                }
            }
            OP_BINV => {
                if a < 2 && b < 64 {
                    (a * 64 + b) as usize
                } else {
                    Self::NO_FROPS
                }
            }
            OP_BSET => {
                if a == 0 && b < 4096 {
                    (a * 4096 + b) as usize
                } else {
                    Self::NO_FROPS
                }
            }
            OP_SLLUW => {
                if a < 1109 && b < 10 {
                    (a * 10 + b) as usize
                } else {
                    Self::NO_FROPS
                }
            }
            _ => return Self::NO_FROPS,
        };
        if relative_offset == Self::NO_FROPS {
            Self::NO_FROPS
        } else {
            relative_offset + OP_TABLE_OFFSETS[op as usize - OP_TABLE_OFFSETS_START]
        }
    }

    #[inline(always)]
    pub fn count(&self) -> usize {
        self.table.count()
    }

    #[cfg(test)]
    pub fn test_table_offsets(&mut self) {
        self.build_table();
        let (start, offsets) = self.table.generate_table_offsets();
        if (start != OP_TABLE_OFFSETS_START) || (offsets != OP_TABLE_OFFSETS) {
            self.table.print_table_offsets();
            panic!("Table offsets do not match expected values");
        }
        assert_eq!(start, OP_TABLE_OFFSETS_START);
        assert_eq!(offsets, OP_TABLE_OFFSETS);
    }

    #[inline(always)]
    pub fn generate_full_table(&self) -> Vec<(u8, u64, u64, u64, bool)> {
        self.table.generate_full_table()
    }

    #[inline(always)]
    pub fn generate_table(&self) -> Vec<(u8, u64, u64)> {
        self.table.generate_table()
    }

    #[inline(always)]
    pub fn generate_cmd(
        &mut self,
        cmd_name: &'static str,
        default_file: &'static str,
    ) -> Result<(), Box<dyn Error>> {
        self.build_table();
        let full_table = self.generate_full_table();
        let full_table_count = full_table.len();
        self.table.generate_cmd(
            "Zisk",
            "BinaryExtensionFrops",
            cmd_name,
            default_file,
            full_table,
            full_table_count,
        )
    }
}

#[test]
fn test_table_offsets() {
    let mut fops = BinaryExtensionFrops::new();
    fops.test_table_offsets();
}

#[test]
fn test_all_accessible_values() {
    let mut fops = BinaryExtensionFrops::new();
    fops.build_table();
    let table = fops.generate_full_table();
    FrequentOpsHelpers::test_all_accessible_values(
        &table,
        BinaryExtensionFrops::is_frequent_op,
        BinaryExtensionFrops::get_row,
    );
}
