[package]
name = "sm-frequent-ops"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[[bin]]
name = "frequent_ops_test"
path = "src/frequent_ops_test.rs"

[dependencies]
zisk-core = { workspace = true }
zisk-common = { workspace = true }
zisk-pil = { workspace = true }

fields = { workspace=true }
proofman = { workspace = true }
proofman-common = { workspace = true }
proofman-macros = { workspace = true }
proofman-util = { workspace = true }
pil-std-lib = { workspace = true }
tracing = { workspace = true }

clap = "4.0"
rayon = { workspace = true }
num-bigint = { workspace = true }
static_assertions = { workspace = true }

[features]
default = []
diagnostic = ["proofman-macros/diagnostic", "proofman/diagnostic"]
generate_code_arith_range_table = []
no_lib_link = ["proofman-common/no_lib_link"]
disable_distributed = ["proofman/disable_distributed", "proofman-common/disable_distributed"]