[service]
name = "consensus-network"
environment = "development"

[server]
host = "127.0.0.1"
port = 50051

[logging]
level = "debug"
format = "pretty"
file_output = false

[comm]
max_peers = 10
discovery_interval_seconds = 30
heartbeat_interval_seconds = 5

