[package]
name = "zisk-sm-mem"
description = "Memory state machine for the ZisK zkVM"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[[bin]]
name = "zisk-mem-sim"
path = "src/mem_sim.rs"

[dependencies]
zisk-core = { workspace = true }
zisk-common = { workspace = true }
zisk-pil = { workspace = true }
zisk-sm-mem-common = { workspace = true }

proofman-common = { workspace = true }
proofman-util = { workspace = true }
pil2-std-lib = { workspace = true }

proofman-fields = { workspace = true }
tracing = { workspace = true }
rayon = { workspace = true }
env = { workspace = true }

[features]
default = []
debug_mem = ["zisk-sm-mem-common/debug_mem"]
debug_mem_align = []
debug_mem_offsets = []
debug_mem_bin_offsets = []
save_mem_bus_data = []
save_mem_plans = []
save_mem_counters = []
mem_align_stats = []
save_addr_action = []
legacy_mem_count_and_plan = []
