[package]
name = "consensus-config"
description = "Configuration management for Consensus Network"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
config = { version = "0.15" }
chrono = { workspace = true }
anyhow = { workspace = true }
