[package]
name = "consensus-config"
description = "Configuration management for Consensus Network"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
config = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
