pub const MEM_ADDR_MASK: u32 = 0xFFFF_FFF8;
pub const MEM_BYTES_BITS: u32 = 3;
pub const MEM_BYTES: u32 = 1 << MEM_BYTES_BITS;

pub const MEM_STEP_BASE: u64 = 1;
pub const MAX_MEM_STEP_OFFSET: u64 = 2;
pub const MAX_MEM_OPS_BY_STEP_OFFSET: u64 = 2;
pub const MAX_MEM_OPS_BY_MAIN_STEP: u64 = (MAX_MEM_STEP_OFFSET + 1) * MAX_MEM_OPS_BY_STEP_OFFSET;

pub const MEMORY_LOAD_OP: u64 = 1;
pub const MEMORY_STORE_OP: u64 = 2;

pub const MAX_MAIN_STEP: u64 = 0x1FFF_FFFF_FFFF_FFFF;
pub const MAX_MEM_STEP: u64 = MEM_STEP_BASE +
    MAX_MEM_OPS_BY_MAIN_STEP * MAX_MAIN_STEP +
    MAX_MEM_OPS_BY_STEP_OFFSET * MAX_MEM_STEP_OFFSET;

pub const MAX_MEM_ADDR: u64 = 0xFFFF_FFFF;

pub const MEMORY_MAX_DIFF: u64 = 1 << 24;
