name: "CLA Signature Bot"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  cla:
    if: github.event.repository.private == false
    uses: 0xPolygonHermez/.github-cla/.github/workflows/cla-reusable.yml@main
    secrets: inherit
