name: Test ZisK

on:
  pull_request:
    branches:
      - develop
      - main
      - "pre-develop-[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - 'book/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cargo-tests:
    name: Cargo tests
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd "$GITHUB_WORKSPACE/tools/test-env"
          sudo ./install_deps.sh

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets # --all-features

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --release
        env:
          RUSTFLAGS: -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0 -C target-cpu=native
          RUST_BACKTRACE: 1

  test-x86_64:
    name: Test on Ubuntu x86_64
    runs-on: gpu-hosted
    timeout-minutes: 180
    defaults:
      run:
        shell: bash
    env:
      TEST_CONTAINER: zisk-gha-test
      ZISK_TESTVECTORS_BRANCH: "develop-0.3.0"

    steps:
      - name: Fix workspace permissions
        run: |
          sudo chown -R "$(id -u):$(id -g)" "$GITHUB_WORKSPACE" || true
          sudo chmod -R u+rwX "$GITHUB_WORKSPACE" || true

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Start test container with systemd
        run: |
          docker rm -f "${TEST_CONTAINER}" || true

          docker run -d \
            --name "${TEST_CONTAINER}" \
            --privileged \
            --cgroupns=host \
            --gpus all \
            --shm-size=48g \
            -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
            -v "$GITHUB_WORKSPACE":/workspace/zisk:rw \
            -v /home/gha/cache-setup:/github/home/output:rw \
            -e ZISK_GHA=1 \
            -e ZISK_REPO_DIR=/workspace/zisk \
            -e ZISK_TESTVECTORS_BRANCH=${ZISK_TESTVECTORS_BRANCH} \
            -e PROVE_FLAGS=-y \
            -e TERM=xterm \
            ziskvm/zisk-gpu-runner:latest

          docker exec -u ziskuser \
            "${TEST_CONTAINER}" bash -lc '
            echo "PID 1:"
            ps -p 1 -o pid,comm,args
            systemctl is-system-running || true
          '

      - name: Fix workspace permissions inside container
        run: |
          docker exec "${TEST_CONTAINER}" bash -lc '
            chown -R ziskuser:ziskuser /workspace/zisk
            chmod -R u+rwX /workspace/zisk
          '
          
      - name: Build ZisK
        run: |
          docker exec -u ziskuser \
            "${TEST_CONTAINER}" bash -lc '
            cd /workspace/zisk/tools/test-env
            ./build_zisk.sh
          '

      - name: Build setup
        run: |
          docker exec -u ziskuser \
            -e USE_CACHE_SETUP="1" \
            -e CACHE_SETUP_HASH="e7de7a73" \
            "${TEST_CONTAINER}" bash -lc '
              cd /workspace/zisk/tools/test-env
              ./build_setup.sh
              echo "Proving key should be available at: /github/home/.zisk/provingKey"
              ls -lha /github/home/.zisk/provingKey
            '

      # - name: Test sha_hasher (CPU)
      #   run: |
      #     docker exec -u ziskuser \
      #       -e ONLY_CPU="1" \
      #       -e ZISK_TEMPLATE_BRANCH="pre-develop-0.17.1" \
      #       "${TEST_CONTAINER}" bash -lc '
      #         cd /workspace/zisk/tools/test-env
      #         ./test_sha_hasher.sh
      #       '

      # - name: Test sha_hasher (GPU)
      #   run: |
      #     docker exec -u ziskuser \
      #       -e ZISK_TEMPLATE_BRANCH="pre-develop-0.17.1" \
      #       "${TEST_CONTAINER}" bash -lc '
      #         cd /workspace/zisk/tools/test-env
      #         ./test_sha_hasher.sh
      #       '

      - name: Test ELF diagnostic
        run: |
          docker exec -u ziskuser \
            "${TEST_CONTAINER}" bash -lc '
            cd /workspace/zisk/tools/test-env
            echo "Proving key should be available at: /github/home/.zisk/provingKey"
            ls -lha /github/home/.zisk/provingKey
            ./test_diagnostic.sh
          '

      - name: Prove Ethereum block
        run: |
          docker exec -u ziskuser \
            -e BLOCK_INPUTS_SINGLE="mainnet_24628607_66_7_zec_reth.bin,mainnet_24626900_221_16_zec_reth.bin" \
            "${TEST_CONTAINER}" bash -lc '
              cd /workspace/zisk/tools/test-env
              ./test_eth_block.sh
            '

      - name: Ethproofs test (no hints)
        run: |
          docker exec -u ziskuser \
            -e BLOCK_INPUTS_ETHPROOFS="mainnet_24628595_641_54_zec_reth.bin,mainnet_24697073_308_22_zec_reth.bin" \
            "${TEST_CONTAINER}" bash -lc '
              cd /workspace/zisk/tools/test-env
              echo "ZisK binary should be available at: /github/home/.zisk/bin/"
              ls /github/home/.zisk/bin/
              ./test_ethproofs.sh
            '

      - name: Ethproofs test (hints)
        run: |
          docker exec -u ziskuser \
            -e BLOCK_INPUTS_ETHPROOFS_HINTS="mainnet_24628611_627_58_zec_reth.bin,mainnet_24628590_478_49_zec_reth.bin" \
            "${TEST_CONTAINER}" bash -lc '
              cd /workspace/zisk/tools/test-env
              ./test_ethproofs.sh
            '

      - name: Stop test container
        if: always()
        run: |
          docker rm -f "${TEST_CONTAINER}" || true
          sudo chown -R "$(id -u):$(id -g)" "$GITHUB_WORKSPACE" || true
          sudo chmod -R u+rwX "$GITHUB_WORKSPACE" || true

  test-macos:
    name: Test on macOS
    runs-on: macos-14
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    env:
      ZISK_GHA: "1"
      ZISK_REPO_DIR: ${{ github.workspace }}
      TERM: xterm
    steps:
      - name: Check Rust version
        run: rustc --version

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd "$GITHUB_WORKSPACE/tools/test-env"
          ./install_deps.sh

      - name: Build ZisK
        run: |
          cd "$GITHUB_WORKSPACE/tools/test-env"
          ./build_zisk.sh

      - name: Test sha_hasher
        env:
          ZISK_TEMPLATE_BRANCH: "pre-develop-0.17.1"
        run: |
          cd "$GITHUB_WORKSPACE/tools/test-env"
          ./test_sha_hasher.sh

  lint:
    name: Format & Clippy on ${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            platform: Ubuntu x86_64
          - runner: macos-14
            target: aarch64-apple-darwin
            platform: macOS
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Install dependencies
        run: |
          cd "$GITHUB_WORKSPACE/tools/test-env"
          ./install_deps.sh

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
        env:
          CARGO_INCREMENTAL: 1

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          # args: --all-targets -- -D warnings
          args: --all-features --all-targets -- -D warnings -A incomplete-features
        env:
          CARGO_INCREMENTAL: 1
