name: Test ELF Assembly

on:
  push:
    branches: [develop]
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  test-elf-regressions:
    name: Test ELF Regressions
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          cd "$GITHUB_WORKSPACE/tools/test-env"
          sudo ./install_deps.sh
      
      - name: Build ZisK
        run: |
          cd "$GITHUB_WORKSPACE/tools/test-env"
          ./build_zisk.sh
      
      - name: Verify ZisK binaries are available
        run: |
          echo "Checking if binaries are in PATH..."
          which cargo-zisk && echo "✓ cargo-zisk found at: $(which cargo-zisk)"
          which ziskemu && echo "✓ ziskemu found at: $(which ziskemu)"

      - name: Build assembly tests
        working-directory: elf-regressions
        run: ./scripts/build.sh --clean
      
      - name: Test with rom-setup
        working-directory: elf-regressions
        run: ./scripts/test.sh rom-setup all
        env:
          CARGO_ZISK_PATH: cargo-zisk
          ZISKEMU_PATH: ziskemu
      
      - name: Test with emulator  
        working-directory: elf-regressions
        run: ./scripts/test.sh emu all
        env:
          CARGO_ZISK_PATH: cargo-zisk
          ZISKEMU_PATH: ziskemu